/*
Story Engine API

Testing AuthoringAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package storyteller

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/arcana261/story-teller-client-go"
)

func Test_storyteller_AuthoringAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test AuthoringAPIService DeleteStoryV1AuthoringStoriesStoryIdDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var storyId string

		httpRes, err := apiClient.AuthoringAPI.DeleteStoryV1AuthoringStoriesStoryIdDelete(context.Background(), storyId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AuthoringAPIService GenerateStoryV1AuthoringStoriesPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.AuthoringAPI.GenerateStoryV1AuthoringStoriesPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AuthoringAPIService GetAuthoringExplorationNodeV1AuthoringStoriesStoryIdExplorationNodesNodeIdGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var storyId string
		var nodeId string

		resp, httpRes, err := apiClient.AuthoringAPI.GetAuthoringExplorationNodeV1AuthoringStoriesStoryIdExplorationNodesNodeIdGet(context.Background(), storyId, nodeId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AuthoringAPIService GetJobStatusV1AuthoringJobsJobIdGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var jobId string

		resp, httpRes, err := apiClient.AuthoringAPI.GetJobStatusV1AuthoringJobsJobIdGet(context.Background(), jobId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AuthoringAPIService GetStoryGraphV1AuthoringStoriesStoryIdGraphGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var storyId string

		resp, httpRes, err := apiClient.AuthoringAPI.GetStoryGraphV1AuthoringStoriesStoryIdGraphGet(context.Background(), storyId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AuthoringAPIService GetStoryPathsV1AuthoringStoriesStoryIdPathsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var storyId string

		resp, httpRes, err := apiClient.AuthoringAPI.GetStoryPathsV1AuthoringStoriesStoryIdPathsGet(context.Background(), storyId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AuthoringAPIService GetStoryV1AuthoringStoriesStoryIdGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var storyId string

		resp, httpRes, err := apiClient.AuthoringAPI.GetStoryV1AuthoringStoriesStoryIdGet(context.Background(), storyId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AuthoringAPIService ListAuthoringExplorationNodesV1AuthoringStoriesStoryIdExplorationNodesGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var storyId string

		resp, httpRes, err := apiClient.AuthoringAPI.ListAuthoringExplorationNodesV1AuthoringStoriesStoryIdExplorationNodesGet(context.Background(), storyId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AuthoringAPIService ListStoriesV1AuthoringStoriesGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.AuthoringAPI.ListStoriesV1AuthoringStoriesGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AuthoringAPIService PatchAuthoringExplorationNodeV1AuthoringStoriesStoryIdExplorationNodesNodeIdPatch", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var storyId string
		var nodeId string

		resp, httpRes, err := apiClient.AuthoringAPI.PatchAuthoringExplorationNodeV1AuthoringStoriesStoryIdExplorationNodesNodeIdPatch(context.Background(), storyId, nodeId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AuthoringAPIService StreamJobStatusV1AuthoringJobsJobIdStreamGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var jobId string

		resp, httpRes, err := apiClient.AuthoringAPI.StreamJobStatusV1AuthoringJobsJobIdStreamGet(context.Background(), jobId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
