/*
Story Engine API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.12
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package storyteller

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SessionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SessionResponse{}

// SessionResponse Player session state returned by session-creation and choice-submission endpoints.  ``playthrough_id`` identifies the current run within a stable ``session_id``. It changes after reset and gives clients a cheap way to discard stale local caches or in-flight request bookkeeping from the previous run.  ``lock_token`` is a UUID issued when a free-text request starts processing. The client must include it in concurrent requests to avoid races; it is ``None`` when no lock is currently held.  ``is_completed`` becomes ``True`` when the player reaches an END node and the story does not allow free-text continuation.
type SessionResponse struct {
	SessionId string `json:"session_id"`
	PlaythroughId string `json:"playthrough_id"`
	CurrentNodeId string `json:"current_node_id"`
	WorldFlags map[string]interface{} `json:"world_flags"`
	DiscoveredLocations map[string]LocationSpecResponse `json:"discovered_locations,omitempty"`
	DiscoveredObjects map[string]ObjectSpecResponse `json:"discovered_objects,omitempty"`
	DiscoveredFlagSchema map[string]interface{} `json:"discovered_flag_schema,omitempty"`
	NodesVisited int32 `json:"nodes_visited"`
	IsCompleted bool `json:"is_completed"`
	LockToken NullableString `json:"lock_token,omitempty"`
	WarningsAcknowledgedAt NullableString `json:"warnings_acknowledged_at,omitempty"`
}

type _SessionResponse SessionResponse

// NewSessionResponse instantiates a new SessionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSessionResponse(sessionId string, playthroughId string, currentNodeId string, worldFlags map[string]interface{}, nodesVisited int32, isCompleted bool) *SessionResponse {
	this := SessionResponse{}
	this.SessionId = sessionId
	this.PlaythroughId = playthroughId
	this.CurrentNodeId = currentNodeId
	this.WorldFlags = worldFlags
	this.NodesVisited = nodesVisited
	this.IsCompleted = isCompleted
	return &this
}

// NewSessionResponseWithDefaults instantiates a new SessionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSessionResponseWithDefaults() *SessionResponse {
	this := SessionResponse{}
	return &this
}

// GetSessionId returns the SessionId field value
func (o *SessionResponse) GetSessionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SessionId
}

// GetSessionIdOk returns a tuple with the SessionId field value
// and a boolean to check if the value has been set.
func (o *SessionResponse) GetSessionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SessionId, true
}

// SetSessionId sets field value
func (o *SessionResponse) SetSessionId(v string) {
	o.SessionId = v
}

// GetPlaythroughId returns the PlaythroughId field value
func (o *SessionResponse) GetPlaythroughId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PlaythroughId
}

// GetPlaythroughIdOk returns a tuple with the PlaythroughId field value
// and a boolean to check if the value has been set.
func (o *SessionResponse) GetPlaythroughIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlaythroughId, true
}

// SetPlaythroughId sets field value
func (o *SessionResponse) SetPlaythroughId(v string) {
	o.PlaythroughId = v
}

// GetCurrentNodeId returns the CurrentNodeId field value
func (o *SessionResponse) GetCurrentNodeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CurrentNodeId
}

// GetCurrentNodeIdOk returns a tuple with the CurrentNodeId field value
// and a boolean to check if the value has been set.
func (o *SessionResponse) GetCurrentNodeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CurrentNodeId, true
}

// SetCurrentNodeId sets field value
func (o *SessionResponse) SetCurrentNodeId(v string) {
	o.CurrentNodeId = v
}

// GetWorldFlags returns the WorldFlags field value
func (o *SessionResponse) GetWorldFlags() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.WorldFlags
}

// GetWorldFlagsOk returns a tuple with the WorldFlags field value
// and a boolean to check if the value has been set.
func (o *SessionResponse) GetWorldFlagsOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.WorldFlags, true
}

// SetWorldFlags sets field value
func (o *SessionResponse) SetWorldFlags(v map[string]interface{}) {
	o.WorldFlags = v
}

// GetDiscoveredLocations returns the DiscoveredLocations field value if set, zero value otherwise.
func (o *SessionResponse) GetDiscoveredLocations() map[string]LocationSpecResponse {
	if o == nil || IsNil(o.DiscoveredLocations) {
		var ret map[string]LocationSpecResponse
		return ret
	}
	return o.DiscoveredLocations
}

// GetDiscoveredLocationsOk returns a tuple with the DiscoveredLocations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionResponse) GetDiscoveredLocationsOk() (map[string]LocationSpecResponse, bool) {
	if o == nil || IsNil(o.DiscoveredLocations) {
		return map[string]LocationSpecResponse{}, false
	}
	return o.DiscoveredLocations, true
}

// HasDiscoveredLocations returns a boolean if a field has been set.
func (o *SessionResponse) HasDiscoveredLocations() bool {
	if o != nil && !IsNil(o.DiscoveredLocations) {
		return true
	}

	return false
}

// SetDiscoveredLocations gets a reference to the given map[string]LocationSpecResponse and assigns it to the DiscoveredLocations field.
func (o *SessionResponse) SetDiscoveredLocations(v map[string]LocationSpecResponse) {
	o.DiscoveredLocations = v
}

// GetDiscoveredObjects returns the DiscoveredObjects field value if set, zero value otherwise.
func (o *SessionResponse) GetDiscoveredObjects() map[string]ObjectSpecResponse {
	if o == nil || IsNil(o.DiscoveredObjects) {
		var ret map[string]ObjectSpecResponse
		return ret
	}
	return o.DiscoveredObjects
}

// GetDiscoveredObjectsOk returns a tuple with the DiscoveredObjects field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionResponse) GetDiscoveredObjectsOk() (map[string]ObjectSpecResponse, bool) {
	if o == nil || IsNil(o.DiscoveredObjects) {
		return map[string]ObjectSpecResponse{}, false
	}
	return o.DiscoveredObjects, true
}

// HasDiscoveredObjects returns a boolean if a field has been set.
func (o *SessionResponse) HasDiscoveredObjects() bool {
	if o != nil && !IsNil(o.DiscoveredObjects) {
		return true
	}

	return false
}

// SetDiscoveredObjects gets a reference to the given map[string]ObjectSpecResponse and assigns it to the DiscoveredObjects field.
func (o *SessionResponse) SetDiscoveredObjects(v map[string]ObjectSpecResponse) {
	o.DiscoveredObjects = v
}

// GetDiscoveredFlagSchema returns the DiscoveredFlagSchema field value if set, zero value otherwise.
func (o *SessionResponse) GetDiscoveredFlagSchema() map[string]interface{} {
	if o == nil || IsNil(o.DiscoveredFlagSchema) {
		var ret map[string]interface{}
		return ret
	}
	return o.DiscoveredFlagSchema
}

// GetDiscoveredFlagSchemaOk returns a tuple with the DiscoveredFlagSchema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionResponse) GetDiscoveredFlagSchemaOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.DiscoveredFlagSchema) {
		return map[string]interface{}{}, false
	}
	return o.DiscoveredFlagSchema, true
}

// HasDiscoveredFlagSchema returns a boolean if a field has been set.
func (o *SessionResponse) HasDiscoveredFlagSchema() bool {
	if o != nil && !IsNil(o.DiscoveredFlagSchema) {
		return true
	}

	return false
}

// SetDiscoveredFlagSchema gets a reference to the given map[string]interface{} and assigns it to the DiscoveredFlagSchema field.
func (o *SessionResponse) SetDiscoveredFlagSchema(v map[string]interface{}) {
	o.DiscoveredFlagSchema = v
}

// GetNodesVisited returns the NodesVisited field value
func (o *SessionResponse) GetNodesVisited() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NodesVisited
}

// GetNodesVisitedOk returns a tuple with the NodesVisited field value
// and a boolean to check if the value has been set.
func (o *SessionResponse) GetNodesVisitedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NodesVisited, true
}

// SetNodesVisited sets field value
func (o *SessionResponse) SetNodesVisited(v int32) {
	o.NodesVisited = v
}

// GetIsCompleted returns the IsCompleted field value
func (o *SessionResponse) GetIsCompleted() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsCompleted
}

// GetIsCompletedOk returns a tuple with the IsCompleted field value
// and a boolean to check if the value has been set.
func (o *SessionResponse) GetIsCompletedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsCompleted, true
}

// SetIsCompleted sets field value
func (o *SessionResponse) SetIsCompleted(v bool) {
	o.IsCompleted = v
}

// GetLockToken returns the LockToken field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SessionResponse) GetLockToken() string {
	if o == nil || IsNil(o.LockToken.Get()) {
		var ret string
		return ret
	}
	return *o.LockToken.Get()
}

// GetLockTokenOk returns a tuple with the LockToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SessionResponse) GetLockTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LockToken.Get(), o.LockToken.IsSet()
}

// HasLockToken returns a boolean if a field has been set.
func (o *SessionResponse) HasLockToken() bool {
	if o != nil && o.LockToken.IsSet() {
		return true
	}

	return false
}

// SetLockToken gets a reference to the given NullableString and assigns it to the LockToken field.
func (o *SessionResponse) SetLockToken(v string) {
	o.LockToken.Set(&v)
}
// SetLockTokenNil sets the value for LockToken to be an explicit nil
func (o *SessionResponse) SetLockTokenNil() {
	o.LockToken.Set(nil)
}

// UnsetLockToken ensures that no value is present for LockToken, not even an explicit nil
func (o *SessionResponse) UnsetLockToken() {
	o.LockToken.Unset()
}

// GetWarningsAcknowledgedAt returns the WarningsAcknowledgedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SessionResponse) GetWarningsAcknowledgedAt() string {
	if o == nil || IsNil(o.WarningsAcknowledgedAt.Get()) {
		var ret string
		return ret
	}
	return *o.WarningsAcknowledgedAt.Get()
}

// GetWarningsAcknowledgedAtOk returns a tuple with the WarningsAcknowledgedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SessionResponse) GetWarningsAcknowledgedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.WarningsAcknowledgedAt.Get(), o.WarningsAcknowledgedAt.IsSet()
}

// HasWarningsAcknowledgedAt returns a boolean if a field has been set.
func (o *SessionResponse) HasWarningsAcknowledgedAt() bool {
	if o != nil && o.WarningsAcknowledgedAt.IsSet() {
		return true
	}

	return false
}

// SetWarningsAcknowledgedAt gets a reference to the given NullableString and assigns it to the WarningsAcknowledgedAt field.
func (o *SessionResponse) SetWarningsAcknowledgedAt(v string) {
	o.WarningsAcknowledgedAt.Set(&v)
}
// SetWarningsAcknowledgedAtNil sets the value for WarningsAcknowledgedAt to be an explicit nil
func (o *SessionResponse) SetWarningsAcknowledgedAtNil() {
	o.WarningsAcknowledgedAt.Set(nil)
}

// UnsetWarningsAcknowledgedAt ensures that no value is present for WarningsAcknowledgedAt, not even an explicit nil
func (o *SessionResponse) UnsetWarningsAcknowledgedAt() {
	o.WarningsAcknowledgedAt.Unset()
}

func (o SessionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SessionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["session_id"] = o.SessionId
	toSerialize["playthrough_id"] = o.PlaythroughId
	toSerialize["current_node_id"] = o.CurrentNodeId
	toSerialize["world_flags"] = o.WorldFlags
	if !IsNil(o.DiscoveredLocations) {
		toSerialize["discovered_locations"] = o.DiscoveredLocations
	}
	if !IsNil(o.DiscoveredObjects) {
		toSerialize["discovered_objects"] = o.DiscoveredObjects
	}
	if !IsNil(o.DiscoveredFlagSchema) {
		toSerialize["discovered_flag_schema"] = o.DiscoveredFlagSchema
	}
	toSerialize["nodes_visited"] = o.NodesVisited
	toSerialize["is_completed"] = o.IsCompleted
	if o.LockToken.IsSet() {
		toSerialize["lock_token"] = o.LockToken.Get()
	}
	if o.WarningsAcknowledgedAt.IsSet() {
		toSerialize["warnings_acknowledged_at"] = o.WarningsAcknowledgedAt.Get()
	}
	return toSerialize, nil
}

func (o *SessionResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"session_id",
		"playthrough_id",
		"current_node_id",
		"world_flags",
		"nodes_visited",
		"is_completed",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSessionResponse := _SessionResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSessionResponse)

	if err != nil {
		return err
	}

	*o = SessionResponse(varSessionResponse)

	return err
}

type NullableSessionResponse struct {
	value *SessionResponse
	isSet bool
}

func (v NullableSessionResponse) Get() *SessionResponse {
	return v.value
}

func (v *NullableSessionResponse) Set(val *SessionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSessionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSessionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSessionResponse(val *SessionResponse) *NullableSessionResponse {
	return &NullableSessionResponse{value: val, isSet: true}
}

func (v NullableSessionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSessionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


