/*
Story Engine API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.12
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package storyteller

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NodeMetadata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NodeMetadata{}

// NodeMetadata Audience and arc metadata attached to every node response.  ``drama_score`` is populated by ``DramaManager`` when arc analysis is available; it is ``None`` for nodes retrieved without arc context.
type NodeMetadata struct {
	AgeRating string `json:"age_rating"`
	Mood string `json:"mood"`
	Genre string `json:"genre"`
	Themes []string `json:"themes"`
	Complexity int32 `json:"complexity"`
	DramaScore NullableFloat32 `json:"drama_score,omitempty"`
}

type _NodeMetadata NodeMetadata

// NewNodeMetadata instantiates a new NodeMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNodeMetadata(ageRating string, mood string, genre string, themes []string, complexity int32) *NodeMetadata {
	this := NodeMetadata{}
	this.AgeRating = ageRating
	this.Mood = mood
	this.Genre = genre
	this.Themes = themes
	this.Complexity = complexity
	return &this
}

// NewNodeMetadataWithDefaults instantiates a new NodeMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNodeMetadataWithDefaults() *NodeMetadata {
	this := NodeMetadata{}
	return &this
}

// GetAgeRating returns the AgeRating field value
func (o *NodeMetadata) GetAgeRating() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AgeRating
}

// GetAgeRatingOk returns a tuple with the AgeRating field value
// and a boolean to check if the value has been set.
func (o *NodeMetadata) GetAgeRatingOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgeRating, true
}

// SetAgeRating sets field value
func (o *NodeMetadata) SetAgeRating(v string) {
	o.AgeRating = v
}

// GetMood returns the Mood field value
func (o *NodeMetadata) GetMood() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Mood
}

// GetMoodOk returns a tuple with the Mood field value
// and a boolean to check if the value has been set.
func (o *NodeMetadata) GetMoodOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mood, true
}

// SetMood sets field value
func (o *NodeMetadata) SetMood(v string) {
	o.Mood = v
}

// GetGenre returns the Genre field value
func (o *NodeMetadata) GetGenre() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Genre
}

// GetGenreOk returns a tuple with the Genre field value
// and a boolean to check if the value has been set.
func (o *NodeMetadata) GetGenreOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Genre, true
}

// SetGenre sets field value
func (o *NodeMetadata) SetGenre(v string) {
	o.Genre = v
}

// GetThemes returns the Themes field value
func (o *NodeMetadata) GetThemes() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Themes
}

// GetThemesOk returns a tuple with the Themes field value
// and a boolean to check if the value has been set.
func (o *NodeMetadata) GetThemesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Themes, true
}

// SetThemes sets field value
func (o *NodeMetadata) SetThemes(v []string) {
	o.Themes = v
}

// GetComplexity returns the Complexity field value
func (o *NodeMetadata) GetComplexity() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Complexity
}

// GetComplexityOk returns a tuple with the Complexity field value
// and a boolean to check if the value has been set.
func (o *NodeMetadata) GetComplexityOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Complexity, true
}

// SetComplexity sets field value
func (o *NodeMetadata) SetComplexity(v int32) {
	o.Complexity = v
}

// GetDramaScore returns the DramaScore field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NodeMetadata) GetDramaScore() float32 {
	if o == nil || IsNil(o.DramaScore.Get()) {
		var ret float32
		return ret
	}
	return *o.DramaScore.Get()
}

// GetDramaScoreOk returns a tuple with the DramaScore field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NodeMetadata) GetDramaScoreOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.DramaScore.Get(), o.DramaScore.IsSet()
}

// HasDramaScore returns a boolean if a field has been set.
func (o *NodeMetadata) HasDramaScore() bool {
	if o != nil && o.DramaScore.IsSet() {
		return true
	}

	return false
}

// SetDramaScore gets a reference to the given NullableFloat32 and assigns it to the DramaScore field.
func (o *NodeMetadata) SetDramaScore(v float32) {
	o.DramaScore.Set(&v)
}
// SetDramaScoreNil sets the value for DramaScore to be an explicit nil
func (o *NodeMetadata) SetDramaScoreNil() {
	o.DramaScore.Set(nil)
}

// UnsetDramaScore ensures that no value is present for DramaScore, not even an explicit nil
func (o *NodeMetadata) UnsetDramaScore() {
	o.DramaScore.Unset()
}

func (o NodeMetadata) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NodeMetadata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["age_rating"] = o.AgeRating
	toSerialize["mood"] = o.Mood
	toSerialize["genre"] = o.Genre
	toSerialize["themes"] = o.Themes
	toSerialize["complexity"] = o.Complexity
	if o.DramaScore.IsSet() {
		toSerialize["drama_score"] = o.DramaScore.Get()
	}
	return toSerialize, nil
}

func (o *NodeMetadata) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"age_rating",
		"mood",
		"genre",
		"themes",
		"complexity",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNodeMetadata := _NodeMetadata{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNodeMetadata)

	if err != nil {
		return err
	}

	*o = NodeMetadata(varNodeMetadata)

	return err
}

type NullableNodeMetadata struct {
	value *NodeMetadata
	isSet bool
}

func (v NullableNodeMetadata) Get() *NodeMetadata {
	return v.value
}

func (v *NullableNodeMetadata) Set(val *NodeMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableNodeMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableNodeMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNodeMetadata(val *NodeMetadata) *NullableNodeMetadata {
	return &NullableNodeMetadata{value: val, isSet: true}
}

func (v NullableNodeMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNodeMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


