/*
Story Engine API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.12
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package storyteller

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ExplorationNodeResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExplorationNodeResponse{}

// ExplorationNodeResponse Single exploration Q&A discovery node returned by exploration-node list/get routes.  Used by both player routes (where ``picked`` reflects the session/playthrough pick state) and authoring routes (where ``picked`` is always ``False`` because there is no session context in the authoring layer).
type ExplorationNodeResponse struct {
	Id string `json:"id"`
	ParentNodeId string `json:"parent_node_id"`
	Question string `json:"question"`
	Answer string `json:"answer"`
	FormalizedText string `json:"formalized_text"`
	Essential bool `json:"essential"`
	Picked bool `json:"picked"`
	DetailDelta map[string]interface{} `json:"detail_delta,omitempty"`
}

type _ExplorationNodeResponse ExplorationNodeResponse

// NewExplorationNodeResponse instantiates a new ExplorationNodeResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExplorationNodeResponse(id string, parentNodeId string, question string, answer string, formalizedText string, essential bool, picked bool) *ExplorationNodeResponse {
	this := ExplorationNodeResponse{}
	this.Id = id
	this.ParentNodeId = parentNodeId
	this.Question = question
	this.Answer = answer
	this.FormalizedText = formalizedText
	this.Essential = essential
	this.Picked = picked
	return &this
}

// NewExplorationNodeResponseWithDefaults instantiates a new ExplorationNodeResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExplorationNodeResponseWithDefaults() *ExplorationNodeResponse {
	this := ExplorationNodeResponse{}
	return &this
}

// GetId returns the Id field value
func (o *ExplorationNodeResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ExplorationNodeResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ExplorationNodeResponse) SetId(v string) {
	o.Id = v
}

// GetParentNodeId returns the ParentNodeId field value
func (o *ExplorationNodeResponse) GetParentNodeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ParentNodeId
}

// GetParentNodeIdOk returns a tuple with the ParentNodeId field value
// and a boolean to check if the value has been set.
func (o *ExplorationNodeResponse) GetParentNodeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ParentNodeId, true
}

// SetParentNodeId sets field value
func (o *ExplorationNodeResponse) SetParentNodeId(v string) {
	o.ParentNodeId = v
}

// GetQuestion returns the Question field value
func (o *ExplorationNodeResponse) GetQuestion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Question
}

// GetQuestionOk returns a tuple with the Question field value
// and a boolean to check if the value has been set.
func (o *ExplorationNodeResponse) GetQuestionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Question, true
}

// SetQuestion sets field value
func (o *ExplorationNodeResponse) SetQuestion(v string) {
	o.Question = v
}

// GetAnswer returns the Answer field value
func (o *ExplorationNodeResponse) GetAnswer() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Answer
}

// GetAnswerOk returns a tuple with the Answer field value
// and a boolean to check if the value has been set.
func (o *ExplorationNodeResponse) GetAnswerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Answer, true
}

// SetAnswer sets field value
func (o *ExplorationNodeResponse) SetAnswer(v string) {
	o.Answer = v
}

// GetFormalizedText returns the FormalizedText field value
func (o *ExplorationNodeResponse) GetFormalizedText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FormalizedText
}

// GetFormalizedTextOk returns a tuple with the FormalizedText field value
// and a boolean to check if the value has been set.
func (o *ExplorationNodeResponse) GetFormalizedTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FormalizedText, true
}

// SetFormalizedText sets field value
func (o *ExplorationNodeResponse) SetFormalizedText(v string) {
	o.FormalizedText = v
}

// GetEssential returns the Essential field value
func (o *ExplorationNodeResponse) GetEssential() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Essential
}

// GetEssentialOk returns a tuple with the Essential field value
// and a boolean to check if the value has been set.
func (o *ExplorationNodeResponse) GetEssentialOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Essential, true
}

// SetEssential sets field value
func (o *ExplorationNodeResponse) SetEssential(v bool) {
	o.Essential = v
}

// GetPicked returns the Picked field value
func (o *ExplorationNodeResponse) GetPicked() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Picked
}

// GetPickedOk returns a tuple with the Picked field value
// and a boolean to check if the value has been set.
func (o *ExplorationNodeResponse) GetPickedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Picked, true
}

// SetPicked sets field value
func (o *ExplorationNodeResponse) SetPicked(v bool) {
	o.Picked = v
}

// GetDetailDelta returns the DetailDelta field value if set, zero value otherwise.
func (o *ExplorationNodeResponse) GetDetailDelta() map[string]interface{} {
	if o == nil || IsNil(o.DetailDelta) {
		var ret map[string]interface{}
		return ret
	}
	return o.DetailDelta
}

// GetDetailDeltaOk returns a tuple with the DetailDelta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExplorationNodeResponse) GetDetailDeltaOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.DetailDelta) {
		return map[string]interface{}{}, false
	}
	return o.DetailDelta, true
}

// HasDetailDelta returns a boolean if a field has been set.
func (o *ExplorationNodeResponse) HasDetailDelta() bool {
	if o != nil && !IsNil(o.DetailDelta) {
		return true
	}

	return false
}

// SetDetailDelta gets a reference to the given map[string]interface{} and assigns it to the DetailDelta field.
func (o *ExplorationNodeResponse) SetDetailDelta(v map[string]interface{}) {
	o.DetailDelta = v
}

func (o ExplorationNodeResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExplorationNodeResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["parent_node_id"] = o.ParentNodeId
	toSerialize["question"] = o.Question
	toSerialize["answer"] = o.Answer
	toSerialize["formalized_text"] = o.FormalizedText
	toSerialize["essential"] = o.Essential
	toSerialize["picked"] = o.Picked
	if !IsNil(o.DetailDelta) {
		toSerialize["detail_delta"] = o.DetailDelta
	}
	return toSerialize, nil
}

func (o *ExplorationNodeResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"parent_node_id",
		"question",
		"answer",
		"formalized_text",
		"essential",
		"picked",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExplorationNodeResponse := _ExplorationNodeResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varExplorationNodeResponse)

	if err != nil {
		return err
	}

	*o = ExplorationNodeResponse(varExplorationNodeResponse)

	return err
}

type NullableExplorationNodeResponse struct {
	value *ExplorationNodeResponse
	isSet bool
}

func (v NullableExplorationNodeResponse) Get() *ExplorationNodeResponse {
	return v.value
}

func (v *NullableExplorationNodeResponse) Set(val *ExplorationNodeResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableExplorationNodeResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableExplorationNodeResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExplorationNodeResponse(val *ExplorationNodeResponse) *NullableExplorationNodeResponse {
	return &NullableExplorationNodeResponse{value: val, isSet: true}
}

func (v NullableExplorationNodeResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExplorationNodeResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


