/*
Story Engine API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.12
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package storyteller

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EntityIndexResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EntityIndexResponse{}

// EntityIndexResponse Per-playthrough entity provenance index for the current player session.
type EntityIndexResponse struct {
	SessionId string `json:"session_id"`
	PlaythroughId string `json:"playthrough_id"`
	Entries []EntityProvenanceEntryResponse `json:"entries"`
}

type _EntityIndexResponse EntityIndexResponse

// NewEntityIndexResponse instantiates a new EntityIndexResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEntityIndexResponse(sessionId string, playthroughId string, entries []EntityProvenanceEntryResponse) *EntityIndexResponse {
	this := EntityIndexResponse{}
	this.SessionId = sessionId
	this.PlaythroughId = playthroughId
	this.Entries = entries
	return &this
}

// NewEntityIndexResponseWithDefaults instantiates a new EntityIndexResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEntityIndexResponseWithDefaults() *EntityIndexResponse {
	this := EntityIndexResponse{}
	return &this
}

// GetSessionId returns the SessionId field value
func (o *EntityIndexResponse) GetSessionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SessionId
}

// GetSessionIdOk returns a tuple with the SessionId field value
// and a boolean to check if the value has been set.
func (o *EntityIndexResponse) GetSessionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SessionId, true
}

// SetSessionId sets field value
func (o *EntityIndexResponse) SetSessionId(v string) {
	o.SessionId = v
}

// GetPlaythroughId returns the PlaythroughId field value
func (o *EntityIndexResponse) GetPlaythroughId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PlaythroughId
}

// GetPlaythroughIdOk returns a tuple with the PlaythroughId field value
// and a boolean to check if the value has been set.
func (o *EntityIndexResponse) GetPlaythroughIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlaythroughId, true
}

// SetPlaythroughId sets field value
func (o *EntityIndexResponse) SetPlaythroughId(v string) {
	o.PlaythroughId = v
}

// GetEntries returns the Entries field value
func (o *EntityIndexResponse) GetEntries() []EntityProvenanceEntryResponse {
	if o == nil {
		var ret []EntityProvenanceEntryResponse
		return ret
	}

	return o.Entries
}

// GetEntriesOk returns a tuple with the Entries field value
// and a boolean to check if the value has been set.
func (o *EntityIndexResponse) GetEntriesOk() ([]EntityProvenanceEntryResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Entries, true
}

// SetEntries sets field value
func (o *EntityIndexResponse) SetEntries(v []EntityProvenanceEntryResponse) {
	o.Entries = v
}

func (o EntityIndexResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EntityIndexResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["session_id"] = o.SessionId
	toSerialize["playthrough_id"] = o.PlaythroughId
	toSerialize["entries"] = o.Entries
	return toSerialize, nil
}

func (o *EntityIndexResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"session_id",
		"playthrough_id",
		"entries",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEntityIndexResponse := _EntityIndexResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEntityIndexResponse)

	if err != nil {
		return err
	}

	*o = EntityIndexResponse(varEntityIndexResponse)

	return err
}

type NullableEntityIndexResponse struct {
	value *EntityIndexResponse
	isSet bool
}

func (v NullableEntityIndexResponse) Get() *EntityIndexResponse {
	return v.value
}

func (v *NullableEntityIndexResponse) Set(val *EntityIndexResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableEntityIndexResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableEntityIndexResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEntityIndexResponse(val *EntityIndexResponse) *NullableEntityIndexResponse {
	return &NullableEntityIndexResponse{value: val, isSet: true}
}

func (v NullableEntityIndexResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEntityIndexResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


