/*
Story Engine API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.13
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package storyteller

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V1HealthGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1HealthGet200Response{}

// V1HealthGet200Response struct for V1HealthGet200Response
type V1HealthGet200Response struct {
	Postgres string `json:"postgres"`
	Redis string `json:"redis"`
	Status string `json:"status"`
	Version string `json:"version"`
}

type _V1HealthGet200Response V1HealthGet200Response

// NewV1HealthGet200Response instantiates a new V1HealthGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1HealthGet200Response(postgres string, redis string, status string, version string) *V1HealthGet200Response {
	this := V1HealthGet200Response{}
	this.Postgres = postgres
	this.Redis = redis
	this.Status = status
	this.Version = version
	return &this
}

// NewV1HealthGet200ResponseWithDefaults instantiates a new V1HealthGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1HealthGet200ResponseWithDefaults() *V1HealthGet200Response {
	this := V1HealthGet200Response{}
	return &this
}

// GetPostgres returns the Postgres field value
func (o *V1HealthGet200Response) GetPostgres() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Postgres
}

// GetPostgresOk returns a tuple with the Postgres field value
// and a boolean to check if the value has been set.
func (o *V1HealthGet200Response) GetPostgresOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Postgres, true
}

// SetPostgres sets field value
func (o *V1HealthGet200Response) SetPostgres(v string) {
	o.Postgres = v
}

// GetRedis returns the Redis field value
func (o *V1HealthGet200Response) GetRedis() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Redis
}

// GetRedisOk returns a tuple with the Redis field value
// and a boolean to check if the value has been set.
func (o *V1HealthGet200Response) GetRedisOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Redis, true
}

// SetRedis sets field value
func (o *V1HealthGet200Response) SetRedis(v string) {
	o.Redis = v
}

// GetStatus returns the Status field value
func (o *V1HealthGet200Response) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *V1HealthGet200Response) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *V1HealthGet200Response) SetStatus(v string) {
	o.Status = v
}

// GetVersion returns the Version field value
func (o *V1HealthGet200Response) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *V1HealthGet200Response) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *V1HealthGet200Response) SetVersion(v string) {
	o.Version = v
}

func (o V1HealthGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1HealthGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["postgres"] = o.Postgres
	toSerialize["redis"] = o.Redis
	toSerialize["status"] = o.Status
	toSerialize["version"] = o.Version
	return toSerialize, nil
}

func (o *V1HealthGet200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"postgres",
		"redis",
		"status",
		"version",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1HealthGet200Response := _V1HealthGet200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV1HealthGet200Response)

	if err != nil {
		return err
	}

	*o = V1HealthGet200Response(varV1HealthGet200Response)

	return err
}

type NullableV1HealthGet200Response struct {
	value *V1HealthGet200Response
	isSet bool
}

func (v NullableV1HealthGet200Response) Get() *V1HealthGet200Response {
	return v.value
}

func (v *NullableV1HealthGet200Response) Set(val *V1HealthGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableV1HealthGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableV1HealthGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1HealthGet200Response(val *V1HealthGet200Response) *NullableV1HealthGet200Response {
	return &NullableV1HealthGet200Response{value: val, isSet: true}
}

func (v NullableV1HealthGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1HealthGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


