/*
Story Engine API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.12
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package storyteller

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PaginatedResponseExplorationNodeResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedResponseExplorationNodeResponse{}

// PaginatedResponseExplorationNodeResponse struct for PaginatedResponseExplorationNodeResponse
type PaginatedResponseExplorationNodeResponse struct {
	Items []ExplorationNodeResponse `json:"items"`
	NextCursor NullableString `json:"next_cursor"`
	HasMore bool `json:"has_more"`
}

type _PaginatedResponseExplorationNodeResponse PaginatedResponseExplorationNodeResponse

// NewPaginatedResponseExplorationNodeResponse instantiates a new PaginatedResponseExplorationNodeResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginatedResponseExplorationNodeResponse(items []ExplorationNodeResponse, nextCursor NullableString, hasMore bool) *PaginatedResponseExplorationNodeResponse {
	this := PaginatedResponseExplorationNodeResponse{}
	this.Items = items
	this.NextCursor = nextCursor
	this.HasMore = hasMore
	return &this
}

// NewPaginatedResponseExplorationNodeResponseWithDefaults instantiates a new PaginatedResponseExplorationNodeResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginatedResponseExplorationNodeResponseWithDefaults() *PaginatedResponseExplorationNodeResponse {
	this := PaginatedResponseExplorationNodeResponse{}
	return &this
}

// GetItems returns the Items field value
func (o *PaginatedResponseExplorationNodeResponse) GetItems() []ExplorationNodeResponse {
	if o == nil {
		var ret []ExplorationNodeResponse
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *PaginatedResponseExplorationNodeResponse) GetItemsOk() ([]ExplorationNodeResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *PaginatedResponseExplorationNodeResponse) SetItems(v []ExplorationNodeResponse) {
	o.Items = v
}

// GetNextCursor returns the NextCursor field value
// If the value is explicit nil, the zero value for string will be returned
func (o *PaginatedResponseExplorationNodeResponse) GetNextCursor() string {
	if o == nil || o.NextCursor.Get() == nil {
		var ret string
		return ret
	}

	return *o.NextCursor.Get()
}

// GetNextCursorOk returns a tuple with the NextCursor field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PaginatedResponseExplorationNodeResponse) GetNextCursorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NextCursor.Get(), o.NextCursor.IsSet()
}

// SetNextCursor sets field value
func (o *PaginatedResponseExplorationNodeResponse) SetNextCursor(v string) {
	o.NextCursor.Set(&v)
}

// GetHasMore returns the HasMore field value
func (o *PaginatedResponseExplorationNodeResponse) GetHasMore() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasMore
}

// GetHasMoreOk returns a tuple with the HasMore field value
// and a boolean to check if the value has been set.
func (o *PaginatedResponseExplorationNodeResponse) GetHasMoreOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasMore, true
}

// SetHasMore sets field value
func (o *PaginatedResponseExplorationNodeResponse) SetHasMore(v bool) {
	o.HasMore = v
}

func (o PaginatedResponseExplorationNodeResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginatedResponseExplorationNodeResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	toSerialize["next_cursor"] = o.NextCursor.Get()
	toSerialize["has_more"] = o.HasMore
	return toSerialize, nil
}

func (o *PaginatedResponseExplorationNodeResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
		"next_cursor",
		"has_more",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaginatedResponseExplorationNodeResponse := _PaginatedResponseExplorationNodeResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPaginatedResponseExplorationNodeResponse)

	if err != nil {
		return err
	}

	*o = PaginatedResponseExplorationNodeResponse(varPaginatedResponseExplorationNodeResponse)

	return err
}

type NullablePaginatedResponseExplorationNodeResponse struct {
	value *PaginatedResponseExplorationNodeResponse
	isSet bool
}

func (v NullablePaginatedResponseExplorationNodeResponse) Get() *PaginatedResponseExplorationNodeResponse {
	return v.value
}

func (v *NullablePaginatedResponseExplorationNodeResponse) Set(val *PaginatedResponseExplorationNodeResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginatedResponseExplorationNodeResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginatedResponseExplorationNodeResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginatedResponseExplorationNodeResponse(val *PaginatedResponseExplorationNodeResponse) *NullablePaginatedResponseExplorationNodeResponse {
	return &NullablePaginatedResponseExplorationNodeResponse{value: val, isSet: true}
}

func (v NullablePaginatedResponseExplorationNodeResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginatedResponseExplorationNodeResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


