/*
Story Engine API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.13
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package storyteller

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V1PlayerPlayerIdDelete200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1PlayerPlayerIdDelete200Response{}

// V1PlayerPlayerIdDelete200Response struct for V1PlayerPlayerIdDelete200Response
type V1PlayerPlayerIdDelete200Response struct {
	Deleted map[string]int32 `json:"deleted"`
	PlayerId string `json:"player_id"`
	TenantId string `json:"tenant_id"`
}

type _V1PlayerPlayerIdDelete200Response V1PlayerPlayerIdDelete200Response

// NewV1PlayerPlayerIdDelete200Response instantiates a new V1PlayerPlayerIdDelete200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1PlayerPlayerIdDelete200Response(deleted map[string]int32, playerId string, tenantId string) *V1PlayerPlayerIdDelete200Response {
	this := V1PlayerPlayerIdDelete200Response{}
	this.Deleted = deleted
	this.PlayerId = playerId
	this.TenantId = tenantId
	return &this
}

// NewV1PlayerPlayerIdDelete200ResponseWithDefaults instantiates a new V1PlayerPlayerIdDelete200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1PlayerPlayerIdDelete200ResponseWithDefaults() *V1PlayerPlayerIdDelete200Response {
	this := V1PlayerPlayerIdDelete200Response{}
	return &this
}

// GetDeleted returns the Deleted field value
func (o *V1PlayerPlayerIdDelete200Response) GetDeleted() map[string]int32 {
	if o == nil {
		var ret map[string]int32
		return ret
	}

	return o.Deleted
}

// GetDeletedOk returns a tuple with the Deleted field value
// and a boolean to check if the value has been set.
func (o *V1PlayerPlayerIdDelete200Response) GetDeletedOk() (map[string]int32, bool) {
	if o == nil {
		return map[string]int32{}, false
	}
	return o.Deleted, true
}

// SetDeleted sets field value
func (o *V1PlayerPlayerIdDelete200Response) SetDeleted(v map[string]int32) {
	o.Deleted = v
}

// GetPlayerId returns the PlayerId field value
func (o *V1PlayerPlayerIdDelete200Response) GetPlayerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PlayerId
}

// GetPlayerIdOk returns a tuple with the PlayerId field value
// and a boolean to check if the value has been set.
func (o *V1PlayerPlayerIdDelete200Response) GetPlayerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlayerId, true
}

// SetPlayerId sets field value
func (o *V1PlayerPlayerIdDelete200Response) SetPlayerId(v string) {
	o.PlayerId = v
}

// GetTenantId returns the TenantId field value
func (o *V1PlayerPlayerIdDelete200Response) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *V1PlayerPlayerIdDelete200Response) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *V1PlayerPlayerIdDelete200Response) SetTenantId(v string) {
	o.TenantId = v
}

func (o V1PlayerPlayerIdDelete200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1PlayerPlayerIdDelete200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["deleted"] = o.Deleted
	toSerialize["player_id"] = o.PlayerId
	toSerialize["tenant_id"] = o.TenantId
	return toSerialize, nil
}

func (o *V1PlayerPlayerIdDelete200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"deleted",
		"player_id",
		"tenant_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1PlayerPlayerIdDelete200Response := _V1PlayerPlayerIdDelete200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV1PlayerPlayerIdDelete200Response)

	if err != nil {
		return err
	}

	*o = V1PlayerPlayerIdDelete200Response(varV1PlayerPlayerIdDelete200Response)

	return err
}

type NullableV1PlayerPlayerIdDelete200Response struct {
	value *V1PlayerPlayerIdDelete200Response
	isSet bool
}

func (v NullableV1PlayerPlayerIdDelete200Response) Get() *V1PlayerPlayerIdDelete200Response {
	return v.value
}

func (v *NullableV1PlayerPlayerIdDelete200Response) Set(val *V1PlayerPlayerIdDelete200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableV1PlayerPlayerIdDelete200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableV1PlayerPlayerIdDelete200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1PlayerPlayerIdDelete200Response(val *V1PlayerPlayerIdDelete200Response) *NullableV1PlayerPlayerIdDelete200Response {
	return &NullableV1PlayerPlayerIdDelete200Response{value: val, isSet: true}
}

func (v NullableV1PlayerPlayerIdDelete200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1PlayerPlayerIdDelete200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


