/*
Story Engine API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.12
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package storyteller

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GraphEdge type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GraphEdge{}

// GraphEdge A directed edge in the story DAG topology view.  Represents a choice arc from ``from_node_id`` to ``to_node_id``. ``label`` is the human-readable choice text; it may be ``None`` for internally generated bridge nodes that have no visible label.
type GraphEdge struct {
	FromNodeId string `json:"from_node_id"`
	ChoiceId string `json:"choice_id"`
	ToNodeId string `json:"to_node_id"`
	Label NullableString `json:"label,omitempty"`
}

type _GraphEdge GraphEdge

// NewGraphEdge instantiates a new GraphEdge object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGraphEdge(fromNodeId string, choiceId string, toNodeId string) *GraphEdge {
	this := GraphEdge{}
	this.FromNodeId = fromNodeId
	this.ChoiceId = choiceId
	this.ToNodeId = toNodeId
	return &this
}

// NewGraphEdgeWithDefaults instantiates a new GraphEdge object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGraphEdgeWithDefaults() *GraphEdge {
	this := GraphEdge{}
	return &this
}

// GetFromNodeId returns the FromNodeId field value
func (o *GraphEdge) GetFromNodeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FromNodeId
}

// GetFromNodeIdOk returns a tuple with the FromNodeId field value
// and a boolean to check if the value has been set.
func (o *GraphEdge) GetFromNodeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FromNodeId, true
}

// SetFromNodeId sets field value
func (o *GraphEdge) SetFromNodeId(v string) {
	o.FromNodeId = v
}

// GetChoiceId returns the ChoiceId field value
func (o *GraphEdge) GetChoiceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChoiceId
}

// GetChoiceIdOk returns a tuple with the ChoiceId field value
// and a boolean to check if the value has been set.
func (o *GraphEdge) GetChoiceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChoiceId, true
}

// SetChoiceId sets field value
func (o *GraphEdge) SetChoiceId(v string) {
	o.ChoiceId = v
}

// GetToNodeId returns the ToNodeId field value
func (o *GraphEdge) GetToNodeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ToNodeId
}

// GetToNodeIdOk returns a tuple with the ToNodeId field value
// and a boolean to check if the value has been set.
func (o *GraphEdge) GetToNodeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ToNodeId, true
}

// SetToNodeId sets field value
func (o *GraphEdge) SetToNodeId(v string) {
	o.ToNodeId = v
}

// GetLabel returns the Label field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GraphEdge) GetLabel() string {
	if o == nil || IsNil(o.Label.Get()) {
		var ret string
		return ret
	}
	return *o.Label.Get()
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GraphEdge) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Label.Get(), o.Label.IsSet()
}

// HasLabel returns a boolean if a field has been set.
func (o *GraphEdge) HasLabel() bool {
	if o != nil && o.Label.IsSet() {
		return true
	}

	return false
}

// SetLabel gets a reference to the given NullableString and assigns it to the Label field.
func (o *GraphEdge) SetLabel(v string) {
	o.Label.Set(&v)
}
// SetLabelNil sets the value for Label to be an explicit nil
func (o *GraphEdge) SetLabelNil() {
	o.Label.Set(nil)
}

// UnsetLabel ensures that no value is present for Label, not even an explicit nil
func (o *GraphEdge) UnsetLabel() {
	o.Label.Unset()
}

func (o GraphEdge) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GraphEdge) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["from_node_id"] = o.FromNodeId
	toSerialize["choice_id"] = o.ChoiceId
	toSerialize["to_node_id"] = o.ToNodeId
	if o.Label.IsSet() {
		toSerialize["label"] = o.Label.Get()
	}
	return toSerialize, nil
}

func (o *GraphEdge) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"from_node_id",
		"choice_id",
		"to_node_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGraphEdge := _GraphEdge{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGraphEdge)

	if err != nil {
		return err
	}

	*o = GraphEdge(varGraphEdge)

	return err
}

type NullableGraphEdge struct {
	value *GraphEdge
	isSet bool
}

func (v NullableGraphEdge) Get() *GraphEdge {
	return v.value
}

func (v *NullableGraphEdge) Set(val *GraphEdge) {
	v.value = val
	v.isSet = true
}

func (v NullableGraphEdge) IsSet() bool {
	return v.isSet
}

func (v *NullableGraphEdge) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGraphEdge(val *GraphEdge) *NullableGraphEdge {
	return &NullableGraphEdge{value: val, isSet: true}
}

func (v NullableGraphEdge) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGraphEdge) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


