/*
Story Engine API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.13
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package storyteller

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V1StoryStoryIdChoicePost200ResponseChoicesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1StoryStoryIdChoicePost200ResponseChoicesInner{}

// V1StoryStoryIdChoicePost200ResponseChoicesInner struct for V1StoryStoryIdChoicePost200ResponseChoicesInner
type V1StoryStoryIdChoicePost200ResponseChoicesInner struct {
	FlagDelta map[string]map[string]interface{} `json:"flag_delta"`
	FlagSchemaDelta map[string]map[string]interface{} `json:"flag_schema_delta"`
	Id string `json:"id"`
	Label string `json:"label"`
	TargetNodeId *string `json:"target_node_id,omitempty"`
}

type _V1StoryStoryIdChoicePost200ResponseChoicesInner V1StoryStoryIdChoicePost200ResponseChoicesInner

// NewV1StoryStoryIdChoicePost200ResponseChoicesInner instantiates a new V1StoryStoryIdChoicePost200ResponseChoicesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1StoryStoryIdChoicePost200ResponseChoicesInner(flagDelta map[string]map[string]interface{}, flagSchemaDelta map[string]map[string]interface{}, id string, label string) *V1StoryStoryIdChoicePost200ResponseChoicesInner {
	this := V1StoryStoryIdChoicePost200ResponseChoicesInner{}
	this.FlagDelta = flagDelta
	this.FlagSchemaDelta = flagSchemaDelta
	this.Id = id
	this.Label = label
	return &this
}

// NewV1StoryStoryIdChoicePost200ResponseChoicesInnerWithDefaults instantiates a new V1StoryStoryIdChoicePost200ResponseChoicesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1StoryStoryIdChoicePost200ResponseChoicesInnerWithDefaults() *V1StoryStoryIdChoicePost200ResponseChoicesInner {
	this := V1StoryStoryIdChoicePost200ResponseChoicesInner{}
	return &this
}

// GetFlagDelta returns the FlagDelta field value
func (o *V1StoryStoryIdChoicePost200ResponseChoicesInner) GetFlagDelta() map[string]map[string]interface{} {
	if o == nil {
		var ret map[string]map[string]interface{}
		return ret
	}

	return o.FlagDelta
}

// GetFlagDeltaOk returns a tuple with the FlagDelta field value
// and a boolean to check if the value has been set.
func (o *V1StoryStoryIdChoicePost200ResponseChoicesInner) GetFlagDeltaOk() (map[string]map[string]interface{}, bool) {
	if o == nil {
		return map[string]map[string]interface{}{}, false
	}
	return o.FlagDelta, true
}

// SetFlagDelta sets field value
func (o *V1StoryStoryIdChoicePost200ResponseChoicesInner) SetFlagDelta(v map[string]map[string]interface{}) {
	o.FlagDelta = v
}

// GetFlagSchemaDelta returns the FlagSchemaDelta field value
func (o *V1StoryStoryIdChoicePost200ResponseChoicesInner) GetFlagSchemaDelta() map[string]map[string]interface{} {
	if o == nil {
		var ret map[string]map[string]interface{}
		return ret
	}

	return o.FlagSchemaDelta
}

// GetFlagSchemaDeltaOk returns a tuple with the FlagSchemaDelta field value
// and a boolean to check if the value has been set.
func (o *V1StoryStoryIdChoicePost200ResponseChoicesInner) GetFlagSchemaDeltaOk() (map[string]map[string]interface{}, bool) {
	if o == nil {
		return map[string]map[string]interface{}{}, false
	}
	return o.FlagSchemaDelta, true
}

// SetFlagSchemaDelta sets field value
func (o *V1StoryStoryIdChoicePost200ResponseChoicesInner) SetFlagSchemaDelta(v map[string]map[string]interface{}) {
	o.FlagSchemaDelta = v
}

// GetId returns the Id field value
func (o *V1StoryStoryIdChoicePost200ResponseChoicesInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *V1StoryStoryIdChoicePost200ResponseChoicesInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *V1StoryStoryIdChoicePost200ResponseChoicesInner) SetId(v string) {
	o.Id = v
}

// GetLabel returns the Label field value
func (o *V1StoryStoryIdChoicePost200ResponseChoicesInner) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *V1StoryStoryIdChoicePost200ResponseChoicesInner) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *V1StoryStoryIdChoicePost200ResponseChoicesInner) SetLabel(v string) {
	o.Label = v
}

// GetTargetNodeId returns the TargetNodeId field value if set, zero value otherwise.
func (o *V1StoryStoryIdChoicePost200ResponseChoicesInner) GetTargetNodeId() string {
	if o == nil || IsNil(o.TargetNodeId) {
		var ret string
		return ret
	}
	return *o.TargetNodeId
}

// GetTargetNodeIdOk returns a tuple with the TargetNodeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1StoryStoryIdChoicePost200ResponseChoicesInner) GetTargetNodeIdOk() (*string, bool) {
	if o == nil || IsNil(o.TargetNodeId) {
		return nil, false
	}
	return o.TargetNodeId, true
}

// HasTargetNodeId returns a boolean if a field has been set.
func (o *V1StoryStoryIdChoicePost200ResponseChoicesInner) HasTargetNodeId() bool {
	if o != nil && !IsNil(o.TargetNodeId) {
		return true
	}

	return false
}

// SetTargetNodeId gets a reference to the given string and assigns it to the TargetNodeId field.
func (o *V1StoryStoryIdChoicePost200ResponseChoicesInner) SetTargetNodeId(v string) {
	o.TargetNodeId = &v
}

func (o V1StoryStoryIdChoicePost200ResponseChoicesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1StoryStoryIdChoicePost200ResponseChoicesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["flag_delta"] = o.FlagDelta
	toSerialize["flag_schema_delta"] = o.FlagSchemaDelta
	toSerialize["id"] = o.Id
	toSerialize["label"] = o.Label
	if !IsNil(o.TargetNodeId) {
		toSerialize["target_node_id"] = o.TargetNodeId
	}
	return toSerialize, nil
}

func (o *V1StoryStoryIdChoicePost200ResponseChoicesInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"flag_delta",
		"flag_schema_delta",
		"id",
		"label",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1StoryStoryIdChoicePost200ResponseChoicesInner := _V1StoryStoryIdChoicePost200ResponseChoicesInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV1StoryStoryIdChoicePost200ResponseChoicesInner)

	if err != nil {
		return err
	}

	*o = V1StoryStoryIdChoicePost200ResponseChoicesInner(varV1StoryStoryIdChoicePost200ResponseChoicesInner)

	return err
}

type NullableV1StoryStoryIdChoicePost200ResponseChoicesInner struct {
	value *V1StoryStoryIdChoicePost200ResponseChoicesInner
	isSet bool
}

func (v NullableV1StoryStoryIdChoicePost200ResponseChoicesInner) Get() *V1StoryStoryIdChoicePost200ResponseChoicesInner {
	return v.value
}

func (v *NullableV1StoryStoryIdChoicePost200ResponseChoicesInner) Set(val *V1StoryStoryIdChoicePost200ResponseChoicesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableV1StoryStoryIdChoicePost200ResponseChoicesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableV1StoryStoryIdChoicePost200ResponseChoicesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1StoryStoryIdChoicePost200ResponseChoicesInner(val *V1StoryStoryIdChoicePost200ResponseChoicesInner) *NullableV1StoryStoryIdChoicePost200ResponseChoicesInner {
	return &NullableV1StoryStoryIdChoicePost200ResponseChoicesInner{value: val, isSet: true}
}

func (v NullableV1StoryStoryIdChoicePost200ResponseChoicesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1StoryStoryIdChoicePost200ResponseChoicesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


