/*
Story Engine API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.13
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package storyteller

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V1StoryStoryIdExplorePostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1StoryStoryIdExplorePostRequest{}

// V1StoryStoryIdExplorePostRequest struct for V1StoryStoryIdExplorePostRequest
type V1StoryStoryIdExplorePostRequest struct {
	IdempotencyKey *string `json:"idempotency_key,omitempty"`
	NodeId string `json:"node_id"`
	Question string `json:"question"`
}

type _V1StoryStoryIdExplorePostRequest V1StoryStoryIdExplorePostRequest

// NewV1StoryStoryIdExplorePostRequest instantiates a new V1StoryStoryIdExplorePostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1StoryStoryIdExplorePostRequest(nodeId string, question string) *V1StoryStoryIdExplorePostRequest {
	this := V1StoryStoryIdExplorePostRequest{}
	this.NodeId = nodeId
	this.Question = question
	return &this
}

// NewV1StoryStoryIdExplorePostRequestWithDefaults instantiates a new V1StoryStoryIdExplorePostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1StoryStoryIdExplorePostRequestWithDefaults() *V1StoryStoryIdExplorePostRequest {
	this := V1StoryStoryIdExplorePostRequest{}
	return &this
}

// GetIdempotencyKey returns the IdempotencyKey field value if set, zero value otherwise.
func (o *V1StoryStoryIdExplorePostRequest) GetIdempotencyKey() string {
	if o == nil || IsNil(o.IdempotencyKey) {
		var ret string
		return ret
	}
	return *o.IdempotencyKey
}

// GetIdempotencyKeyOk returns a tuple with the IdempotencyKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1StoryStoryIdExplorePostRequest) GetIdempotencyKeyOk() (*string, bool) {
	if o == nil || IsNil(o.IdempotencyKey) {
		return nil, false
	}
	return o.IdempotencyKey, true
}

// HasIdempotencyKey returns a boolean if a field has been set.
func (o *V1StoryStoryIdExplorePostRequest) HasIdempotencyKey() bool {
	if o != nil && !IsNil(o.IdempotencyKey) {
		return true
	}

	return false
}

// SetIdempotencyKey gets a reference to the given string and assigns it to the IdempotencyKey field.
func (o *V1StoryStoryIdExplorePostRequest) SetIdempotencyKey(v string) {
	o.IdempotencyKey = &v
}

// GetNodeId returns the NodeId field value
func (o *V1StoryStoryIdExplorePostRequest) GetNodeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NodeId
}

// GetNodeIdOk returns a tuple with the NodeId field value
// and a boolean to check if the value has been set.
func (o *V1StoryStoryIdExplorePostRequest) GetNodeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NodeId, true
}

// SetNodeId sets field value
func (o *V1StoryStoryIdExplorePostRequest) SetNodeId(v string) {
	o.NodeId = v
}

// GetQuestion returns the Question field value
func (o *V1StoryStoryIdExplorePostRequest) GetQuestion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Question
}

// GetQuestionOk returns a tuple with the Question field value
// and a boolean to check if the value has been set.
func (o *V1StoryStoryIdExplorePostRequest) GetQuestionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Question, true
}

// SetQuestion sets field value
func (o *V1StoryStoryIdExplorePostRequest) SetQuestion(v string) {
	o.Question = v
}

func (o V1StoryStoryIdExplorePostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1StoryStoryIdExplorePostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IdempotencyKey) {
		toSerialize["idempotency_key"] = o.IdempotencyKey
	}
	toSerialize["node_id"] = o.NodeId
	toSerialize["question"] = o.Question
	return toSerialize, nil
}

func (o *V1StoryStoryIdExplorePostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"node_id",
		"question",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1StoryStoryIdExplorePostRequest := _V1StoryStoryIdExplorePostRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV1StoryStoryIdExplorePostRequest)

	if err != nil {
		return err
	}

	*o = V1StoryStoryIdExplorePostRequest(varV1StoryStoryIdExplorePostRequest)

	return err
}

type NullableV1StoryStoryIdExplorePostRequest struct {
	value *V1StoryStoryIdExplorePostRequest
	isSet bool
}

func (v NullableV1StoryStoryIdExplorePostRequest) Get() *V1StoryStoryIdExplorePostRequest {
	return v.value
}

func (v *NullableV1StoryStoryIdExplorePostRequest) Set(val *V1StoryStoryIdExplorePostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV1StoryStoryIdExplorePostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV1StoryStoryIdExplorePostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1StoryStoryIdExplorePostRequest(val *V1StoryStoryIdExplorePostRequest) *NullableV1StoryStoryIdExplorePostRequest {
	return &NullableV1StoryStoryIdExplorePostRequest{value: val, isSet: true}
}

func (v NullableV1StoryStoryIdExplorePostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1StoryStoryIdExplorePostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


