/*
Story Engine API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.13
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package storyteller

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V1StoryStoryIdChoicePostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1StoryStoryIdChoicePostRequest{}

// V1StoryStoryIdChoicePostRequest struct for V1StoryStoryIdChoicePostRequest
type V1StoryStoryIdChoicePostRequest struct {
	ChoiceId string `json:"choice_id"`
	IdempotencyKey *string `json:"idempotency_key,omitempty"`
	LockToken *string `json:"lock_token,omitempty"`
	NodeId string `json:"node_id"`
}

type _V1StoryStoryIdChoicePostRequest V1StoryStoryIdChoicePostRequest

// NewV1StoryStoryIdChoicePostRequest instantiates a new V1StoryStoryIdChoicePostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1StoryStoryIdChoicePostRequest(choiceId string, nodeId string) *V1StoryStoryIdChoicePostRequest {
	this := V1StoryStoryIdChoicePostRequest{}
	this.ChoiceId = choiceId
	this.NodeId = nodeId
	return &this
}

// NewV1StoryStoryIdChoicePostRequestWithDefaults instantiates a new V1StoryStoryIdChoicePostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1StoryStoryIdChoicePostRequestWithDefaults() *V1StoryStoryIdChoicePostRequest {
	this := V1StoryStoryIdChoicePostRequest{}
	return &this
}

// GetChoiceId returns the ChoiceId field value
func (o *V1StoryStoryIdChoicePostRequest) GetChoiceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChoiceId
}

// GetChoiceIdOk returns a tuple with the ChoiceId field value
// and a boolean to check if the value has been set.
func (o *V1StoryStoryIdChoicePostRequest) GetChoiceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChoiceId, true
}

// SetChoiceId sets field value
func (o *V1StoryStoryIdChoicePostRequest) SetChoiceId(v string) {
	o.ChoiceId = v
}

// GetIdempotencyKey returns the IdempotencyKey field value if set, zero value otherwise.
func (o *V1StoryStoryIdChoicePostRequest) GetIdempotencyKey() string {
	if o == nil || IsNil(o.IdempotencyKey) {
		var ret string
		return ret
	}
	return *o.IdempotencyKey
}

// GetIdempotencyKeyOk returns a tuple with the IdempotencyKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1StoryStoryIdChoicePostRequest) GetIdempotencyKeyOk() (*string, bool) {
	if o == nil || IsNil(o.IdempotencyKey) {
		return nil, false
	}
	return o.IdempotencyKey, true
}

// HasIdempotencyKey returns a boolean if a field has been set.
func (o *V1StoryStoryIdChoicePostRequest) HasIdempotencyKey() bool {
	if o != nil && !IsNil(o.IdempotencyKey) {
		return true
	}

	return false
}

// SetIdempotencyKey gets a reference to the given string and assigns it to the IdempotencyKey field.
func (o *V1StoryStoryIdChoicePostRequest) SetIdempotencyKey(v string) {
	o.IdempotencyKey = &v
}

// GetLockToken returns the LockToken field value if set, zero value otherwise.
func (o *V1StoryStoryIdChoicePostRequest) GetLockToken() string {
	if o == nil || IsNil(o.LockToken) {
		var ret string
		return ret
	}
	return *o.LockToken
}

// GetLockTokenOk returns a tuple with the LockToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1StoryStoryIdChoicePostRequest) GetLockTokenOk() (*string, bool) {
	if o == nil || IsNil(o.LockToken) {
		return nil, false
	}
	return o.LockToken, true
}

// HasLockToken returns a boolean if a field has been set.
func (o *V1StoryStoryIdChoicePostRequest) HasLockToken() bool {
	if o != nil && !IsNil(o.LockToken) {
		return true
	}

	return false
}

// SetLockToken gets a reference to the given string and assigns it to the LockToken field.
func (o *V1StoryStoryIdChoicePostRequest) SetLockToken(v string) {
	o.LockToken = &v
}

// GetNodeId returns the NodeId field value
func (o *V1StoryStoryIdChoicePostRequest) GetNodeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NodeId
}

// GetNodeIdOk returns a tuple with the NodeId field value
// and a boolean to check if the value has been set.
func (o *V1StoryStoryIdChoicePostRequest) GetNodeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NodeId, true
}

// SetNodeId sets field value
func (o *V1StoryStoryIdChoicePostRequest) SetNodeId(v string) {
	o.NodeId = v
}

func (o V1StoryStoryIdChoicePostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1StoryStoryIdChoicePostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["choice_id"] = o.ChoiceId
	if !IsNil(o.IdempotencyKey) {
		toSerialize["idempotency_key"] = o.IdempotencyKey
	}
	if !IsNil(o.LockToken) {
		toSerialize["lock_token"] = o.LockToken
	}
	toSerialize["node_id"] = o.NodeId
	return toSerialize, nil
}

func (o *V1StoryStoryIdChoicePostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"choice_id",
		"node_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1StoryStoryIdChoicePostRequest := _V1StoryStoryIdChoicePostRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV1StoryStoryIdChoicePostRequest)

	if err != nil {
		return err
	}

	*o = V1StoryStoryIdChoicePostRequest(varV1StoryStoryIdChoicePostRequest)

	return err
}

type NullableV1StoryStoryIdChoicePostRequest struct {
	value *V1StoryStoryIdChoicePostRequest
	isSet bool
}

func (v NullableV1StoryStoryIdChoicePostRequest) Get() *V1StoryStoryIdChoicePostRequest {
	return v.value
}

func (v *NullableV1StoryStoryIdChoicePostRequest) Set(val *V1StoryStoryIdChoicePostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV1StoryStoryIdChoicePostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV1StoryStoryIdChoicePostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1StoryStoryIdChoicePostRequest(val *V1StoryStoryIdChoicePostRequest) *NullableV1StoryStoryIdChoicePostRequest {
	return &NullableV1StoryStoryIdChoicePostRequest{value: val, isSet: true}
}

func (v NullableV1StoryStoryIdChoicePostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1StoryStoryIdChoicePostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


