/*
Story Engine API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.13
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package storyteller

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V1AdminStoryStoryIdGet200ResponseObjectsValue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1AdminStoryStoryIdGet200ResponseObjectsValue{}

// V1AdminStoryStoryIdGet200ResponseObjectsValue struct for V1AdminStoryStoryIdGet200ResponseObjectsValue
type V1AdminStoryStoryIdGet200ResponseObjectsValue struct {
	Description string `json:"description"`
	HolderId string `json:"holder_id"`
	LocationId string `json:"location_id"`
	Name string `json:"name"`
	ObjectType string `json:"object_type"`
}

type _V1AdminStoryStoryIdGet200ResponseObjectsValue V1AdminStoryStoryIdGet200ResponseObjectsValue

// NewV1AdminStoryStoryIdGet200ResponseObjectsValue instantiates a new V1AdminStoryStoryIdGet200ResponseObjectsValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1AdminStoryStoryIdGet200ResponseObjectsValue(description string, holderId string, locationId string, name string, objectType string) *V1AdminStoryStoryIdGet200ResponseObjectsValue {
	this := V1AdminStoryStoryIdGet200ResponseObjectsValue{}
	this.Description = description
	this.HolderId = holderId
	this.LocationId = locationId
	this.Name = name
	this.ObjectType = objectType
	return &this
}

// NewV1AdminStoryStoryIdGet200ResponseObjectsValueWithDefaults instantiates a new V1AdminStoryStoryIdGet200ResponseObjectsValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1AdminStoryStoryIdGet200ResponseObjectsValueWithDefaults() *V1AdminStoryStoryIdGet200ResponseObjectsValue {
	this := V1AdminStoryStoryIdGet200ResponseObjectsValue{}
	return &this
}

// GetDescription returns the Description field value
func (o *V1AdminStoryStoryIdGet200ResponseObjectsValue) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *V1AdminStoryStoryIdGet200ResponseObjectsValue) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *V1AdminStoryStoryIdGet200ResponseObjectsValue) SetDescription(v string) {
	o.Description = v
}

// GetHolderId returns the HolderId field value
func (o *V1AdminStoryStoryIdGet200ResponseObjectsValue) GetHolderId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.HolderId
}

// GetHolderIdOk returns a tuple with the HolderId field value
// and a boolean to check if the value has been set.
func (o *V1AdminStoryStoryIdGet200ResponseObjectsValue) GetHolderIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HolderId, true
}

// SetHolderId sets field value
func (o *V1AdminStoryStoryIdGet200ResponseObjectsValue) SetHolderId(v string) {
	o.HolderId = v
}

// GetLocationId returns the LocationId field value
func (o *V1AdminStoryStoryIdGet200ResponseObjectsValue) GetLocationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LocationId
}

// GetLocationIdOk returns a tuple with the LocationId field value
// and a boolean to check if the value has been set.
func (o *V1AdminStoryStoryIdGet200ResponseObjectsValue) GetLocationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LocationId, true
}

// SetLocationId sets field value
func (o *V1AdminStoryStoryIdGet200ResponseObjectsValue) SetLocationId(v string) {
	o.LocationId = v
}

// GetName returns the Name field value
func (o *V1AdminStoryStoryIdGet200ResponseObjectsValue) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *V1AdminStoryStoryIdGet200ResponseObjectsValue) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *V1AdminStoryStoryIdGet200ResponseObjectsValue) SetName(v string) {
	o.Name = v
}

// GetObjectType returns the ObjectType field value
func (o *V1AdminStoryStoryIdGet200ResponseObjectsValue) GetObjectType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ObjectType
}

// GetObjectTypeOk returns a tuple with the ObjectType field value
// and a boolean to check if the value has been set.
func (o *V1AdminStoryStoryIdGet200ResponseObjectsValue) GetObjectTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObjectType, true
}

// SetObjectType sets field value
func (o *V1AdminStoryStoryIdGet200ResponseObjectsValue) SetObjectType(v string) {
	o.ObjectType = v
}

func (o V1AdminStoryStoryIdGet200ResponseObjectsValue) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1AdminStoryStoryIdGet200ResponseObjectsValue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["description"] = o.Description
	toSerialize["holder_id"] = o.HolderId
	toSerialize["location_id"] = o.LocationId
	toSerialize["name"] = o.Name
	toSerialize["object_type"] = o.ObjectType
	return toSerialize, nil
}

func (o *V1AdminStoryStoryIdGet200ResponseObjectsValue) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"description",
		"holder_id",
		"location_id",
		"name",
		"object_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1AdminStoryStoryIdGet200ResponseObjectsValue := _V1AdminStoryStoryIdGet200ResponseObjectsValue{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV1AdminStoryStoryIdGet200ResponseObjectsValue)

	if err != nil {
		return err
	}

	*o = V1AdminStoryStoryIdGet200ResponseObjectsValue(varV1AdminStoryStoryIdGet200ResponseObjectsValue)

	return err
}

type NullableV1AdminStoryStoryIdGet200ResponseObjectsValue struct {
	value *V1AdminStoryStoryIdGet200ResponseObjectsValue
	isSet bool
}

func (v NullableV1AdminStoryStoryIdGet200ResponseObjectsValue) Get() *V1AdminStoryStoryIdGet200ResponseObjectsValue {
	return v.value
}

func (v *NullableV1AdminStoryStoryIdGet200ResponseObjectsValue) Set(val *V1AdminStoryStoryIdGet200ResponseObjectsValue) {
	v.value = val
	v.isSet = true
}

func (v NullableV1AdminStoryStoryIdGet200ResponseObjectsValue) IsSet() bool {
	return v.isSet
}

func (v *NullableV1AdminStoryStoryIdGet200ResponseObjectsValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1AdminStoryStoryIdGet200ResponseObjectsValue(val *V1AdminStoryStoryIdGet200ResponseObjectsValue) *NullableV1AdminStoryStoryIdGet200ResponseObjectsValue {
	return &NullableV1AdminStoryStoryIdGet200ResponseObjectsValue{value: val, isSet: true}
}

func (v NullableV1AdminStoryStoryIdGet200ResponseObjectsValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1AdminStoryStoryIdGet200ResponseObjectsValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


