/*
Story Engine API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.12
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package storyteller

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ExplorationStateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExplorationStateResponse{}

// ExplorationStateResponse Default player-facing read model for current-node exploration state.  Raw ``question`` and ``answer`` turn text are intentionally absent here. Clients get the shared node enrichment summary/details plus HMACed recent-turn metadata; raw transcript readback belongs behind the later privacy/export gates rather than this reload-friendly endpoint.
type ExplorationStateResponse struct {
	NodeId string `json:"node_id"`
	CurrentNodeId string `json:"current_node_id"`
	PlaythroughId string `json:"playthrough_id"`
	EnrichmentDetails map[string]interface{} `json:"enrichment_details,omitempty"`
	QuestionCount *int32 `json:"question_count,omitempty"`
	RecentTurns []ExplorationRecentTurnResponse `json:"recent_turns,omitempty"`
}

type _ExplorationStateResponse ExplorationStateResponse

// NewExplorationStateResponse instantiates a new ExplorationStateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExplorationStateResponse(nodeId string, currentNodeId string, playthroughId string) *ExplorationStateResponse {
	this := ExplorationStateResponse{}
	this.NodeId = nodeId
	this.CurrentNodeId = currentNodeId
	this.PlaythroughId = playthroughId
	var questionCount int32 = 0
	this.QuestionCount = &questionCount
	return &this
}

// NewExplorationStateResponseWithDefaults instantiates a new ExplorationStateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExplorationStateResponseWithDefaults() *ExplorationStateResponse {
	this := ExplorationStateResponse{}
	var questionCount int32 = 0
	this.QuestionCount = &questionCount
	return &this
}

// GetNodeId returns the NodeId field value
func (o *ExplorationStateResponse) GetNodeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NodeId
}

// GetNodeIdOk returns a tuple with the NodeId field value
// and a boolean to check if the value has been set.
func (o *ExplorationStateResponse) GetNodeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NodeId, true
}

// SetNodeId sets field value
func (o *ExplorationStateResponse) SetNodeId(v string) {
	o.NodeId = v
}

// GetCurrentNodeId returns the CurrentNodeId field value
func (o *ExplorationStateResponse) GetCurrentNodeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CurrentNodeId
}

// GetCurrentNodeIdOk returns a tuple with the CurrentNodeId field value
// and a boolean to check if the value has been set.
func (o *ExplorationStateResponse) GetCurrentNodeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CurrentNodeId, true
}

// SetCurrentNodeId sets field value
func (o *ExplorationStateResponse) SetCurrentNodeId(v string) {
	o.CurrentNodeId = v
}

// GetPlaythroughId returns the PlaythroughId field value
func (o *ExplorationStateResponse) GetPlaythroughId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PlaythroughId
}

// GetPlaythroughIdOk returns a tuple with the PlaythroughId field value
// and a boolean to check if the value has been set.
func (o *ExplorationStateResponse) GetPlaythroughIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlaythroughId, true
}

// SetPlaythroughId sets field value
func (o *ExplorationStateResponse) SetPlaythroughId(v string) {
	o.PlaythroughId = v
}

// GetEnrichmentDetails returns the EnrichmentDetails field value if set, zero value otherwise.
func (o *ExplorationStateResponse) GetEnrichmentDetails() map[string]interface{} {
	if o == nil || IsNil(o.EnrichmentDetails) {
		var ret map[string]interface{}
		return ret
	}
	return o.EnrichmentDetails
}

// GetEnrichmentDetailsOk returns a tuple with the EnrichmentDetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExplorationStateResponse) GetEnrichmentDetailsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.EnrichmentDetails) {
		return map[string]interface{}{}, false
	}
	return o.EnrichmentDetails, true
}

// HasEnrichmentDetails returns a boolean if a field has been set.
func (o *ExplorationStateResponse) HasEnrichmentDetails() bool {
	if o != nil && !IsNil(o.EnrichmentDetails) {
		return true
	}

	return false
}

// SetEnrichmentDetails gets a reference to the given map[string]interface{} and assigns it to the EnrichmentDetails field.
func (o *ExplorationStateResponse) SetEnrichmentDetails(v map[string]interface{}) {
	o.EnrichmentDetails = v
}

// GetQuestionCount returns the QuestionCount field value if set, zero value otherwise.
func (o *ExplorationStateResponse) GetQuestionCount() int32 {
	if o == nil || IsNil(o.QuestionCount) {
		var ret int32
		return ret
	}
	return *o.QuestionCount
}

// GetQuestionCountOk returns a tuple with the QuestionCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExplorationStateResponse) GetQuestionCountOk() (*int32, bool) {
	if o == nil || IsNil(o.QuestionCount) {
		return nil, false
	}
	return o.QuestionCount, true
}

// HasQuestionCount returns a boolean if a field has been set.
func (o *ExplorationStateResponse) HasQuestionCount() bool {
	if o != nil && !IsNil(o.QuestionCount) {
		return true
	}

	return false
}

// SetQuestionCount gets a reference to the given int32 and assigns it to the QuestionCount field.
func (o *ExplorationStateResponse) SetQuestionCount(v int32) {
	o.QuestionCount = &v
}

// GetRecentTurns returns the RecentTurns field value if set, zero value otherwise.
func (o *ExplorationStateResponse) GetRecentTurns() []ExplorationRecentTurnResponse {
	if o == nil || IsNil(o.RecentTurns) {
		var ret []ExplorationRecentTurnResponse
		return ret
	}
	return o.RecentTurns
}

// GetRecentTurnsOk returns a tuple with the RecentTurns field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExplorationStateResponse) GetRecentTurnsOk() ([]ExplorationRecentTurnResponse, bool) {
	if o == nil || IsNil(o.RecentTurns) {
		return nil, false
	}
	return o.RecentTurns, true
}

// HasRecentTurns returns a boolean if a field has been set.
func (o *ExplorationStateResponse) HasRecentTurns() bool {
	if o != nil && !IsNil(o.RecentTurns) {
		return true
	}

	return false
}

// SetRecentTurns gets a reference to the given []ExplorationRecentTurnResponse and assigns it to the RecentTurns field.
func (o *ExplorationStateResponse) SetRecentTurns(v []ExplorationRecentTurnResponse) {
	o.RecentTurns = v
}

func (o ExplorationStateResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExplorationStateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["node_id"] = o.NodeId
	toSerialize["current_node_id"] = o.CurrentNodeId
	toSerialize["playthrough_id"] = o.PlaythroughId
	if !IsNil(o.EnrichmentDetails) {
		toSerialize["enrichment_details"] = o.EnrichmentDetails
	}
	if !IsNil(o.QuestionCount) {
		toSerialize["question_count"] = o.QuestionCount
	}
	if !IsNil(o.RecentTurns) {
		toSerialize["recent_turns"] = o.RecentTurns
	}
	return toSerialize, nil
}

func (o *ExplorationStateResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"node_id",
		"current_node_id",
		"playthrough_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExplorationStateResponse := _ExplorationStateResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varExplorationStateResponse)

	if err != nil {
		return err
	}

	*o = ExplorationStateResponse(varExplorationStateResponse)

	return err
}

type NullableExplorationStateResponse struct {
	value *ExplorationStateResponse
	isSet bool
}

func (v NullableExplorationStateResponse) Get() *ExplorationStateResponse {
	return v.value
}

func (v *NullableExplorationStateResponse) Set(val *ExplorationStateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableExplorationStateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableExplorationStateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExplorationStateResponse(val *ExplorationStateResponse) *NullableExplorationStateResponse {
	return &NullableExplorationStateResponse{value: val, isSet: true}
}

func (v NullableExplorationStateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExplorationStateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


