/*
Story Engine API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.12
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package storyteller

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the StoryGenerateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StoryGenerateResponse{}

// StoryGenerateResponse Response for POST /v1/authoring/stories.  HTTP 201 is returned on ``mode=\"sync\"`` success; HTTP 202 for ``mode=\"async\"`` (job enqueued).  On the sync path ``story_id`` is populated immediately and ``status=\"complete\"``.  On the async path ``story_id`` is ``None`` and ``status=\"queued\"``.
type StoryGenerateResponse struct {
	JobId string `json:"job_id"`
	Mode string `json:"mode"`
	StoryId NullableString `json:"story_id"`
	Status string `json:"status"`
}

type _StoryGenerateResponse StoryGenerateResponse

// NewStoryGenerateResponse instantiates a new StoryGenerateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStoryGenerateResponse(jobId string, mode string, storyId NullableString, status string) *StoryGenerateResponse {
	this := StoryGenerateResponse{}
	this.JobId = jobId
	this.Mode = mode
	this.StoryId = storyId
	this.Status = status
	return &this
}

// NewStoryGenerateResponseWithDefaults instantiates a new StoryGenerateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStoryGenerateResponseWithDefaults() *StoryGenerateResponse {
	this := StoryGenerateResponse{}
	return &this
}

// GetJobId returns the JobId field value
func (o *StoryGenerateResponse) GetJobId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.JobId
}

// GetJobIdOk returns a tuple with the JobId field value
// and a boolean to check if the value has been set.
func (o *StoryGenerateResponse) GetJobIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JobId, true
}

// SetJobId sets field value
func (o *StoryGenerateResponse) SetJobId(v string) {
	o.JobId = v
}

// GetMode returns the Mode field value
func (o *StoryGenerateResponse) GetMode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Mode
}

// GetModeOk returns a tuple with the Mode field value
// and a boolean to check if the value has been set.
func (o *StoryGenerateResponse) GetModeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mode, true
}

// SetMode sets field value
func (o *StoryGenerateResponse) SetMode(v string) {
	o.Mode = v
}

// GetStoryId returns the StoryId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *StoryGenerateResponse) GetStoryId() string {
	if o == nil || o.StoryId.Get() == nil {
		var ret string
		return ret
	}

	return *o.StoryId.Get()
}

// GetStoryIdOk returns a tuple with the StoryId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StoryGenerateResponse) GetStoryIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.StoryId.Get(), o.StoryId.IsSet()
}

// SetStoryId sets field value
func (o *StoryGenerateResponse) SetStoryId(v string) {
	o.StoryId.Set(&v)
}

// GetStatus returns the Status field value
func (o *StoryGenerateResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *StoryGenerateResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *StoryGenerateResponse) SetStatus(v string) {
	o.Status = v
}

func (o StoryGenerateResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StoryGenerateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["job_id"] = o.JobId
	toSerialize["mode"] = o.Mode
	toSerialize["story_id"] = o.StoryId.Get()
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *StoryGenerateResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"job_id",
		"mode",
		"story_id",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStoryGenerateResponse := _StoryGenerateResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStoryGenerateResponse)

	if err != nil {
		return err
	}

	*o = StoryGenerateResponse(varStoryGenerateResponse)

	return err
}

type NullableStoryGenerateResponse struct {
	value *StoryGenerateResponse
	isSet bool
}

func (v NullableStoryGenerateResponse) Get() *StoryGenerateResponse {
	return v.value
}

func (v *NullableStoryGenerateResponse) Set(val *StoryGenerateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableStoryGenerateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableStoryGenerateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStoryGenerateResponse(val *StoryGenerateResponse) *NullableStoryGenerateResponse {
	return &NullableStoryGenerateResponse{value: val, isSet: true}
}

func (v NullableStoryGenerateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStoryGenerateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


