/*
Story Engine API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.12
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package storyteller

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the EntityProvenanceExportEntryResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EntityProvenanceExportEntryResponse{}

// EntityProvenanceExportEntryResponse A stable player data export row for entity provenance.
type EntityProvenanceExportEntryResponse struct {
	Id string `json:"id"`
	TenantId string `json:"tenant_id"`
	StoryId string `json:"story_id"`
	SessionId string `json:"session_id"`
	PlaythroughId string `json:"playthrough_id"`
	EntityType string `json:"entity_type"`
	EntityId string `json:"entity_id"`
	IntroducedAtNodeId string `json:"introduced_at_node_id"`
	IntroducedAtChoiceId NullableString `json:"introduced_at_choice_id"`
	LastUpdatedAtNodeId NullableString `json:"last_updated_at_node_id"`
	LastUpdatedAtChoiceId NullableString `json:"last_updated_at_choice_id"`
	IntroducedAt time.Time `json:"introduced_at"`
	LastUpdatedAt NullableTime `json:"last_updated_at"`
}

type _EntityProvenanceExportEntryResponse EntityProvenanceExportEntryResponse

// NewEntityProvenanceExportEntryResponse instantiates a new EntityProvenanceExportEntryResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEntityProvenanceExportEntryResponse(id string, tenantId string, storyId string, sessionId string, playthroughId string, entityType string, entityId string, introducedAtNodeId string, introducedAtChoiceId NullableString, lastUpdatedAtNodeId NullableString, lastUpdatedAtChoiceId NullableString, introducedAt time.Time, lastUpdatedAt NullableTime) *EntityProvenanceExportEntryResponse {
	this := EntityProvenanceExportEntryResponse{}
	this.Id = id
	this.TenantId = tenantId
	this.StoryId = storyId
	this.SessionId = sessionId
	this.PlaythroughId = playthroughId
	this.EntityType = entityType
	this.EntityId = entityId
	this.IntroducedAtNodeId = introducedAtNodeId
	this.IntroducedAtChoiceId = introducedAtChoiceId
	this.LastUpdatedAtNodeId = lastUpdatedAtNodeId
	this.LastUpdatedAtChoiceId = lastUpdatedAtChoiceId
	this.IntroducedAt = introducedAt
	this.LastUpdatedAt = lastUpdatedAt
	return &this
}

// NewEntityProvenanceExportEntryResponseWithDefaults instantiates a new EntityProvenanceExportEntryResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEntityProvenanceExportEntryResponseWithDefaults() *EntityProvenanceExportEntryResponse {
	this := EntityProvenanceExportEntryResponse{}
	return &this
}

// GetId returns the Id field value
func (o *EntityProvenanceExportEntryResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *EntityProvenanceExportEntryResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *EntityProvenanceExportEntryResponse) SetId(v string) {
	o.Id = v
}

// GetTenantId returns the TenantId field value
func (o *EntityProvenanceExportEntryResponse) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *EntityProvenanceExportEntryResponse) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *EntityProvenanceExportEntryResponse) SetTenantId(v string) {
	o.TenantId = v
}

// GetStoryId returns the StoryId field value
func (o *EntityProvenanceExportEntryResponse) GetStoryId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StoryId
}

// GetStoryIdOk returns a tuple with the StoryId field value
// and a boolean to check if the value has been set.
func (o *EntityProvenanceExportEntryResponse) GetStoryIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StoryId, true
}

// SetStoryId sets field value
func (o *EntityProvenanceExportEntryResponse) SetStoryId(v string) {
	o.StoryId = v
}

// GetSessionId returns the SessionId field value
func (o *EntityProvenanceExportEntryResponse) GetSessionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SessionId
}

// GetSessionIdOk returns a tuple with the SessionId field value
// and a boolean to check if the value has been set.
func (o *EntityProvenanceExportEntryResponse) GetSessionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SessionId, true
}

// SetSessionId sets field value
func (o *EntityProvenanceExportEntryResponse) SetSessionId(v string) {
	o.SessionId = v
}

// GetPlaythroughId returns the PlaythroughId field value
func (o *EntityProvenanceExportEntryResponse) GetPlaythroughId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PlaythroughId
}

// GetPlaythroughIdOk returns a tuple with the PlaythroughId field value
// and a boolean to check if the value has been set.
func (o *EntityProvenanceExportEntryResponse) GetPlaythroughIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlaythroughId, true
}

// SetPlaythroughId sets field value
func (o *EntityProvenanceExportEntryResponse) SetPlaythroughId(v string) {
	o.PlaythroughId = v
}

// GetEntityType returns the EntityType field value
func (o *EntityProvenanceExportEntryResponse) GetEntityType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EntityType
}

// GetEntityTypeOk returns a tuple with the EntityType field value
// and a boolean to check if the value has been set.
func (o *EntityProvenanceExportEntryResponse) GetEntityTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EntityType, true
}

// SetEntityType sets field value
func (o *EntityProvenanceExportEntryResponse) SetEntityType(v string) {
	o.EntityType = v
}

// GetEntityId returns the EntityId field value
func (o *EntityProvenanceExportEntryResponse) GetEntityId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EntityId
}

// GetEntityIdOk returns a tuple with the EntityId field value
// and a boolean to check if the value has been set.
func (o *EntityProvenanceExportEntryResponse) GetEntityIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EntityId, true
}

// SetEntityId sets field value
func (o *EntityProvenanceExportEntryResponse) SetEntityId(v string) {
	o.EntityId = v
}

// GetIntroducedAtNodeId returns the IntroducedAtNodeId field value
func (o *EntityProvenanceExportEntryResponse) GetIntroducedAtNodeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IntroducedAtNodeId
}

// GetIntroducedAtNodeIdOk returns a tuple with the IntroducedAtNodeId field value
// and a boolean to check if the value has been set.
func (o *EntityProvenanceExportEntryResponse) GetIntroducedAtNodeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IntroducedAtNodeId, true
}

// SetIntroducedAtNodeId sets field value
func (o *EntityProvenanceExportEntryResponse) SetIntroducedAtNodeId(v string) {
	o.IntroducedAtNodeId = v
}

// GetIntroducedAtChoiceId returns the IntroducedAtChoiceId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *EntityProvenanceExportEntryResponse) GetIntroducedAtChoiceId() string {
	if o == nil || o.IntroducedAtChoiceId.Get() == nil {
		var ret string
		return ret
	}

	return *o.IntroducedAtChoiceId.Get()
}

// GetIntroducedAtChoiceIdOk returns a tuple with the IntroducedAtChoiceId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EntityProvenanceExportEntryResponse) GetIntroducedAtChoiceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.IntroducedAtChoiceId.Get(), o.IntroducedAtChoiceId.IsSet()
}

// SetIntroducedAtChoiceId sets field value
func (o *EntityProvenanceExportEntryResponse) SetIntroducedAtChoiceId(v string) {
	o.IntroducedAtChoiceId.Set(&v)
}

// GetLastUpdatedAtNodeId returns the LastUpdatedAtNodeId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *EntityProvenanceExportEntryResponse) GetLastUpdatedAtNodeId() string {
	if o == nil || o.LastUpdatedAtNodeId.Get() == nil {
		var ret string
		return ret
	}

	return *o.LastUpdatedAtNodeId.Get()
}

// GetLastUpdatedAtNodeIdOk returns a tuple with the LastUpdatedAtNodeId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EntityProvenanceExportEntryResponse) GetLastUpdatedAtNodeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastUpdatedAtNodeId.Get(), o.LastUpdatedAtNodeId.IsSet()
}

// SetLastUpdatedAtNodeId sets field value
func (o *EntityProvenanceExportEntryResponse) SetLastUpdatedAtNodeId(v string) {
	o.LastUpdatedAtNodeId.Set(&v)
}

// GetLastUpdatedAtChoiceId returns the LastUpdatedAtChoiceId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *EntityProvenanceExportEntryResponse) GetLastUpdatedAtChoiceId() string {
	if o == nil || o.LastUpdatedAtChoiceId.Get() == nil {
		var ret string
		return ret
	}

	return *o.LastUpdatedAtChoiceId.Get()
}

// GetLastUpdatedAtChoiceIdOk returns a tuple with the LastUpdatedAtChoiceId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EntityProvenanceExportEntryResponse) GetLastUpdatedAtChoiceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastUpdatedAtChoiceId.Get(), o.LastUpdatedAtChoiceId.IsSet()
}

// SetLastUpdatedAtChoiceId sets field value
func (o *EntityProvenanceExportEntryResponse) SetLastUpdatedAtChoiceId(v string) {
	o.LastUpdatedAtChoiceId.Set(&v)
}

// GetIntroducedAt returns the IntroducedAt field value
func (o *EntityProvenanceExportEntryResponse) GetIntroducedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.IntroducedAt
}

// GetIntroducedAtOk returns a tuple with the IntroducedAt field value
// and a boolean to check if the value has been set.
func (o *EntityProvenanceExportEntryResponse) GetIntroducedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IntroducedAt, true
}

// SetIntroducedAt sets field value
func (o *EntityProvenanceExportEntryResponse) SetIntroducedAt(v time.Time) {
	o.IntroducedAt = v
}

// GetLastUpdatedAt returns the LastUpdatedAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *EntityProvenanceExportEntryResponse) GetLastUpdatedAt() time.Time {
	if o == nil || o.LastUpdatedAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.LastUpdatedAt.Get()
}

// GetLastUpdatedAtOk returns a tuple with the LastUpdatedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EntityProvenanceExportEntryResponse) GetLastUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastUpdatedAt.Get(), o.LastUpdatedAt.IsSet()
}

// SetLastUpdatedAt sets field value
func (o *EntityProvenanceExportEntryResponse) SetLastUpdatedAt(v time.Time) {
	o.LastUpdatedAt.Set(&v)
}

func (o EntityProvenanceExportEntryResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EntityProvenanceExportEntryResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["tenant_id"] = o.TenantId
	toSerialize["story_id"] = o.StoryId
	toSerialize["session_id"] = o.SessionId
	toSerialize["playthrough_id"] = o.PlaythroughId
	toSerialize["entity_type"] = o.EntityType
	toSerialize["entity_id"] = o.EntityId
	toSerialize["introduced_at_node_id"] = o.IntroducedAtNodeId
	toSerialize["introduced_at_choice_id"] = o.IntroducedAtChoiceId.Get()
	toSerialize["last_updated_at_node_id"] = o.LastUpdatedAtNodeId.Get()
	toSerialize["last_updated_at_choice_id"] = o.LastUpdatedAtChoiceId.Get()
	toSerialize["introduced_at"] = o.IntroducedAt
	toSerialize["last_updated_at"] = o.LastUpdatedAt.Get()
	return toSerialize, nil
}

func (o *EntityProvenanceExportEntryResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"tenant_id",
		"story_id",
		"session_id",
		"playthrough_id",
		"entity_type",
		"entity_id",
		"introduced_at_node_id",
		"introduced_at_choice_id",
		"last_updated_at_node_id",
		"last_updated_at_choice_id",
		"introduced_at",
		"last_updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEntityProvenanceExportEntryResponse := _EntityProvenanceExportEntryResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEntityProvenanceExportEntryResponse)

	if err != nil {
		return err
	}

	*o = EntityProvenanceExportEntryResponse(varEntityProvenanceExportEntryResponse)

	return err
}

type NullableEntityProvenanceExportEntryResponse struct {
	value *EntityProvenanceExportEntryResponse
	isSet bool
}

func (v NullableEntityProvenanceExportEntryResponse) Get() *EntityProvenanceExportEntryResponse {
	return v.value
}

func (v *NullableEntityProvenanceExportEntryResponse) Set(val *EntityProvenanceExportEntryResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableEntityProvenanceExportEntryResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableEntityProvenanceExportEntryResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEntityProvenanceExportEntryResponse(val *EntityProvenanceExportEntryResponse) *NullableEntityProvenanceExportEntryResponse {
	return &NullableEntityProvenanceExportEntryResponse{value: val, isSet: true}
}

func (v NullableEntityProvenanceExportEntryResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEntityProvenanceExportEntryResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


