/*
Story Engine API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.13
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package storyteller

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V1AuthoringStoriesStoryIdGraphGet200ResponseNodesValue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1AuthoringStoriesStoryIdGraphGet200ResponseNodesValue{}

// V1AuthoringStoriesStoryIdGraphGet200ResponseNodesValue struct for V1AuthoringStoriesStoryIdGraphGet200ResponseNodesValue
type V1AuthoringStoriesStoryIdGraphGet200ResponseNodesValue struct {
	Choices []V1AuthoringStoriesStoryIdGraphGet200ResponseNodesValueChoicesInner `json:"choices"`
	NodeId string `json:"node_id"`
	NodeType string `json:"node_type"`
	Text *string `json:"text,omitempty"`
}

type _V1AuthoringStoriesStoryIdGraphGet200ResponseNodesValue V1AuthoringStoriesStoryIdGraphGet200ResponseNodesValue

// NewV1AuthoringStoriesStoryIdGraphGet200ResponseNodesValue instantiates a new V1AuthoringStoriesStoryIdGraphGet200ResponseNodesValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1AuthoringStoriesStoryIdGraphGet200ResponseNodesValue(choices []V1AuthoringStoriesStoryIdGraphGet200ResponseNodesValueChoicesInner, nodeId string, nodeType string) *V1AuthoringStoriesStoryIdGraphGet200ResponseNodesValue {
	this := V1AuthoringStoriesStoryIdGraphGet200ResponseNodesValue{}
	this.Choices = choices
	this.NodeId = nodeId
	this.NodeType = nodeType
	return &this
}

// NewV1AuthoringStoriesStoryIdGraphGet200ResponseNodesValueWithDefaults instantiates a new V1AuthoringStoriesStoryIdGraphGet200ResponseNodesValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1AuthoringStoriesStoryIdGraphGet200ResponseNodesValueWithDefaults() *V1AuthoringStoriesStoryIdGraphGet200ResponseNodesValue {
	this := V1AuthoringStoriesStoryIdGraphGet200ResponseNodesValue{}
	return &this
}

// GetChoices returns the Choices field value
func (o *V1AuthoringStoriesStoryIdGraphGet200ResponseNodesValue) GetChoices() []V1AuthoringStoriesStoryIdGraphGet200ResponseNodesValueChoicesInner {
	if o == nil {
		var ret []V1AuthoringStoriesStoryIdGraphGet200ResponseNodesValueChoicesInner
		return ret
	}

	return o.Choices
}

// GetChoicesOk returns a tuple with the Choices field value
// and a boolean to check if the value has been set.
func (o *V1AuthoringStoriesStoryIdGraphGet200ResponseNodesValue) GetChoicesOk() ([]V1AuthoringStoriesStoryIdGraphGet200ResponseNodesValueChoicesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Choices, true
}

// SetChoices sets field value
func (o *V1AuthoringStoriesStoryIdGraphGet200ResponseNodesValue) SetChoices(v []V1AuthoringStoriesStoryIdGraphGet200ResponseNodesValueChoicesInner) {
	o.Choices = v
}

// GetNodeId returns the NodeId field value
func (o *V1AuthoringStoriesStoryIdGraphGet200ResponseNodesValue) GetNodeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NodeId
}

// GetNodeIdOk returns a tuple with the NodeId field value
// and a boolean to check if the value has been set.
func (o *V1AuthoringStoriesStoryIdGraphGet200ResponseNodesValue) GetNodeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NodeId, true
}

// SetNodeId sets field value
func (o *V1AuthoringStoriesStoryIdGraphGet200ResponseNodesValue) SetNodeId(v string) {
	o.NodeId = v
}

// GetNodeType returns the NodeType field value
func (o *V1AuthoringStoriesStoryIdGraphGet200ResponseNodesValue) GetNodeType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NodeType
}

// GetNodeTypeOk returns a tuple with the NodeType field value
// and a boolean to check if the value has been set.
func (o *V1AuthoringStoriesStoryIdGraphGet200ResponseNodesValue) GetNodeTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NodeType, true
}

// SetNodeType sets field value
func (o *V1AuthoringStoriesStoryIdGraphGet200ResponseNodesValue) SetNodeType(v string) {
	o.NodeType = v
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *V1AuthoringStoriesStoryIdGraphGet200ResponseNodesValue) GetText() string {
	if o == nil || IsNil(o.Text) {
		var ret string
		return ret
	}
	return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1AuthoringStoriesStoryIdGraphGet200ResponseNodesValue) GetTextOk() (*string, bool) {
	if o == nil || IsNil(o.Text) {
		return nil, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *V1AuthoringStoriesStoryIdGraphGet200ResponseNodesValue) HasText() bool {
	if o != nil && !IsNil(o.Text) {
		return true
	}

	return false
}

// SetText gets a reference to the given string and assigns it to the Text field.
func (o *V1AuthoringStoriesStoryIdGraphGet200ResponseNodesValue) SetText(v string) {
	o.Text = &v
}

func (o V1AuthoringStoriesStoryIdGraphGet200ResponseNodesValue) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1AuthoringStoriesStoryIdGraphGet200ResponseNodesValue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["choices"] = o.Choices
	toSerialize["node_id"] = o.NodeId
	toSerialize["node_type"] = o.NodeType
	if !IsNil(o.Text) {
		toSerialize["text"] = o.Text
	}
	return toSerialize, nil
}

func (o *V1AuthoringStoriesStoryIdGraphGet200ResponseNodesValue) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"choices",
		"node_id",
		"node_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1AuthoringStoriesStoryIdGraphGet200ResponseNodesValue := _V1AuthoringStoriesStoryIdGraphGet200ResponseNodesValue{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV1AuthoringStoriesStoryIdGraphGet200ResponseNodesValue)

	if err != nil {
		return err
	}

	*o = V1AuthoringStoriesStoryIdGraphGet200ResponseNodesValue(varV1AuthoringStoriesStoryIdGraphGet200ResponseNodesValue)

	return err
}

type NullableV1AuthoringStoriesStoryIdGraphGet200ResponseNodesValue struct {
	value *V1AuthoringStoriesStoryIdGraphGet200ResponseNodesValue
	isSet bool
}

func (v NullableV1AuthoringStoriesStoryIdGraphGet200ResponseNodesValue) Get() *V1AuthoringStoriesStoryIdGraphGet200ResponseNodesValue {
	return v.value
}

func (v *NullableV1AuthoringStoriesStoryIdGraphGet200ResponseNodesValue) Set(val *V1AuthoringStoriesStoryIdGraphGet200ResponseNodesValue) {
	v.value = val
	v.isSet = true
}

func (v NullableV1AuthoringStoriesStoryIdGraphGet200ResponseNodesValue) IsSet() bool {
	return v.isSet
}

func (v *NullableV1AuthoringStoriesStoryIdGraphGet200ResponseNodesValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1AuthoringStoriesStoryIdGraphGet200ResponseNodesValue(val *V1AuthoringStoriesStoryIdGraphGet200ResponseNodesValue) *NullableV1AuthoringStoriesStoryIdGraphGet200ResponseNodesValue {
	return &NullableV1AuthoringStoriesStoryIdGraphGet200ResponseNodesValue{value: val, isSet: true}
}

func (v NullableV1AuthoringStoriesStoryIdGraphGet200ResponseNodesValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1AuthoringStoriesStoryIdGraphGet200ResponseNodesValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


