/*
Story Engine API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.12
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package storyteller

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GraphTopologyResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GraphTopologyResponse{}

// GraphTopologyResponse Full DAG structure returned by GET /story/{id}/topology.  Intended for author tooling and debugging.  ``nodes`` is a list of ``{id, node_type}`` dicts.  ``edges`` encodes each choice arc. ``flag_schema`` and ``characters`` are the author-declared game-state definitions for the story.
type GraphTopologyResponse struct {
	StoryId string `json:"story_id"`
	StartNodeId string `json:"start_node_id"`
	Nodes []map[string]string `json:"nodes"`
	Edges []GraphEdge `json:"edges"`
	FlagSchema map[string]interface{} `json:"flag_schema,omitempty"`
	Characters map[string]interface{} `json:"characters,omitempty"`
	Locations map[string]interface{} `json:"locations,omitempty"`
	Objects map[string]interface{} `json:"objects,omitempty"`
	AllowFreeTextContinuation *bool `json:"allow_free_text_continuation,omitempty"`
	ExplorationNodes []*map[string]interface{} `json:"exploration_nodes,omitempty"`
}

type _GraphTopologyResponse GraphTopologyResponse

// NewGraphTopologyResponse instantiates a new GraphTopologyResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGraphTopologyResponse(storyId string, startNodeId string, nodes []map[string]string, edges []GraphEdge) *GraphTopologyResponse {
	this := GraphTopologyResponse{}
	this.StoryId = storyId
	this.StartNodeId = startNodeId
	this.Nodes = nodes
	this.Edges = edges
	var allowFreeTextContinuation bool = true
	this.AllowFreeTextContinuation = &allowFreeTextContinuation
	return &this
}

// NewGraphTopologyResponseWithDefaults instantiates a new GraphTopologyResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGraphTopologyResponseWithDefaults() *GraphTopologyResponse {
	this := GraphTopologyResponse{}
	var allowFreeTextContinuation bool = true
	this.AllowFreeTextContinuation = &allowFreeTextContinuation
	return &this
}

// GetStoryId returns the StoryId field value
func (o *GraphTopologyResponse) GetStoryId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StoryId
}

// GetStoryIdOk returns a tuple with the StoryId field value
// and a boolean to check if the value has been set.
func (o *GraphTopologyResponse) GetStoryIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StoryId, true
}

// SetStoryId sets field value
func (o *GraphTopologyResponse) SetStoryId(v string) {
	o.StoryId = v
}

// GetStartNodeId returns the StartNodeId field value
func (o *GraphTopologyResponse) GetStartNodeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StartNodeId
}

// GetStartNodeIdOk returns a tuple with the StartNodeId field value
// and a boolean to check if the value has been set.
func (o *GraphTopologyResponse) GetStartNodeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartNodeId, true
}

// SetStartNodeId sets field value
func (o *GraphTopologyResponse) SetStartNodeId(v string) {
	o.StartNodeId = v
}

// GetNodes returns the Nodes field value
func (o *GraphTopologyResponse) GetNodes() []map[string]string {
	if o == nil {
		var ret []map[string]string
		return ret
	}

	return o.Nodes
}

// GetNodesOk returns a tuple with the Nodes field value
// and a boolean to check if the value has been set.
func (o *GraphTopologyResponse) GetNodesOk() ([]map[string]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Nodes, true
}

// SetNodes sets field value
func (o *GraphTopologyResponse) SetNodes(v []map[string]string) {
	o.Nodes = v
}

// GetEdges returns the Edges field value
func (o *GraphTopologyResponse) GetEdges() []GraphEdge {
	if o == nil {
		var ret []GraphEdge
		return ret
	}

	return o.Edges
}

// GetEdgesOk returns a tuple with the Edges field value
// and a boolean to check if the value has been set.
func (o *GraphTopologyResponse) GetEdgesOk() ([]GraphEdge, bool) {
	if o == nil {
		return nil, false
	}
	return o.Edges, true
}

// SetEdges sets field value
func (o *GraphTopologyResponse) SetEdges(v []GraphEdge) {
	o.Edges = v
}

// GetFlagSchema returns the FlagSchema field value if set, zero value otherwise.
func (o *GraphTopologyResponse) GetFlagSchema() map[string]interface{} {
	if o == nil || IsNil(o.FlagSchema) {
		var ret map[string]interface{}
		return ret
	}
	return o.FlagSchema
}

// GetFlagSchemaOk returns a tuple with the FlagSchema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GraphTopologyResponse) GetFlagSchemaOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.FlagSchema) {
		return map[string]interface{}{}, false
	}
	return o.FlagSchema, true
}

// HasFlagSchema returns a boolean if a field has been set.
func (o *GraphTopologyResponse) HasFlagSchema() bool {
	if o != nil && !IsNil(o.FlagSchema) {
		return true
	}

	return false
}

// SetFlagSchema gets a reference to the given map[string]interface{} and assigns it to the FlagSchema field.
func (o *GraphTopologyResponse) SetFlagSchema(v map[string]interface{}) {
	o.FlagSchema = v
}

// GetCharacters returns the Characters field value if set, zero value otherwise.
func (o *GraphTopologyResponse) GetCharacters() map[string]interface{} {
	if o == nil || IsNil(o.Characters) {
		var ret map[string]interface{}
		return ret
	}
	return o.Characters
}

// GetCharactersOk returns a tuple with the Characters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GraphTopologyResponse) GetCharactersOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Characters) {
		return map[string]interface{}{}, false
	}
	return o.Characters, true
}

// HasCharacters returns a boolean if a field has been set.
func (o *GraphTopologyResponse) HasCharacters() bool {
	if o != nil && !IsNil(o.Characters) {
		return true
	}

	return false
}

// SetCharacters gets a reference to the given map[string]interface{} and assigns it to the Characters field.
func (o *GraphTopologyResponse) SetCharacters(v map[string]interface{}) {
	o.Characters = v
}

// GetLocations returns the Locations field value if set, zero value otherwise.
func (o *GraphTopologyResponse) GetLocations() map[string]interface{} {
	if o == nil || IsNil(o.Locations) {
		var ret map[string]interface{}
		return ret
	}
	return o.Locations
}

// GetLocationsOk returns a tuple with the Locations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GraphTopologyResponse) GetLocationsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Locations) {
		return map[string]interface{}{}, false
	}
	return o.Locations, true
}

// HasLocations returns a boolean if a field has been set.
func (o *GraphTopologyResponse) HasLocations() bool {
	if o != nil && !IsNil(o.Locations) {
		return true
	}

	return false
}

// SetLocations gets a reference to the given map[string]interface{} and assigns it to the Locations field.
func (o *GraphTopologyResponse) SetLocations(v map[string]interface{}) {
	o.Locations = v
}

// GetObjects returns the Objects field value if set, zero value otherwise.
func (o *GraphTopologyResponse) GetObjects() map[string]interface{} {
	if o == nil || IsNil(o.Objects) {
		var ret map[string]interface{}
		return ret
	}
	return o.Objects
}

// GetObjectsOk returns a tuple with the Objects field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GraphTopologyResponse) GetObjectsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Objects) {
		return map[string]interface{}{}, false
	}
	return o.Objects, true
}

// HasObjects returns a boolean if a field has been set.
func (o *GraphTopologyResponse) HasObjects() bool {
	if o != nil && !IsNil(o.Objects) {
		return true
	}

	return false
}

// SetObjects gets a reference to the given map[string]interface{} and assigns it to the Objects field.
func (o *GraphTopologyResponse) SetObjects(v map[string]interface{}) {
	o.Objects = v
}

// GetAllowFreeTextContinuation returns the AllowFreeTextContinuation field value if set, zero value otherwise.
func (o *GraphTopologyResponse) GetAllowFreeTextContinuation() bool {
	if o == nil || IsNil(o.AllowFreeTextContinuation) {
		var ret bool
		return ret
	}
	return *o.AllowFreeTextContinuation
}

// GetAllowFreeTextContinuationOk returns a tuple with the AllowFreeTextContinuation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GraphTopologyResponse) GetAllowFreeTextContinuationOk() (*bool, bool) {
	if o == nil || IsNil(o.AllowFreeTextContinuation) {
		return nil, false
	}
	return o.AllowFreeTextContinuation, true
}

// HasAllowFreeTextContinuation returns a boolean if a field has been set.
func (o *GraphTopologyResponse) HasAllowFreeTextContinuation() bool {
	if o != nil && !IsNil(o.AllowFreeTextContinuation) {
		return true
	}

	return false
}

// SetAllowFreeTextContinuation gets a reference to the given bool and assigns it to the AllowFreeTextContinuation field.
func (o *GraphTopologyResponse) SetAllowFreeTextContinuation(v bool) {
	o.AllowFreeTextContinuation = &v
}

// GetExplorationNodes returns the ExplorationNodes field value if set, zero value otherwise.
func (o *GraphTopologyResponse) GetExplorationNodes() []*map[string]interface{} {
	if o == nil || IsNil(o.ExplorationNodes) {
		var ret []*map[string]interface{}
		return ret
	}
	return o.ExplorationNodes
}

// GetExplorationNodesOk returns a tuple with the ExplorationNodes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GraphTopologyResponse) GetExplorationNodesOk() ([]*map[string]interface{}, bool) {
	if o == nil || IsNil(o.ExplorationNodes) {
		return nil, false
	}
	return o.ExplorationNodes, true
}

// HasExplorationNodes returns a boolean if a field has been set.
func (o *GraphTopologyResponse) HasExplorationNodes() bool {
	if o != nil && !IsNil(o.ExplorationNodes) {
		return true
	}

	return false
}

// SetExplorationNodes gets a reference to the given []*map[string]interface{} and assigns it to the ExplorationNodes field.
func (o *GraphTopologyResponse) SetExplorationNodes(v []*map[string]interface{}) {
	o.ExplorationNodes = v
}

func (o GraphTopologyResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GraphTopologyResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["story_id"] = o.StoryId
	toSerialize["start_node_id"] = o.StartNodeId
	toSerialize["nodes"] = o.Nodes
	toSerialize["edges"] = o.Edges
	if !IsNil(o.FlagSchema) {
		toSerialize["flag_schema"] = o.FlagSchema
	}
	if !IsNil(o.Characters) {
		toSerialize["characters"] = o.Characters
	}
	if !IsNil(o.Locations) {
		toSerialize["locations"] = o.Locations
	}
	if !IsNil(o.Objects) {
		toSerialize["objects"] = o.Objects
	}
	if !IsNil(o.AllowFreeTextContinuation) {
		toSerialize["allow_free_text_continuation"] = o.AllowFreeTextContinuation
	}
	if !IsNil(o.ExplorationNodes) {
		toSerialize["exploration_nodes"] = o.ExplorationNodes
	}
	return toSerialize, nil
}

func (o *GraphTopologyResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"story_id",
		"start_node_id",
		"nodes",
		"edges",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGraphTopologyResponse := _GraphTopologyResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGraphTopologyResponse)

	if err != nil {
		return err
	}

	*o = GraphTopologyResponse(varGraphTopologyResponse)

	return err
}

type NullableGraphTopologyResponse struct {
	value *GraphTopologyResponse
	isSet bool
}

func (v NullableGraphTopologyResponse) Get() *GraphTopologyResponse {
	return v.value
}

func (v *NullableGraphTopologyResponse) Set(val *GraphTopologyResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGraphTopologyResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGraphTopologyResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGraphTopologyResponse(val *GraphTopologyResponse) *NullableGraphTopologyResponse {
	return &NullableGraphTopologyResponse{value: val, isSet: true}
}

func (v NullableGraphTopologyResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGraphTopologyResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


