/*
Story Engine API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.13
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package storyteller

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V1AdminStoryStoryIdGet200ResponseLocationsValue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1AdminStoryStoryIdGet200ResponseLocationsValue{}

// V1AdminStoryStoryIdGet200ResponseLocationsValue struct for V1AdminStoryStoryIdGet200ResponseLocationsValue
type V1AdminStoryStoryIdGet200ResponseLocationsValue struct {
	Atmosphere string `json:"atmosphere"`
	ConnectedTo []string `json:"connected_to"`
	Description string `json:"description"`
	Name string `json:"name"`
	Region string `json:"region"`
}

type _V1AdminStoryStoryIdGet200ResponseLocationsValue V1AdminStoryStoryIdGet200ResponseLocationsValue

// NewV1AdminStoryStoryIdGet200ResponseLocationsValue instantiates a new V1AdminStoryStoryIdGet200ResponseLocationsValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1AdminStoryStoryIdGet200ResponseLocationsValue(atmosphere string, connectedTo []string, description string, name string, region string) *V1AdminStoryStoryIdGet200ResponseLocationsValue {
	this := V1AdminStoryStoryIdGet200ResponseLocationsValue{}
	this.Atmosphere = atmosphere
	this.ConnectedTo = connectedTo
	this.Description = description
	this.Name = name
	this.Region = region
	return &this
}

// NewV1AdminStoryStoryIdGet200ResponseLocationsValueWithDefaults instantiates a new V1AdminStoryStoryIdGet200ResponseLocationsValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1AdminStoryStoryIdGet200ResponseLocationsValueWithDefaults() *V1AdminStoryStoryIdGet200ResponseLocationsValue {
	this := V1AdminStoryStoryIdGet200ResponseLocationsValue{}
	return &this
}

// GetAtmosphere returns the Atmosphere field value
func (o *V1AdminStoryStoryIdGet200ResponseLocationsValue) GetAtmosphere() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Atmosphere
}

// GetAtmosphereOk returns a tuple with the Atmosphere field value
// and a boolean to check if the value has been set.
func (o *V1AdminStoryStoryIdGet200ResponseLocationsValue) GetAtmosphereOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Atmosphere, true
}

// SetAtmosphere sets field value
func (o *V1AdminStoryStoryIdGet200ResponseLocationsValue) SetAtmosphere(v string) {
	o.Atmosphere = v
}

// GetConnectedTo returns the ConnectedTo field value
func (o *V1AdminStoryStoryIdGet200ResponseLocationsValue) GetConnectedTo() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.ConnectedTo
}

// GetConnectedToOk returns a tuple with the ConnectedTo field value
// and a boolean to check if the value has been set.
func (o *V1AdminStoryStoryIdGet200ResponseLocationsValue) GetConnectedToOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ConnectedTo, true
}

// SetConnectedTo sets field value
func (o *V1AdminStoryStoryIdGet200ResponseLocationsValue) SetConnectedTo(v []string) {
	o.ConnectedTo = v
}

// GetDescription returns the Description field value
func (o *V1AdminStoryStoryIdGet200ResponseLocationsValue) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *V1AdminStoryStoryIdGet200ResponseLocationsValue) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *V1AdminStoryStoryIdGet200ResponseLocationsValue) SetDescription(v string) {
	o.Description = v
}

// GetName returns the Name field value
func (o *V1AdminStoryStoryIdGet200ResponseLocationsValue) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *V1AdminStoryStoryIdGet200ResponseLocationsValue) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *V1AdminStoryStoryIdGet200ResponseLocationsValue) SetName(v string) {
	o.Name = v
}

// GetRegion returns the Region field value
func (o *V1AdminStoryStoryIdGet200ResponseLocationsValue) GetRegion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Region
}

// GetRegionOk returns a tuple with the Region field value
// and a boolean to check if the value has been set.
func (o *V1AdminStoryStoryIdGet200ResponseLocationsValue) GetRegionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Region, true
}

// SetRegion sets field value
func (o *V1AdminStoryStoryIdGet200ResponseLocationsValue) SetRegion(v string) {
	o.Region = v
}

func (o V1AdminStoryStoryIdGet200ResponseLocationsValue) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1AdminStoryStoryIdGet200ResponseLocationsValue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["atmosphere"] = o.Atmosphere
	toSerialize["connected_to"] = o.ConnectedTo
	toSerialize["description"] = o.Description
	toSerialize["name"] = o.Name
	toSerialize["region"] = o.Region
	return toSerialize, nil
}

func (o *V1AdminStoryStoryIdGet200ResponseLocationsValue) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"atmosphere",
		"connected_to",
		"description",
		"name",
		"region",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1AdminStoryStoryIdGet200ResponseLocationsValue := _V1AdminStoryStoryIdGet200ResponseLocationsValue{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV1AdminStoryStoryIdGet200ResponseLocationsValue)

	if err != nil {
		return err
	}

	*o = V1AdminStoryStoryIdGet200ResponseLocationsValue(varV1AdminStoryStoryIdGet200ResponseLocationsValue)

	return err
}

type NullableV1AdminStoryStoryIdGet200ResponseLocationsValue struct {
	value *V1AdminStoryStoryIdGet200ResponseLocationsValue
	isSet bool
}

func (v NullableV1AdminStoryStoryIdGet200ResponseLocationsValue) Get() *V1AdminStoryStoryIdGet200ResponseLocationsValue {
	return v.value
}

func (v *NullableV1AdminStoryStoryIdGet200ResponseLocationsValue) Set(val *V1AdminStoryStoryIdGet200ResponseLocationsValue) {
	v.value = val
	v.isSet = true
}

func (v NullableV1AdminStoryStoryIdGet200ResponseLocationsValue) IsSet() bool {
	return v.isSet
}

func (v *NullableV1AdminStoryStoryIdGet200ResponseLocationsValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1AdminStoryStoryIdGet200ResponseLocationsValue(val *V1AdminStoryStoryIdGet200ResponseLocationsValue) *NullableV1AdminStoryStoryIdGet200ResponseLocationsValue {
	return &NullableV1AdminStoryStoryIdGet200ResponseLocationsValue{value: val, isSet: true}
}

func (v NullableV1AdminStoryStoryIdGet200ResponseLocationsValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1AdminStoryStoryIdGet200ResponseLocationsValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


