/*
Story Engine API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.12
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package storyteller

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ChoiceResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChoiceResponse{}

// ChoiceResponse A single authored or LLM-generated player choice surfaced by the API.  ``target_node_id`` is intentionally exposed to the client to enable prefetching of the next node's content before the player commits. ``flag_delta`` contains world-state mutations that apply when this choice is taken; the client may use this to preview consequences. ``flag_schema_delta`` carries schema entries for the flags mentioned in ``flag_delta`` when they are available on the current branch.
type ChoiceResponse struct {
	Id string `json:"id"`
	Label string `json:"label"`
	TargetNodeId NullableString `json:"target_node_id"`
	FlagDelta map[string]interface{} `json:"flag_delta,omitempty"`
	FlagSchemaDelta map[string]interface{} `json:"flag_schema_delta,omitempty"`
}

type _ChoiceResponse ChoiceResponse

// NewChoiceResponse instantiates a new ChoiceResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChoiceResponse(id string, label string, targetNodeId NullableString) *ChoiceResponse {
	this := ChoiceResponse{}
	this.Id = id
	this.Label = label
	this.TargetNodeId = targetNodeId
	return &this
}

// NewChoiceResponseWithDefaults instantiates a new ChoiceResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChoiceResponseWithDefaults() *ChoiceResponse {
	this := ChoiceResponse{}
	return &this
}

// GetId returns the Id field value
func (o *ChoiceResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ChoiceResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ChoiceResponse) SetId(v string) {
	o.Id = v
}

// GetLabel returns the Label field value
func (o *ChoiceResponse) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *ChoiceResponse) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *ChoiceResponse) SetLabel(v string) {
	o.Label = v
}

// GetTargetNodeId returns the TargetNodeId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ChoiceResponse) GetTargetNodeId() string {
	if o == nil || o.TargetNodeId.Get() == nil {
		var ret string
		return ret
	}

	return *o.TargetNodeId.Get()
}

// GetTargetNodeIdOk returns a tuple with the TargetNodeId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ChoiceResponse) GetTargetNodeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TargetNodeId.Get(), o.TargetNodeId.IsSet()
}

// SetTargetNodeId sets field value
func (o *ChoiceResponse) SetTargetNodeId(v string) {
	o.TargetNodeId.Set(&v)
}

// GetFlagDelta returns the FlagDelta field value if set, zero value otherwise.
func (o *ChoiceResponse) GetFlagDelta() map[string]interface{} {
	if o == nil || IsNil(o.FlagDelta) {
		var ret map[string]interface{}
		return ret
	}
	return o.FlagDelta
}

// GetFlagDeltaOk returns a tuple with the FlagDelta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChoiceResponse) GetFlagDeltaOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.FlagDelta) {
		return map[string]interface{}{}, false
	}
	return o.FlagDelta, true
}

// HasFlagDelta returns a boolean if a field has been set.
func (o *ChoiceResponse) HasFlagDelta() bool {
	if o != nil && !IsNil(o.FlagDelta) {
		return true
	}

	return false
}

// SetFlagDelta gets a reference to the given map[string]interface{} and assigns it to the FlagDelta field.
func (o *ChoiceResponse) SetFlagDelta(v map[string]interface{}) {
	o.FlagDelta = v
}

// GetFlagSchemaDelta returns the FlagSchemaDelta field value if set, zero value otherwise.
func (o *ChoiceResponse) GetFlagSchemaDelta() map[string]interface{} {
	if o == nil || IsNil(o.FlagSchemaDelta) {
		var ret map[string]interface{}
		return ret
	}
	return o.FlagSchemaDelta
}

// GetFlagSchemaDeltaOk returns a tuple with the FlagSchemaDelta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChoiceResponse) GetFlagSchemaDeltaOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.FlagSchemaDelta) {
		return map[string]interface{}{}, false
	}
	return o.FlagSchemaDelta, true
}

// HasFlagSchemaDelta returns a boolean if a field has been set.
func (o *ChoiceResponse) HasFlagSchemaDelta() bool {
	if o != nil && !IsNil(o.FlagSchemaDelta) {
		return true
	}

	return false
}

// SetFlagSchemaDelta gets a reference to the given map[string]interface{} and assigns it to the FlagSchemaDelta field.
func (o *ChoiceResponse) SetFlagSchemaDelta(v map[string]interface{}) {
	o.FlagSchemaDelta = v
}

func (o ChoiceResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChoiceResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["label"] = o.Label
	toSerialize["target_node_id"] = o.TargetNodeId.Get()
	if !IsNil(o.FlagDelta) {
		toSerialize["flag_delta"] = o.FlagDelta
	}
	if !IsNil(o.FlagSchemaDelta) {
		toSerialize["flag_schema_delta"] = o.FlagSchemaDelta
	}
	return toSerialize, nil
}

func (o *ChoiceResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"label",
		"target_node_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varChoiceResponse := _ChoiceResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varChoiceResponse)

	if err != nil {
		return err
	}

	*o = ChoiceResponse(varChoiceResponse)

	return err
}

type NullableChoiceResponse struct {
	value *ChoiceResponse
	isSet bool
}

func (v NullableChoiceResponse) Get() *ChoiceResponse {
	return v.value
}

func (v *NullableChoiceResponse) Set(val *ChoiceResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableChoiceResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableChoiceResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChoiceResponse(val *ChoiceResponse) *NullableChoiceResponse {
	return &NullableChoiceResponse{value: val, isSet: true}
}

func (v NullableChoiceResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChoiceResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


