/*
Story Engine API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.13
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package storyteller

import (
	"encoding/json"
)

// checks if the V1AuthoringStoriesStoryIdExplorationNodesNodeIdPatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1AuthoringStoriesStoryIdExplorationNodesNodeIdPatchRequest{}

// V1AuthoringStoriesStoryIdExplorationNodesNodeIdPatchRequest struct for V1AuthoringStoriesStoryIdExplorationNodesNodeIdPatchRequest
type V1AuthoringStoriesStoryIdExplorationNodesNodeIdPatchRequest struct {
	Essential *bool `json:"essential,omitempty"`
}

// NewV1AuthoringStoriesStoryIdExplorationNodesNodeIdPatchRequest instantiates a new V1AuthoringStoriesStoryIdExplorationNodesNodeIdPatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1AuthoringStoriesStoryIdExplorationNodesNodeIdPatchRequest() *V1AuthoringStoriesStoryIdExplorationNodesNodeIdPatchRequest {
	this := V1AuthoringStoriesStoryIdExplorationNodesNodeIdPatchRequest{}
	return &this
}

// NewV1AuthoringStoriesStoryIdExplorationNodesNodeIdPatchRequestWithDefaults instantiates a new V1AuthoringStoriesStoryIdExplorationNodesNodeIdPatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1AuthoringStoriesStoryIdExplorationNodesNodeIdPatchRequestWithDefaults() *V1AuthoringStoriesStoryIdExplorationNodesNodeIdPatchRequest {
	this := V1AuthoringStoriesStoryIdExplorationNodesNodeIdPatchRequest{}
	return &this
}

// GetEssential returns the Essential field value if set, zero value otherwise.
func (o *V1AuthoringStoriesStoryIdExplorationNodesNodeIdPatchRequest) GetEssential() bool {
	if o == nil || IsNil(o.Essential) {
		var ret bool
		return ret
	}
	return *o.Essential
}

// GetEssentialOk returns a tuple with the Essential field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1AuthoringStoriesStoryIdExplorationNodesNodeIdPatchRequest) GetEssentialOk() (*bool, bool) {
	if o == nil || IsNil(o.Essential) {
		return nil, false
	}
	return o.Essential, true
}

// HasEssential returns a boolean if a field has been set.
func (o *V1AuthoringStoriesStoryIdExplorationNodesNodeIdPatchRequest) HasEssential() bool {
	if o != nil && !IsNil(o.Essential) {
		return true
	}

	return false
}

// SetEssential gets a reference to the given bool and assigns it to the Essential field.
func (o *V1AuthoringStoriesStoryIdExplorationNodesNodeIdPatchRequest) SetEssential(v bool) {
	o.Essential = &v
}

func (o V1AuthoringStoriesStoryIdExplorationNodesNodeIdPatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1AuthoringStoriesStoryIdExplorationNodesNodeIdPatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Essential) {
		toSerialize["essential"] = o.Essential
	}
	return toSerialize, nil
}

type NullableV1AuthoringStoriesStoryIdExplorationNodesNodeIdPatchRequest struct {
	value *V1AuthoringStoriesStoryIdExplorationNodesNodeIdPatchRequest
	isSet bool
}

func (v NullableV1AuthoringStoriesStoryIdExplorationNodesNodeIdPatchRequest) Get() *V1AuthoringStoriesStoryIdExplorationNodesNodeIdPatchRequest {
	return v.value
}

func (v *NullableV1AuthoringStoriesStoryIdExplorationNodesNodeIdPatchRequest) Set(val *V1AuthoringStoriesStoryIdExplorationNodesNodeIdPatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV1AuthoringStoriesStoryIdExplorationNodesNodeIdPatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV1AuthoringStoriesStoryIdExplorationNodesNodeIdPatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1AuthoringStoriesStoryIdExplorationNodesNodeIdPatchRequest(val *V1AuthoringStoriesStoryIdExplorationNodesNodeIdPatchRequest) *NullableV1AuthoringStoriesStoryIdExplorationNodesNodeIdPatchRequest {
	return &NullableV1AuthoringStoriesStoryIdExplorationNodesNodeIdPatchRequest{value: val, isSet: true}
}

func (v NullableV1AuthoringStoriesStoryIdExplorationNodesNodeIdPatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1AuthoringStoriesStoryIdExplorationNodesNodeIdPatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


