/*
Story Engine API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.13
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package storyteller

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V1AdminStoryStoryIdGet200ResponseCharactersValue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1AdminStoryStoryIdGet200ResponseCharactersValue{}

// V1AdminStoryStoryIdGet200ResponseCharactersValue struct for V1AdminStoryStoryIdGet200ResponseCharactersValue
type V1AdminStoryStoryIdGet200ResponseCharactersValue struct {
	Backstory string `json:"backstory"`
	Motive string `json:"motive"`
	Name string `json:"name"`
	Role string `json:"role"`
	Traits []string `json:"traits"`
	Voice string `json:"voice"`
}

type _V1AdminStoryStoryIdGet200ResponseCharactersValue V1AdminStoryStoryIdGet200ResponseCharactersValue

// NewV1AdminStoryStoryIdGet200ResponseCharactersValue instantiates a new V1AdminStoryStoryIdGet200ResponseCharactersValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1AdminStoryStoryIdGet200ResponseCharactersValue(backstory string, motive string, name string, role string, traits []string, voice string) *V1AdminStoryStoryIdGet200ResponseCharactersValue {
	this := V1AdminStoryStoryIdGet200ResponseCharactersValue{}
	this.Backstory = backstory
	this.Motive = motive
	this.Name = name
	this.Role = role
	this.Traits = traits
	this.Voice = voice
	return &this
}

// NewV1AdminStoryStoryIdGet200ResponseCharactersValueWithDefaults instantiates a new V1AdminStoryStoryIdGet200ResponseCharactersValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1AdminStoryStoryIdGet200ResponseCharactersValueWithDefaults() *V1AdminStoryStoryIdGet200ResponseCharactersValue {
	this := V1AdminStoryStoryIdGet200ResponseCharactersValue{}
	return &this
}

// GetBackstory returns the Backstory field value
func (o *V1AdminStoryStoryIdGet200ResponseCharactersValue) GetBackstory() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Backstory
}

// GetBackstoryOk returns a tuple with the Backstory field value
// and a boolean to check if the value has been set.
func (o *V1AdminStoryStoryIdGet200ResponseCharactersValue) GetBackstoryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Backstory, true
}

// SetBackstory sets field value
func (o *V1AdminStoryStoryIdGet200ResponseCharactersValue) SetBackstory(v string) {
	o.Backstory = v
}

// GetMotive returns the Motive field value
func (o *V1AdminStoryStoryIdGet200ResponseCharactersValue) GetMotive() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Motive
}

// GetMotiveOk returns a tuple with the Motive field value
// and a boolean to check if the value has been set.
func (o *V1AdminStoryStoryIdGet200ResponseCharactersValue) GetMotiveOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Motive, true
}

// SetMotive sets field value
func (o *V1AdminStoryStoryIdGet200ResponseCharactersValue) SetMotive(v string) {
	o.Motive = v
}

// GetName returns the Name field value
func (o *V1AdminStoryStoryIdGet200ResponseCharactersValue) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *V1AdminStoryStoryIdGet200ResponseCharactersValue) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *V1AdminStoryStoryIdGet200ResponseCharactersValue) SetName(v string) {
	o.Name = v
}

// GetRole returns the Role field value
func (o *V1AdminStoryStoryIdGet200ResponseCharactersValue) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *V1AdminStoryStoryIdGet200ResponseCharactersValue) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *V1AdminStoryStoryIdGet200ResponseCharactersValue) SetRole(v string) {
	o.Role = v
}

// GetTraits returns the Traits field value
func (o *V1AdminStoryStoryIdGet200ResponseCharactersValue) GetTraits() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Traits
}

// GetTraitsOk returns a tuple with the Traits field value
// and a boolean to check if the value has been set.
func (o *V1AdminStoryStoryIdGet200ResponseCharactersValue) GetTraitsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Traits, true
}

// SetTraits sets field value
func (o *V1AdminStoryStoryIdGet200ResponseCharactersValue) SetTraits(v []string) {
	o.Traits = v
}

// GetVoice returns the Voice field value
func (o *V1AdminStoryStoryIdGet200ResponseCharactersValue) GetVoice() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Voice
}

// GetVoiceOk returns a tuple with the Voice field value
// and a boolean to check if the value has been set.
func (o *V1AdminStoryStoryIdGet200ResponseCharactersValue) GetVoiceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Voice, true
}

// SetVoice sets field value
func (o *V1AdminStoryStoryIdGet200ResponseCharactersValue) SetVoice(v string) {
	o.Voice = v
}

func (o V1AdminStoryStoryIdGet200ResponseCharactersValue) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1AdminStoryStoryIdGet200ResponseCharactersValue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["backstory"] = o.Backstory
	toSerialize["motive"] = o.Motive
	toSerialize["name"] = o.Name
	toSerialize["role"] = o.Role
	toSerialize["traits"] = o.Traits
	toSerialize["voice"] = o.Voice
	return toSerialize, nil
}

func (o *V1AdminStoryStoryIdGet200ResponseCharactersValue) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"backstory",
		"motive",
		"name",
		"role",
		"traits",
		"voice",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1AdminStoryStoryIdGet200ResponseCharactersValue := _V1AdminStoryStoryIdGet200ResponseCharactersValue{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV1AdminStoryStoryIdGet200ResponseCharactersValue)

	if err != nil {
		return err
	}

	*o = V1AdminStoryStoryIdGet200ResponseCharactersValue(varV1AdminStoryStoryIdGet200ResponseCharactersValue)

	return err
}

type NullableV1AdminStoryStoryIdGet200ResponseCharactersValue struct {
	value *V1AdminStoryStoryIdGet200ResponseCharactersValue
	isSet bool
}

func (v NullableV1AdminStoryStoryIdGet200ResponseCharactersValue) Get() *V1AdminStoryStoryIdGet200ResponseCharactersValue {
	return v.value
}

func (v *NullableV1AdminStoryStoryIdGet200ResponseCharactersValue) Set(val *V1AdminStoryStoryIdGet200ResponseCharactersValue) {
	v.value = val
	v.isSet = true
}

func (v NullableV1AdminStoryStoryIdGet200ResponseCharactersValue) IsSet() bool {
	return v.isSet
}

func (v *NullableV1AdminStoryStoryIdGet200ResponseCharactersValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1AdminStoryStoryIdGet200ResponseCharactersValue(val *V1AdminStoryStoryIdGet200ResponseCharactersValue) *NullableV1AdminStoryStoryIdGet200ResponseCharactersValue {
	return &NullableV1AdminStoryStoryIdGet200ResponseCharactersValue{value: val, isSet: true}
}

func (v NullableV1AdminStoryStoryIdGet200ResponseCharactersValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1AdminStoryStoryIdGet200ResponseCharactersValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


