/*
Story Engine API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.13
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package storyteller

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V1AdminStoryStoryIdNodeNodeIdClearEnrichmentPost200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1AdminStoryStoryIdNodeNodeIdClearEnrichmentPost200Response{}

// V1AdminStoryStoryIdNodeNodeIdClearEnrichmentPost200Response struct for V1AdminStoryStoryIdNodeNodeIdClearEnrichmentPost200Response
type V1AdminStoryStoryIdNodeNodeIdClearEnrichmentPost200Response struct {
	EnrichmentSummary string `json:"enrichment_summary"`
	NodeId string `json:"node_id"`
}

type _V1AdminStoryStoryIdNodeNodeIdClearEnrichmentPost200Response V1AdminStoryStoryIdNodeNodeIdClearEnrichmentPost200Response

// NewV1AdminStoryStoryIdNodeNodeIdClearEnrichmentPost200Response instantiates a new V1AdminStoryStoryIdNodeNodeIdClearEnrichmentPost200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1AdminStoryStoryIdNodeNodeIdClearEnrichmentPost200Response(enrichmentSummary string, nodeId string) *V1AdminStoryStoryIdNodeNodeIdClearEnrichmentPost200Response {
	this := V1AdminStoryStoryIdNodeNodeIdClearEnrichmentPost200Response{}
	this.EnrichmentSummary = enrichmentSummary
	this.NodeId = nodeId
	return &this
}

// NewV1AdminStoryStoryIdNodeNodeIdClearEnrichmentPost200ResponseWithDefaults instantiates a new V1AdminStoryStoryIdNodeNodeIdClearEnrichmentPost200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1AdminStoryStoryIdNodeNodeIdClearEnrichmentPost200ResponseWithDefaults() *V1AdminStoryStoryIdNodeNodeIdClearEnrichmentPost200Response {
	this := V1AdminStoryStoryIdNodeNodeIdClearEnrichmentPost200Response{}
	return &this
}

// GetEnrichmentSummary returns the EnrichmentSummary field value
func (o *V1AdminStoryStoryIdNodeNodeIdClearEnrichmentPost200Response) GetEnrichmentSummary() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EnrichmentSummary
}

// GetEnrichmentSummaryOk returns a tuple with the EnrichmentSummary field value
// and a boolean to check if the value has been set.
func (o *V1AdminStoryStoryIdNodeNodeIdClearEnrichmentPost200Response) GetEnrichmentSummaryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EnrichmentSummary, true
}

// SetEnrichmentSummary sets field value
func (o *V1AdminStoryStoryIdNodeNodeIdClearEnrichmentPost200Response) SetEnrichmentSummary(v string) {
	o.EnrichmentSummary = v
}

// GetNodeId returns the NodeId field value
func (o *V1AdminStoryStoryIdNodeNodeIdClearEnrichmentPost200Response) GetNodeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NodeId
}

// GetNodeIdOk returns a tuple with the NodeId field value
// and a boolean to check if the value has been set.
func (o *V1AdminStoryStoryIdNodeNodeIdClearEnrichmentPost200Response) GetNodeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NodeId, true
}

// SetNodeId sets field value
func (o *V1AdminStoryStoryIdNodeNodeIdClearEnrichmentPost200Response) SetNodeId(v string) {
	o.NodeId = v
}

func (o V1AdminStoryStoryIdNodeNodeIdClearEnrichmentPost200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1AdminStoryStoryIdNodeNodeIdClearEnrichmentPost200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["enrichment_summary"] = o.EnrichmentSummary
	toSerialize["node_id"] = o.NodeId
	return toSerialize, nil
}

func (o *V1AdminStoryStoryIdNodeNodeIdClearEnrichmentPost200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"enrichment_summary",
		"node_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1AdminStoryStoryIdNodeNodeIdClearEnrichmentPost200Response := _V1AdminStoryStoryIdNodeNodeIdClearEnrichmentPost200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV1AdminStoryStoryIdNodeNodeIdClearEnrichmentPost200Response)

	if err != nil {
		return err
	}

	*o = V1AdminStoryStoryIdNodeNodeIdClearEnrichmentPost200Response(varV1AdminStoryStoryIdNodeNodeIdClearEnrichmentPost200Response)

	return err
}

type NullableV1AdminStoryStoryIdNodeNodeIdClearEnrichmentPost200Response struct {
	value *V1AdminStoryStoryIdNodeNodeIdClearEnrichmentPost200Response
	isSet bool
}

func (v NullableV1AdminStoryStoryIdNodeNodeIdClearEnrichmentPost200Response) Get() *V1AdminStoryStoryIdNodeNodeIdClearEnrichmentPost200Response {
	return v.value
}

func (v *NullableV1AdminStoryStoryIdNodeNodeIdClearEnrichmentPost200Response) Set(val *V1AdminStoryStoryIdNodeNodeIdClearEnrichmentPost200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableV1AdminStoryStoryIdNodeNodeIdClearEnrichmentPost200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableV1AdminStoryStoryIdNodeNodeIdClearEnrichmentPost200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1AdminStoryStoryIdNodeNodeIdClearEnrichmentPost200Response(val *V1AdminStoryStoryIdNodeNodeIdClearEnrichmentPost200Response) *NullableV1AdminStoryStoryIdNodeNodeIdClearEnrichmentPost200Response {
	return &NullableV1AdminStoryStoryIdNodeNodeIdClearEnrichmentPost200Response{value: val, isSet: true}
}

func (v NullableV1AdminStoryStoryIdNodeNodeIdClearEnrichmentPost200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1AdminStoryStoryIdNodeNodeIdClearEnrichmentPost200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


