/*
Story Engine API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.12
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package storyteller

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FreeTextRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FreeTextRequest{}

// FreeTextRequest Request body for POST /story/{story_id}/free-text (LLM pipeline, SSE response).
type FreeTextRequest struct {
	NodeId string `json:"node_id"`
	FreeText string `json:"free_text"`
	IdempotencyKey string `json:"idempotency_key"`
	LockToken NullableString `json:"lock_token,omitempty"`
}

type _FreeTextRequest FreeTextRequest

// NewFreeTextRequest instantiates a new FreeTextRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFreeTextRequest(nodeId string, freeText string, idempotencyKey string) *FreeTextRequest {
	this := FreeTextRequest{}
	this.NodeId = nodeId
	this.FreeText = freeText
	this.IdempotencyKey = idempotencyKey
	return &this
}

// NewFreeTextRequestWithDefaults instantiates a new FreeTextRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFreeTextRequestWithDefaults() *FreeTextRequest {
	this := FreeTextRequest{}
	return &this
}

// GetNodeId returns the NodeId field value
func (o *FreeTextRequest) GetNodeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NodeId
}

// GetNodeIdOk returns a tuple with the NodeId field value
// and a boolean to check if the value has been set.
func (o *FreeTextRequest) GetNodeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NodeId, true
}

// SetNodeId sets field value
func (o *FreeTextRequest) SetNodeId(v string) {
	o.NodeId = v
}

// GetFreeText returns the FreeText field value
func (o *FreeTextRequest) GetFreeText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FreeText
}

// GetFreeTextOk returns a tuple with the FreeText field value
// and a boolean to check if the value has been set.
func (o *FreeTextRequest) GetFreeTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FreeText, true
}

// SetFreeText sets field value
func (o *FreeTextRequest) SetFreeText(v string) {
	o.FreeText = v
}

// GetIdempotencyKey returns the IdempotencyKey field value
func (o *FreeTextRequest) GetIdempotencyKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IdempotencyKey
}

// GetIdempotencyKeyOk returns a tuple with the IdempotencyKey field value
// and a boolean to check if the value has been set.
func (o *FreeTextRequest) GetIdempotencyKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IdempotencyKey, true
}

// SetIdempotencyKey sets field value
func (o *FreeTextRequest) SetIdempotencyKey(v string) {
	o.IdempotencyKey = v
}

// GetLockToken returns the LockToken field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FreeTextRequest) GetLockToken() string {
	if o == nil || IsNil(o.LockToken.Get()) {
		var ret string
		return ret
	}
	return *o.LockToken.Get()
}

// GetLockTokenOk returns a tuple with the LockToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FreeTextRequest) GetLockTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LockToken.Get(), o.LockToken.IsSet()
}

// HasLockToken returns a boolean if a field has been set.
func (o *FreeTextRequest) HasLockToken() bool {
	if o != nil && o.LockToken.IsSet() {
		return true
	}

	return false
}

// SetLockToken gets a reference to the given NullableString and assigns it to the LockToken field.
func (o *FreeTextRequest) SetLockToken(v string) {
	o.LockToken.Set(&v)
}
// SetLockTokenNil sets the value for LockToken to be an explicit nil
func (o *FreeTextRequest) SetLockTokenNil() {
	o.LockToken.Set(nil)
}

// UnsetLockToken ensures that no value is present for LockToken, not even an explicit nil
func (o *FreeTextRequest) UnsetLockToken() {
	o.LockToken.Unset()
}

func (o FreeTextRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FreeTextRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["node_id"] = o.NodeId
	toSerialize["free_text"] = o.FreeText
	toSerialize["idempotency_key"] = o.IdempotencyKey
	if o.LockToken.IsSet() {
		toSerialize["lock_token"] = o.LockToken.Get()
	}
	return toSerialize, nil
}

func (o *FreeTextRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"node_id",
		"free_text",
		"idempotency_key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFreeTextRequest := _FreeTextRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFreeTextRequest)

	if err != nil {
		return err
	}

	*o = FreeTextRequest(varFreeTextRequest)

	return err
}

type NullableFreeTextRequest struct {
	value *FreeTextRequest
	isSet bool
}

func (v NullableFreeTextRequest) Get() *FreeTextRequest {
	return v.value
}

func (v *NullableFreeTextRequest) Set(val *FreeTextRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableFreeTextRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableFreeTextRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFreeTextRequest(val *FreeTextRequest) *NullableFreeTextRequest {
	return &NullableFreeTextRequest{value: val, isSet: true}
}

func (v NullableFreeTextRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFreeTextRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


