/*
Story Engine API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.13
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package storyteller

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V1PlayerPlayerIdDataExportGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1PlayerPlayerIdDataExportGet200Response{}

// V1PlayerPlayerIdDataExportGet200Response struct for V1PlayerPlayerIdDataExportGet200Response
type V1PlayerPlayerIdDataExportGet200Response struct {
	EntityProvenance []map[string]interface{} `json:"entity_provenance"`
	Exploration map[string]map[string]interface{} `json:"exploration"`
	GeneratedAt string `json:"generated_at"`
	PlayerId string `json:"player_id"`
	Sessions []map[string]interface{} `json:"sessions"`
	StoryEvents []map[string]interface{} `json:"story_events"`
	TenantId string `json:"tenant_id"`
	TosAcceptances []map[string]interface{} `json:"tos_acceptances"`
}

type _V1PlayerPlayerIdDataExportGet200Response V1PlayerPlayerIdDataExportGet200Response

// NewV1PlayerPlayerIdDataExportGet200Response instantiates a new V1PlayerPlayerIdDataExportGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1PlayerPlayerIdDataExportGet200Response(entityProvenance []map[string]interface{}, exploration map[string]map[string]interface{}, generatedAt string, playerId string, sessions []map[string]interface{}, storyEvents []map[string]interface{}, tenantId string, tosAcceptances []map[string]interface{}) *V1PlayerPlayerIdDataExportGet200Response {
	this := V1PlayerPlayerIdDataExportGet200Response{}
	this.EntityProvenance = entityProvenance
	this.Exploration = exploration
	this.GeneratedAt = generatedAt
	this.PlayerId = playerId
	this.Sessions = sessions
	this.StoryEvents = storyEvents
	this.TenantId = tenantId
	this.TosAcceptances = tosAcceptances
	return &this
}

// NewV1PlayerPlayerIdDataExportGet200ResponseWithDefaults instantiates a new V1PlayerPlayerIdDataExportGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1PlayerPlayerIdDataExportGet200ResponseWithDefaults() *V1PlayerPlayerIdDataExportGet200Response {
	this := V1PlayerPlayerIdDataExportGet200Response{}
	return &this
}

// GetEntityProvenance returns the EntityProvenance field value
func (o *V1PlayerPlayerIdDataExportGet200Response) GetEntityProvenance() []map[string]interface{} {
	if o == nil {
		var ret []map[string]interface{}
		return ret
	}

	return o.EntityProvenance
}

// GetEntityProvenanceOk returns a tuple with the EntityProvenance field value
// and a boolean to check if the value has been set.
func (o *V1PlayerPlayerIdDataExportGet200Response) GetEntityProvenanceOk() ([]map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.EntityProvenance, true
}

// SetEntityProvenance sets field value
func (o *V1PlayerPlayerIdDataExportGet200Response) SetEntityProvenance(v []map[string]interface{}) {
	o.EntityProvenance = v
}

// GetExploration returns the Exploration field value
func (o *V1PlayerPlayerIdDataExportGet200Response) GetExploration() map[string]map[string]interface{} {
	if o == nil {
		var ret map[string]map[string]interface{}
		return ret
	}

	return o.Exploration
}

// GetExplorationOk returns a tuple with the Exploration field value
// and a boolean to check if the value has been set.
func (o *V1PlayerPlayerIdDataExportGet200Response) GetExplorationOk() (map[string]map[string]interface{}, bool) {
	if o == nil {
		return map[string]map[string]interface{}{}, false
	}
	return o.Exploration, true
}

// SetExploration sets field value
func (o *V1PlayerPlayerIdDataExportGet200Response) SetExploration(v map[string]map[string]interface{}) {
	o.Exploration = v
}

// GetGeneratedAt returns the GeneratedAt field value
func (o *V1PlayerPlayerIdDataExportGet200Response) GetGeneratedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GeneratedAt
}

// GetGeneratedAtOk returns a tuple with the GeneratedAt field value
// and a boolean to check if the value has been set.
func (o *V1PlayerPlayerIdDataExportGet200Response) GetGeneratedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GeneratedAt, true
}

// SetGeneratedAt sets field value
func (o *V1PlayerPlayerIdDataExportGet200Response) SetGeneratedAt(v string) {
	o.GeneratedAt = v
}

// GetPlayerId returns the PlayerId field value
func (o *V1PlayerPlayerIdDataExportGet200Response) GetPlayerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PlayerId
}

// GetPlayerIdOk returns a tuple with the PlayerId field value
// and a boolean to check if the value has been set.
func (o *V1PlayerPlayerIdDataExportGet200Response) GetPlayerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlayerId, true
}

// SetPlayerId sets field value
func (o *V1PlayerPlayerIdDataExportGet200Response) SetPlayerId(v string) {
	o.PlayerId = v
}

// GetSessions returns the Sessions field value
func (o *V1PlayerPlayerIdDataExportGet200Response) GetSessions() []map[string]interface{} {
	if o == nil {
		var ret []map[string]interface{}
		return ret
	}

	return o.Sessions
}

// GetSessionsOk returns a tuple with the Sessions field value
// and a boolean to check if the value has been set.
func (o *V1PlayerPlayerIdDataExportGet200Response) GetSessionsOk() ([]map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.Sessions, true
}

// SetSessions sets field value
func (o *V1PlayerPlayerIdDataExportGet200Response) SetSessions(v []map[string]interface{}) {
	o.Sessions = v
}

// GetStoryEvents returns the StoryEvents field value
func (o *V1PlayerPlayerIdDataExportGet200Response) GetStoryEvents() []map[string]interface{} {
	if o == nil {
		var ret []map[string]interface{}
		return ret
	}

	return o.StoryEvents
}

// GetStoryEventsOk returns a tuple with the StoryEvents field value
// and a boolean to check if the value has been set.
func (o *V1PlayerPlayerIdDataExportGet200Response) GetStoryEventsOk() ([]map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.StoryEvents, true
}

// SetStoryEvents sets field value
func (o *V1PlayerPlayerIdDataExportGet200Response) SetStoryEvents(v []map[string]interface{}) {
	o.StoryEvents = v
}

// GetTenantId returns the TenantId field value
func (o *V1PlayerPlayerIdDataExportGet200Response) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *V1PlayerPlayerIdDataExportGet200Response) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *V1PlayerPlayerIdDataExportGet200Response) SetTenantId(v string) {
	o.TenantId = v
}

// GetTosAcceptances returns the TosAcceptances field value
func (o *V1PlayerPlayerIdDataExportGet200Response) GetTosAcceptances() []map[string]interface{} {
	if o == nil {
		var ret []map[string]interface{}
		return ret
	}

	return o.TosAcceptances
}

// GetTosAcceptancesOk returns a tuple with the TosAcceptances field value
// and a boolean to check if the value has been set.
func (o *V1PlayerPlayerIdDataExportGet200Response) GetTosAcceptancesOk() ([]map[string]interface{}, bool) {
	if o == nil {
		return nil, false
	}
	return o.TosAcceptances, true
}

// SetTosAcceptances sets field value
func (o *V1PlayerPlayerIdDataExportGet200Response) SetTosAcceptances(v []map[string]interface{}) {
	o.TosAcceptances = v
}

func (o V1PlayerPlayerIdDataExportGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1PlayerPlayerIdDataExportGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["entity_provenance"] = o.EntityProvenance
	toSerialize["exploration"] = o.Exploration
	toSerialize["generated_at"] = o.GeneratedAt
	toSerialize["player_id"] = o.PlayerId
	toSerialize["sessions"] = o.Sessions
	toSerialize["story_events"] = o.StoryEvents
	toSerialize["tenant_id"] = o.TenantId
	toSerialize["tos_acceptances"] = o.TosAcceptances
	return toSerialize, nil
}

func (o *V1PlayerPlayerIdDataExportGet200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"entity_provenance",
		"exploration",
		"generated_at",
		"player_id",
		"sessions",
		"story_events",
		"tenant_id",
		"tos_acceptances",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1PlayerPlayerIdDataExportGet200Response := _V1PlayerPlayerIdDataExportGet200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV1PlayerPlayerIdDataExportGet200Response)

	if err != nil {
		return err
	}

	*o = V1PlayerPlayerIdDataExportGet200Response(varV1PlayerPlayerIdDataExportGet200Response)

	return err
}

type NullableV1PlayerPlayerIdDataExportGet200Response struct {
	value *V1PlayerPlayerIdDataExportGet200Response
	isSet bool
}

func (v NullableV1PlayerPlayerIdDataExportGet200Response) Get() *V1PlayerPlayerIdDataExportGet200Response {
	return v.value
}

func (v *NullableV1PlayerPlayerIdDataExportGet200Response) Set(val *V1PlayerPlayerIdDataExportGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableV1PlayerPlayerIdDataExportGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableV1PlayerPlayerIdDataExportGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1PlayerPlayerIdDataExportGet200Response(val *V1PlayerPlayerIdDataExportGet200Response) *NullableV1PlayerPlayerIdDataExportGet200Response {
	return &NullableV1PlayerPlayerIdDataExportGet200Response{value: val, isSet: true}
}

func (v NullableV1PlayerPlayerIdDataExportGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1PlayerPlayerIdDataExportGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


