/*
Story Engine API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.12
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package storyteller

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TenantResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TenantResponse{}

// TenantResponse Read-only tenant summary returned by GET /admin/tenants/{id}.
type TenantResponse struct {
	TenantId string `json:"tenant_id"`
	Name string `json:"name"`
	ContactEmail string `json:"contact_email"`
	BillingCountry string `json:"billing_country"`
	MaxAgeRating string `json:"max_age_rating"`
	Tier string `json:"tier"`
	Status string `json:"status"`
	CreatedAt string `json:"created_at"`
}

type _TenantResponse TenantResponse

// NewTenantResponse instantiates a new TenantResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTenantResponse(tenantId string, name string, contactEmail string, billingCountry string, maxAgeRating string, tier string, status string, createdAt string) *TenantResponse {
	this := TenantResponse{}
	this.TenantId = tenantId
	this.Name = name
	this.ContactEmail = contactEmail
	this.BillingCountry = billingCountry
	this.MaxAgeRating = maxAgeRating
	this.Tier = tier
	this.Status = status
	this.CreatedAt = createdAt
	return &this
}

// NewTenantResponseWithDefaults instantiates a new TenantResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTenantResponseWithDefaults() *TenantResponse {
	this := TenantResponse{}
	return &this
}

// GetTenantId returns the TenantId field value
func (o *TenantResponse) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *TenantResponse) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *TenantResponse) SetTenantId(v string) {
	o.TenantId = v
}

// GetName returns the Name field value
func (o *TenantResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *TenantResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *TenantResponse) SetName(v string) {
	o.Name = v
}

// GetContactEmail returns the ContactEmail field value
func (o *TenantResponse) GetContactEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContactEmail
}

// GetContactEmailOk returns a tuple with the ContactEmail field value
// and a boolean to check if the value has been set.
func (o *TenantResponse) GetContactEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContactEmail, true
}

// SetContactEmail sets field value
func (o *TenantResponse) SetContactEmail(v string) {
	o.ContactEmail = v
}

// GetBillingCountry returns the BillingCountry field value
func (o *TenantResponse) GetBillingCountry() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BillingCountry
}

// GetBillingCountryOk returns a tuple with the BillingCountry field value
// and a boolean to check if the value has been set.
func (o *TenantResponse) GetBillingCountryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BillingCountry, true
}

// SetBillingCountry sets field value
func (o *TenantResponse) SetBillingCountry(v string) {
	o.BillingCountry = v
}

// GetMaxAgeRating returns the MaxAgeRating field value
func (o *TenantResponse) GetMaxAgeRating() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MaxAgeRating
}

// GetMaxAgeRatingOk returns a tuple with the MaxAgeRating field value
// and a boolean to check if the value has been set.
func (o *TenantResponse) GetMaxAgeRatingOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MaxAgeRating, true
}

// SetMaxAgeRating sets field value
func (o *TenantResponse) SetMaxAgeRating(v string) {
	o.MaxAgeRating = v
}

// GetTier returns the Tier field value
func (o *TenantResponse) GetTier() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Tier
}

// GetTierOk returns a tuple with the Tier field value
// and a boolean to check if the value has been set.
func (o *TenantResponse) GetTierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tier, true
}

// SetTier sets field value
func (o *TenantResponse) SetTier(v string) {
	o.Tier = v
}

// GetStatus returns the Status field value
func (o *TenantResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *TenantResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *TenantResponse) SetStatus(v string) {
	o.Status = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *TenantResponse) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *TenantResponse) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *TenantResponse) SetCreatedAt(v string) {
	o.CreatedAt = v
}

func (o TenantResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TenantResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tenant_id"] = o.TenantId
	toSerialize["name"] = o.Name
	toSerialize["contact_email"] = o.ContactEmail
	toSerialize["billing_country"] = o.BillingCountry
	toSerialize["max_age_rating"] = o.MaxAgeRating
	toSerialize["tier"] = o.Tier
	toSerialize["status"] = o.Status
	toSerialize["created_at"] = o.CreatedAt
	return toSerialize, nil
}

func (o *TenantResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tenant_id",
		"name",
		"contact_email",
		"billing_country",
		"max_age_rating",
		"tier",
		"status",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTenantResponse := _TenantResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTenantResponse)

	if err != nil {
		return err
	}

	*o = TenantResponse(varTenantResponse)

	return err
}

type NullableTenantResponse struct {
	value *TenantResponse
	isSet bool
}

func (v NullableTenantResponse) Get() *TenantResponse {
	return v.value
}

func (v *NullableTenantResponse) Set(val *TenantResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTenantResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTenantResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTenantResponse(val *TenantResponse) *NullableTenantResponse {
	return &NullableTenantResponse{value: val, isSet: true}
}

func (v NullableTenantResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTenantResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


