/*
Story Engine API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.13
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package storyteller

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V1StoryStoryIdExplorePost200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1StoryStoryIdExplorePost200Response{}

// V1StoryStoryIdExplorePost200Response struct for V1StoryStoryIdExplorePost200Response
type V1StoryStoryIdExplorePost200Response struct {
	Answer string `json:"answer"`
	CacheHit bool `json:"cache_hit"`
	CacheSource *string `json:"cache_source,omitempty"`
	CanonicalDetailVersion *int32 `json:"canonical_detail_version,omitempty"`
	Confidence string `json:"confidence"`
	CurrentNodeIdAfter *string `json:"current_node_id_after,omitempty"`
	CurrentNodeIdBefore *string `json:"current_node_id_before,omitempty"`
	DetailDelta map[string]map[string]interface{} `json:"detail_delta"`
	ExplorationNodeId *string `json:"exploration_node_id,omitempty"`
	ExplorationTurnId *string `json:"exploration_turn_id,omitempty"`
	FormalizedText *string `json:"formalized_text,omitempty"`
	HiddenInfoRequested bool `json:"hidden_info_requested"`
	IdempotencyReplay bool `json:"idempotency_replay"`
	NodeId *string `json:"node_id,omitempty"`
	OverlayVersion *int32 `json:"overlay_version,omitempty"`
	RedirectReason *string `json:"redirect_reason,omitempty"`
	RequiresAction bool `json:"requires_action"`
}

type _V1StoryStoryIdExplorePost200Response V1StoryStoryIdExplorePost200Response

// NewV1StoryStoryIdExplorePost200Response instantiates a new V1StoryStoryIdExplorePost200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1StoryStoryIdExplorePost200Response(answer string, cacheHit bool, confidence string, detailDelta map[string]map[string]interface{}, hiddenInfoRequested bool, idempotencyReplay bool, requiresAction bool) *V1StoryStoryIdExplorePost200Response {
	this := V1StoryStoryIdExplorePost200Response{}
	this.Answer = answer
	this.CacheHit = cacheHit
	this.Confidence = confidence
	this.DetailDelta = detailDelta
	this.HiddenInfoRequested = hiddenInfoRequested
	this.IdempotencyReplay = idempotencyReplay
	this.RequiresAction = requiresAction
	return &this
}

// NewV1StoryStoryIdExplorePost200ResponseWithDefaults instantiates a new V1StoryStoryIdExplorePost200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1StoryStoryIdExplorePost200ResponseWithDefaults() *V1StoryStoryIdExplorePost200Response {
	this := V1StoryStoryIdExplorePost200Response{}
	return &this
}

// GetAnswer returns the Answer field value
func (o *V1StoryStoryIdExplorePost200Response) GetAnswer() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Answer
}

// GetAnswerOk returns a tuple with the Answer field value
// and a boolean to check if the value has been set.
func (o *V1StoryStoryIdExplorePost200Response) GetAnswerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Answer, true
}

// SetAnswer sets field value
func (o *V1StoryStoryIdExplorePost200Response) SetAnswer(v string) {
	o.Answer = v
}

// GetCacheHit returns the CacheHit field value
func (o *V1StoryStoryIdExplorePost200Response) GetCacheHit() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.CacheHit
}

// GetCacheHitOk returns a tuple with the CacheHit field value
// and a boolean to check if the value has been set.
func (o *V1StoryStoryIdExplorePost200Response) GetCacheHitOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CacheHit, true
}

// SetCacheHit sets field value
func (o *V1StoryStoryIdExplorePost200Response) SetCacheHit(v bool) {
	o.CacheHit = v
}

// GetCacheSource returns the CacheSource field value if set, zero value otherwise.
func (o *V1StoryStoryIdExplorePost200Response) GetCacheSource() string {
	if o == nil || IsNil(o.CacheSource) {
		var ret string
		return ret
	}
	return *o.CacheSource
}

// GetCacheSourceOk returns a tuple with the CacheSource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1StoryStoryIdExplorePost200Response) GetCacheSourceOk() (*string, bool) {
	if o == nil || IsNil(o.CacheSource) {
		return nil, false
	}
	return o.CacheSource, true
}

// HasCacheSource returns a boolean if a field has been set.
func (o *V1StoryStoryIdExplorePost200Response) HasCacheSource() bool {
	if o != nil && !IsNil(o.CacheSource) {
		return true
	}

	return false
}

// SetCacheSource gets a reference to the given string and assigns it to the CacheSource field.
func (o *V1StoryStoryIdExplorePost200Response) SetCacheSource(v string) {
	o.CacheSource = &v
}

// GetCanonicalDetailVersion returns the CanonicalDetailVersion field value if set, zero value otherwise.
func (o *V1StoryStoryIdExplorePost200Response) GetCanonicalDetailVersion() int32 {
	if o == nil || IsNil(o.CanonicalDetailVersion) {
		var ret int32
		return ret
	}
	return *o.CanonicalDetailVersion
}

// GetCanonicalDetailVersionOk returns a tuple with the CanonicalDetailVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1StoryStoryIdExplorePost200Response) GetCanonicalDetailVersionOk() (*int32, bool) {
	if o == nil || IsNil(o.CanonicalDetailVersion) {
		return nil, false
	}
	return o.CanonicalDetailVersion, true
}

// HasCanonicalDetailVersion returns a boolean if a field has been set.
func (o *V1StoryStoryIdExplorePost200Response) HasCanonicalDetailVersion() bool {
	if o != nil && !IsNil(o.CanonicalDetailVersion) {
		return true
	}

	return false
}

// SetCanonicalDetailVersion gets a reference to the given int32 and assigns it to the CanonicalDetailVersion field.
func (o *V1StoryStoryIdExplorePost200Response) SetCanonicalDetailVersion(v int32) {
	o.CanonicalDetailVersion = &v
}

// GetConfidence returns the Confidence field value
func (o *V1StoryStoryIdExplorePost200Response) GetConfidence() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Confidence
}

// GetConfidenceOk returns a tuple with the Confidence field value
// and a boolean to check if the value has been set.
func (o *V1StoryStoryIdExplorePost200Response) GetConfidenceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Confidence, true
}

// SetConfidence sets field value
func (o *V1StoryStoryIdExplorePost200Response) SetConfidence(v string) {
	o.Confidence = v
}

// GetCurrentNodeIdAfter returns the CurrentNodeIdAfter field value if set, zero value otherwise.
func (o *V1StoryStoryIdExplorePost200Response) GetCurrentNodeIdAfter() string {
	if o == nil || IsNil(o.CurrentNodeIdAfter) {
		var ret string
		return ret
	}
	return *o.CurrentNodeIdAfter
}

// GetCurrentNodeIdAfterOk returns a tuple with the CurrentNodeIdAfter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1StoryStoryIdExplorePost200Response) GetCurrentNodeIdAfterOk() (*string, bool) {
	if o == nil || IsNil(o.CurrentNodeIdAfter) {
		return nil, false
	}
	return o.CurrentNodeIdAfter, true
}

// HasCurrentNodeIdAfter returns a boolean if a field has been set.
func (o *V1StoryStoryIdExplorePost200Response) HasCurrentNodeIdAfter() bool {
	if o != nil && !IsNil(o.CurrentNodeIdAfter) {
		return true
	}

	return false
}

// SetCurrentNodeIdAfter gets a reference to the given string and assigns it to the CurrentNodeIdAfter field.
func (o *V1StoryStoryIdExplorePost200Response) SetCurrentNodeIdAfter(v string) {
	o.CurrentNodeIdAfter = &v
}

// GetCurrentNodeIdBefore returns the CurrentNodeIdBefore field value if set, zero value otherwise.
func (o *V1StoryStoryIdExplorePost200Response) GetCurrentNodeIdBefore() string {
	if o == nil || IsNil(o.CurrentNodeIdBefore) {
		var ret string
		return ret
	}
	return *o.CurrentNodeIdBefore
}

// GetCurrentNodeIdBeforeOk returns a tuple with the CurrentNodeIdBefore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1StoryStoryIdExplorePost200Response) GetCurrentNodeIdBeforeOk() (*string, bool) {
	if o == nil || IsNil(o.CurrentNodeIdBefore) {
		return nil, false
	}
	return o.CurrentNodeIdBefore, true
}

// HasCurrentNodeIdBefore returns a boolean if a field has been set.
func (o *V1StoryStoryIdExplorePost200Response) HasCurrentNodeIdBefore() bool {
	if o != nil && !IsNil(o.CurrentNodeIdBefore) {
		return true
	}

	return false
}

// SetCurrentNodeIdBefore gets a reference to the given string and assigns it to the CurrentNodeIdBefore field.
func (o *V1StoryStoryIdExplorePost200Response) SetCurrentNodeIdBefore(v string) {
	o.CurrentNodeIdBefore = &v
}

// GetDetailDelta returns the DetailDelta field value
func (o *V1StoryStoryIdExplorePost200Response) GetDetailDelta() map[string]map[string]interface{} {
	if o == nil {
		var ret map[string]map[string]interface{}
		return ret
	}

	return o.DetailDelta
}

// GetDetailDeltaOk returns a tuple with the DetailDelta field value
// and a boolean to check if the value has been set.
func (o *V1StoryStoryIdExplorePost200Response) GetDetailDeltaOk() (map[string]map[string]interface{}, bool) {
	if o == nil {
		return map[string]map[string]interface{}{}, false
	}
	return o.DetailDelta, true
}

// SetDetailDelta sets field value
func (o *V1StoryStoryIdExplorePost200Response) SetDetailDelta(v map[string]map[string]interface{}) {
	o.DetailDelta = v
}

// GetExplorationNodeId returns the ExplorationNodeId field value if set, zero value otherwise.
func (o *V1StoryStoryIdExplorePost200Response) GetExplorationNodeId() string {
	if o == nil || IsNil(o.ExplorationNodeId) {
		var ret string
		return ret
	}
	return *o.ExplorationNodeId
}

// GetExplorationNodeIdOk returns a tuple with the ExplorationNodeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1StoryStoryIdExplorePost200Response) GetExplorationNodeIdOk() (*string, bool) {
	if o == nil || IsNil(o.ExplorationNodeId) {
		return nil, false
	}
	return o.ExplorationNodeId, true
}

// HasExplorationNodeId returns a boolean if a field has been set.
func (o *V1StoryStoryIdExplorePost200Response) HasExplorationNodeId() bool {
	if o != nil && !IsNil(o.ExplorationNodeId) {
		return true
	}

	return false
}

// SetExplorationNodeId gets a reference to the given string and assigns it to the ExplorationNodeId field.
func (o *V1StoryStoryIdExplorePost200Response) SetExplorationNodeId(v string) {
	o.ExplorationNodeId = &v
}

// GetExplorationTurnId returns the ExplorationTurnId field value if set, zero value otherwise.
func (o *V1StoryStoryIdExplorePost200Response) GetExplorationTurnId() string {
	if o == nil || IsNil(o.ExplorationTurnId) {
		var ret string
		return ret
	}
	return *o.ExplorationTurnId
}

// GetExplorationTurnIdOk returns a tuple with the ExplorationTurnId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1StoryStoryIdExplorePost200Response) GetExplorationTurnIdOk() (*string, bool) {
	if o == nil || IsNil(o.ExplorationTurnId) {
		return nil, false
	}
	return o.ExplorationTurnId, true
}

// HasExplorationTurnId returns a boolean if a field has been set.
func (o *V1StoryStoryIdExplorePost200Response) HasExplorationTurnId() bool {
	if o != nil && !IsNil(o.ExplorationTurnId) {
		return true
	}

	return false
}

// SetExplorationTurnId gets a reference to the given string and assigns it to the ExplorationTurnId field.
func (o *V1StoryStoryIdExplorePost200Response) SetExplorationTurnId(v string) {
	o.ExplorationTurnId = &v
}

// GetFormalizedText returns the FormalizedText field value if set, zero value otherwise.
func (o *V1StoryStoryIdExplorePost200Response) GetFormalizedText() string {
	if o == nil || IsNil(o.FormalizedText) {
		var ret string
		return ret
	}
	return *o.FormalizedText
}

// GetFormalizedTextOk returns a tuple with the FormalizedText field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1StoryStoryIdExplorePost200Response) GetFormalizedTextOk() (*string, bool) {
	if o == nil || IsNil(o.FormalizedText) {
		return nil, false
	}
	return o.FormalizedText, true
}

// HasFormalizedText returns a boolean if a field has been set.
func (o *V1StoryStoryIdExplorePost200Response) HasFormalizedText() bool {
	if o != nil && !IsNil(o.FormalizedText) {
		return true
	}

	return false
}

// SetFormalizedText gets a reference to the given string and assigns it to the FormalizedText field.
func (o *V1StoryStoryIdExplorePost200Response) SetFormalizedText(v string) {
	o.FormalizedText = &v
}

// GetHiddenInfoRequested returns the HiddenInfoRequested field value
func (o *V1StoryStoryIdExplorePost200Response) GetHiddenInfoRequested() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HiddenInfoRequested
}

// GetHiddenInfoRequestedOk returns a tuple with the HiddenInfoRequested field value
// and a boolean to check if the value has been set.
func (o *V1StoryStoryIdExplorePost200Response) GetHiddenInfoRequestedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HiddenInfoRequested, true
}

// SetHiddenInfoRequested sets field value
func (o *V1StoryStoryIdExplorePost200Response) SetHiddenInfoRequested(v bool) {
	o.HiddenInfoRequested = v
}

// GetIdempotencyReplay returns the IdempotencyReplay field value
func (o *V1StoryStoryIdExplorePost200Response) GetIdempotencyReplay() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IdempotencyReplay
}

// GetIdempotencyReplayOk returns a tuple with the IdempotencyReplay field value
// and a boolean to check if the value has been set.
func (o *V1StoryStoryIdExplorePost200Response) GetIdempotencyReplayOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IdempotencyReplay, true
}

// SetIdempotencyReplay sets field value
func (o *V1StoryStoryIdExplorePost200Response) SetIdempotencyReplay(v bool) {
	o.IdempotencyReplay = v
}

// GetNodeId returns the NodeId field value if set, zero value otherwise.
func (o *V1StoryStoryIdExplorePost200Response) GetNodeId() string {
	if o == nil || IsNil(o.NodeId) {
		var ret string
		return ret
	}
	return *o.NodeId
}

// GetNodeIdOk returns a tuple with the NodeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1StoryStoryIdExplorePost200Response) GetNodeIdOk() (*string, bool) {
	if o == nil || IsNil(o.NodeId) {
		return nil, false
	}
	return o.NodeId, true
}

// HasNodeId returns a boolean if a field has been set.
func (o *V1StoryStoryIdExplorePost200Response) HasNodeId() bool {
	if o != nil && !IsNil(o.NodeId) {
		return true
	}

	return false
}

// SetNodeId gets a reference to the given string and assigns it to the NodeId field.
func (o *V1StoryStoryIdExplorePost200Response) SetNodeId(v string) {
	o.NodeId = &v
}

// GetOverlayVersion returns the OverlayVersion field value if set, zero value otherwise.
func (o *V1StoryStoryIdExplorePost200Response) GetOverlayVersion() int32 {
	if o == nil || IsNil(o.OverlayVersion) {
		var ret int32
		return ret
	}
	return *o.OverlayVersion
}

// GetOverlayVersionOk returns a tuple with the OverlayVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1StoryStoryIdExplorePost200Response) GetOverlayVersionOk() (*int32, bool) {
	if o == nil || IsNil(o.OverlayVersion) {
		return nil, false
	}
	return o.OverlayVersion, true
}

// HasOverlayVersion returns a boolean if a field has been set.
func (o *V1StoryStoryIdExplorePost200Response) HasOverlayVersion() bool {
	if o != nil && !IsNil(o.OverlayVersion) {
		return true
	}

	return false
}

// SetOverlayVersion gets a reference to the given int32 and assigns it to the OverlayVersion field.
func (o *V1StoryStoryIdExplorePost200Response) SetOverlayVersion(v int32) {
	o.OverlayVersion = &v
}

// GetRedirectReason returns the RedirectReason field value if set, zero value otherwise.
func (o *V1StoryStoryIdExplorePost200Response) GetRedirectReason() string {
	if o == nil || IsNil(o.RedirectReason) {
		var ret string
		return ret
	}
	return *o.RedirectReason
}

// GetRedirectReasonOk returns a tuple with the RedirectReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1StoryStoryIdExplorePost200Response) GetRedirectReasonOk() (*string, bool) {
	if o == nil || IsNil(o.RedirectReason) {
		return nil, false
	}
	return o.RedirectReason, true
}

// HasRedirectReason returns a boolean if a field has been set.
func (o *V1StoryStoryIdExplorePost200Response) HasRedirectReason() bool {
	if o != nil && !IsNil(o.RedirectReason) {
		return true
	}

	return false
}

// SetRedirectReason gets a reference to the given string and assigns it to the RedirectReason field.
func (o *V1StoryStoryIdExplorePost200Response) SetRedirectReason(v string) {
	o.RedirectReason = &v
}

// GetRequiresAction returns the RequiresAction field value
func (o *V1StoryStoryIdExplorePost200Response) GetRequiresAction() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.RequiresAction
}

// GetRequiresActionOk returns a tuple with the RequiresAction field value
// and a boolean to check if the value has been set.
func (o *V1StoryStoryIdExplorePost200Response) GetRequiresActionOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequiresAction, true
}

// SetRequiresAction sets field value
func (o *V1StoryStoryIdExplorePost200Response) SetRequiresAction(v bool) {
	o.RequiresAction = v
}

func (o V1StoryStoryIdExplorePost200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1StoryStoryIdExplorePost200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["answer"] = o.Answer
	toSerialize["cache_hit"] = o.CacheHit
	if !IsNil(o.CacheSource) {
		toSerialize["cache_source"] = o.CacheSource
	}
	if !IsNil(o.CanonicalDetailVersion) {
		toSerialize["canonical_detail_version"] = o.CanonicalDetailVersion
	}
	toSerialize["confidence"] = o.Confidence
	if !IsNil(o.CurrentNodeIdAfter) {
		toSerialize["current_node_id_after"] = o.CurrentNodeIdAfter
	}
	if !IsNil(o.CurrentNodeIdBefore) {
		toSerialize["current_node_id_before"] = o.CurrentNodeIdBefore
	}
	toSerialize["detail_delta"] = o.DetailDelta
	if !IsNil(o.ExplorationNodeId) {
		toSerialize["exploration_node_id"] = o.ExplorationNodeId
	}
	if !IsNil(o.ExplorationTurnId) {
		toSerialize["exploration_turn_id"] = o.ExplorationTurnId
	}
	if !IsNil(o.FormalizedText) {
		toSerialize["formalized_text"] = o.FormalizedText
	}
	toSerialize["hidden_info_requested"] = o.HiddenInfoRequested
	toSerialize["idempotency_replay"] = o.IdempotencyReplay
	if !IsNil(o.NodeId) {
		toSerialize["node_id"] = o.NodeId
	}
	if !IsNil(o.OverlayVersion) {
		toSerialize["overlay_version"] = o.OverlayVersion
	}
	if !IsNil(o.RedirectReason) {
		toSerialize["redirect_reason"] = o.RedirectReason
	}
	toSerialize["requires_action"] = o.RequiresAction
	return toSerialize, nil
}

func (o *V1StoryStoryIdExplorePost200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"answer",
		"cache_hit",
		"confidence",
		"detail_delta",
		"hidden_info_requested",
		"idempotency_replay",
		"requires_action",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1StoryStoryIdExplorePost200Response := _V1StoryStoryIdExplorePost200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV1StoryStoryIdExplorePost200Response)

	if err != nil {
		return err
	}

	*o = V1StoryStoryIdExplorePost200Response(varV1StoryStoryIdExplorePost200Response)

	return err
}

type NullableV1StoryStoryIdExplorePost200Response struct {
	value *V1StoryStoryIdExplorePost200Response
	isSet bool
}

func (v NullableV1StoryStoryIdExplorePost200Response) Get() *V1StoryStoryIdExplorePost200Response {
	return v.value
}

func (v *NullableV1StoryStoryIdExplorePost200Response) Set(val *V1StoryStoryIdExplorePost200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableV1StoryStoryIdExplorePost200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableV1StoryStoryIdExplorePost200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1StoryStoryIdExplorePost200Response(val *V1StoryStoryIdExplorePost200Response) *NullableV1StoryStoryIdExplorePost200Response {
	return &NullableV1StoryStoryIdExplorePost200Response{value: val, isSet: true}
}

func (v NullableV1StoryStoryIdExplorePost200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1StoryStoryIdExplorePost200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


