/*
Story Engine API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.12
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package storyteller

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PlayerErasureResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlayerErasureResponse{}

// PlayerErasureResponse Counts returned after player-owned data erasure completes.  Counts are useful for audit and support workflows while avoiding any post-erasure echo of raw content.
type PlayerErasureResponse struct {
	TenantId string `json:"tenant_id"`
	PlayerId string `json:"player_id"`
	Deleted map[string]int32 `json:"deleted"`
}

type _PlayerErasureResponse PlayerErasureResponse

// NewPlayerErasureResponse instantiates a new PlayerErasureResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlayerErasureResponse(tenantId string, playerId string, deleted map[string]int32) *PlayerErasureResponse {
	this := PlayerErasureResponse{}
	this.TenantId = tenantId
	this.PlayerId = playerId
	this.Deleted = deleted
	return &this
}

// NewPlayerErasureResponseWithDefaults instantiates a new PlayerErasureResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlayerErasureResponseWithDefaults() *PlayerErasureResponse {
	this := PlayerErasureResponse{}
	return &this
}

// GetTenantId returns the TenantId field value
func (o *PlayerErasureResponse) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *PlayerErasureResponse) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *PlayerErasureResponse) SetTenantId(v string) {
	o.TenantId = v
}

// GetPlayerId returns the PlayerId field value
func (o *PlayerErasureResponse) GetPlayerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PlayerId
}

// GetPlayerIdOk returns a tuple with the PlayerId field value
// and a boolean to check if the value has been set.
func (o *PlayerErasureResponse) GetPlayerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlayerId, true
}

// SetPlayerId sets field value
func (o *PlayerErasureResponse) SetPlayerId(v string) {
	o.PlayerId = v
}

// GetDeleted returns the Deleted field value
func (o *PlayerErasureResponse) GetDeleted() map[string]int32 {
	if o == nil {
		var ret map[string]int32
		return ret
	}

	return o.Deleted
}

// GetDeletedOk returns a tuple with the Deleted field value
// and a boolean to check if the value has been set.
func (o *PlayerErasureResponse) GetDeletedOk() (map[string]int32, bool) {
	if o == nil {
		return map[string]int32{}, false
	}
	return o.Deleted, true
}

// SetDeleted sets field value
func (o *PlayerErasureResponse) SetDeleted(v map[string]int32) {
	o.Deleted = v
}

func (o PlayerErasureResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlayerErasureResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tenant_id"] = o.TenantId
	toSerialize["player_id"] = o.PlayerId
	toSerialize["deleted"] = o.Deleted
	return toSerialize, nil
}

func (o *PlayerErasureResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tenant_id",
		"player_id",
		"deleted",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPlayerErasureResponse := _PlayerErasureResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPlayerErasureResponse)

	if err != nil {
		return err
	}

	*o = PlayerErasureResponse(varPlayerErasureResponse)

	return err
}

type NullablePlayerErasureResponse struct {
	value *PlayerErasureResponse
	isSet bool
}

func (v NullablePlayerErasureResponse) Get() *PlayerErasureResponse {
	return v.value
}

func (v *NullablePlayerErasureResponse) Set(val *PlayerErasureResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePlayerErasureResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePlayerErasureResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlayerErasureResponse(val *PlayerErasureResponse) *NullablePlayerErasureResponse {
	return &NullablePlayerErasureResponse{value: val, isSet: true}
}

func (v NullablePlayerErasureResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlayerErasureResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


