/*
Story Engine API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.13
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package storyteller

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V1AuthoringStoriesGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1AuthoringStoriesGet200Response{}

// V1AuthoringStoriesGet200Response struct for V1AuthoringStoriesGet200Response
type V1AuthoringStoriesGet200Response struct {
	HasMore bool `json:"has_more"`
	Items []V1AuthoringStoriesGet200ResponseItemsInner `json:"items"`
	NextCursor *string `json:"next_cursor,omitempty"`
}

type _V1AuthoringStoriesGet200Response V1AuthoringStoriesGet200Response

// NewV1AuthoringStoriesGet200Response instantiates a new V1AuthoringStoriesGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1AuthoringStoriesGet200Response(hasMore bool, items []V1AuthoringStoriesGet200ResponseItemsInner) *V1AuthoringStoriesGet200Response {
	this := V1AuthoringStoriesGet200Response{}
	this.HasMore = hasMore
	this.Items = items
	return &this
}

// NewV1AuthoringStoriesGet200ResponseWithDefaults instantiates a new V1AuthoringStoriesGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1AuthoringStoriesGet200ResponseWithDefaults() *V1AuthoringStoriesGet200Response {
	this := V1AuthoringStoriesGet200Response{}
	return &this
}

// GetHasMore returns the HasMore field value
func (o *V1AuthoringStoriesGet200Response) GetHasMore() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasMore
}

// GetHasMoreOk returns a tuple with the HasMore field value
// and a boolean to check if the value has been set.
func (o *V1AuthoringStoriesGet200Response) GetHasMoreOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HasMore, true
}

// SetHasMore sets field value
func (o *V1AuthoringStoriesGet200Response) SetHasMore(v bool) {
	o.HasMore = v
}

// GetItems returns the Items field value
func (o *V1AuthoringStoriesGet200Response) GetItems() []V1AuthoringStoriesGet200ResponseItemsInner {
	if o == nil {
		var ret []V1AuthoringStoriesGet200ResponseItemsInner
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *V1AuthoringStoriesGet200Response) GetItemsOk() ([]V1AuthoringStoriesGet200ResponseItemsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *V1AuthoringStoriesGet200Response) SetItems(v []V1AuthoringStoriesGet200ResponseItemsInner) {
	o.Items = v
}

// GetNextCursor returns the NextCursor field value if set, zero value otherwise.
func (o *V1AuthoringStoriesGet200Response) GetNextCursor() string {
	if o == nil || IsNil(o.NextCursor) {
		var ret string
		return ret
	}
	return *o.NextCursor
}

// GetNextCursorOk returns a tuple with the NextCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1AuthoringStoriesGet200Response) GetNextCursorOk() (*string, bool) {
	if o == nil || IsNil(o.NextCursor) {
		return nil, false
	}
	return o.NextCursor, true
}

// HasNextCursor returns a boolean if a field has been set.
func (o *V1AuthoringStoriesGet200Response) HasNextCursor() bool {
	if o != nil && !IsNil(o.NextCursor) {
		return true
	}

	return false
}

// SetNextCursor gets a reference to the given string and assigns it to the NextCursor field.
func (o *V1AuthoringStoriesGet200Response) SetNextCursor(v string) {
	o.NextCursor = &v
}

func (o V1AuthoringStoriesGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1AuthoringStoriesGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["has_more"] = o.HasMore
	toSerialize["items"] = o.Items
	if !IsNil(o.NextCursor) {
		toSerialize["next_cursor"] = o.NextCursor
	}
	return toSerialize, nil
}

func (o *V1AuthoringStoriesGet200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"has_more",
		"items",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1AuthoringStoriesGet200Response := _V1AuthoringStoriesGet200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV1AuthoringStoriesGet200Response)

	if err != nil {
		return err
	}

	*o = V1AuthoringStoriesGet200Response(varV1AuthoringStoriesGet200Response)

	return err
}

type NullableV1AuthoringStoriesGet200Response struct {
	value *V1AuthoringStoriesGet200Response
	isSet bool
}

func (v NullableV1AuthoringStoriesGet200Response) Get() *V1AuthoringStoriesGet200Response {
	return v.value
}

func (v *NullableV1AuthoringStoriesGet200Response) Set(val *V1AuthoringStoriesGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableV1AuthoringStoriesGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableV1AuthoringStoriesGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1AuthoringStoriesGet200Response(val *V1AuthoringStoriesGet200Response) *NullableV1AuthoringStoriesGet200Response {
	return &NullableV1AuthoringStoriesGet200Response{value: val, isSet: true}
}

func (v NullableV1AuthoringStoriesGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1AuthoringStoriesGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


