/*
Story Engine API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.12
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package storyteller

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ObjectSpecResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ObjectSpecResponse{}

// ObjectSpecResponse Author-defined object with type, starting location, and initial holder.
type ObjectSpecResponse struct {
	Name string `json:"name"`
	Description string `json:"description"`
	ObjectType *string `json:"object_type,omitempty"`
	LocationId *string `json:"location_id,omitempty"`
	HolderId *string `json:"holder_id,omitempty"`
}

type _ObjectSpecResponse ObjectSpecResponse

// NewObjectSpecResponse instantiates a new ObjectSpecResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewObjectSpecResponse(name string, description string) *ObjectSpecResponse {
	this := ObjectSpecResponse{}
	this.Name = name
	this.Description = description
	var objectType string = ""
	this.ObjectType = &objectType
	var locationId string = ""
	this.LocationId = &locationId
	var holderId string = ""
	this.HolderId = &holderId
	return &this
}

// NewObjectSpecResponseWithDefaults instantiates a new ObjectSpecResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewObjectSpecResponseWithDefaults() *ObjectSpecResponse {
	this := ObjectSpecResponse{}
	var objectType string = ""
	this.ObjectType = &objectType
	var locationId string = ""
	this.LocationId = &locationId
	var holderId string = ""
	this.HolderId = &holderId
	return &this
}

// GetName returns the Name field value
func (o *ObjectSpecResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ObjectSpecResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ObjectSpecResponse) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
func (o *ObjectSpecResponse) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *ObjectSpecResponse) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *ObjectSpecResponse) SetDescription(v string) {
	o.Description = v
}

// GetObjectType returns the ObjectType field value if set, zero value otherwise.
func (o *ObjectSpecResponse) GetObjectType() string {
	if o == nil || IsNil(o.ObjectType) {
		var ret string
		return ret
	}
	return *o.ObjectType
}

// GetObjectTypeOk returns a tuple with the ObjectType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectSpecResponse) GetObjectTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ObjectType) {
		return nil, false
	}
	return o.ObjectType, true
}

// HasObjectType returns a boolean if a field has been set.
func (o *ObjectSpecResponse) HasObjectType() bool {
	if o != nil && !IsNil(o.ObjectType) {
		return true
	}

	return false
}

// SetObjectType gets a reference to the given string and assigns it to the ObjectType field.
func (o *ObjectSpecResponse) SetObjectType(v string) {
	o.ObjectType = &v
}

// GetLocationId returns the LocationId field value if set, zero value otherwise.
func (o *ObjectSpecResponse) GetLocationId() string {
	if o == nil || IsNil(o.LocationId) {
		var ret string
		return ret
	}
	return *o.LocationId
}

// GetLocationIdOk returns a tuple with the LocationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectSpecResponse) GetLocationIdOk() (*string, bool) {
	if o == nil || IsNil(o.LocationId) {
		return nil, false
	}
	return o.LocationId, true
}

// HasLocationId returns a boolean if a field has been set.
func (o *ObjectSpecResponse) HasLocationId() bool {
	if o != nil && !IsNil(o.LocationId) {
		return true
	}

	return false
}

// SetLocationId gets a reference to the given string and assigns it to the LocationId field.
func (o *ObjectSpecResponse) SetLocationId(v string) {
	o.LocationId = &v
}

// GetHolderId returns the HolderId field value if set, zero value otherwise.
func (o *ObjectSpecResponse) GetHolderId() string {
	if o == nil || IsNil(o.HolderId) {
		var ret string
		return ret
	}
	return *o.HolderId
}

// GetHolderIdOk returns a tuple with the HolderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ObjectSpecResponse) GetHolderIdOk() (*string, bool) {
	if o == nil || IsNil(o.HolderId) {
		return nil, false
	}
	return o.HolderId, true
}

// HasHolderId returns a boolean if a field has been set.
func (o *ObjectSpecResponse) HasHolderId() bool {
	if o != nil && !IsNil(o.HolderId) {
		return true
	}

	return false
}

// SetHolderId gets a reference to the given string and assigns it to the HolderId field.
func (o *ObjectSpecResponse) SetHolderId(v string) {
	o.HolderId = &v
}

func (o ObjectSpecResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ObjectSpecResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["description"] = o.Description
	if !IsNil(o.ObjectType) {
		toSerialize["object_type"] = o.ObjectType
	}
	if !IsNil(o.LocationId) {
		toSerialize["location_id"] = o.LocationId
	}
	if !IsNil(o.HolderId) {
		toSerialize["holder_id"] = o.HolderId
	}
	return toSerialize, nil
}

func (o *ObjectSpecResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"description",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varObjectSpecResponse := _ObjectSpecResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varObjectSpecResponse)

	if err != nil {
		return err
	}

	*o = ObjectSpecResponse(varObjectSpecResponse)

	return err
}

type NullableObjectSpecResponse struct {
	value *ObjectSpecResponse
	isSet bool
}

func (v NullableObjectSpecResponse) Get() *ObjectSpecResponse {
	return v.value
}

func (v *NullableObjectSpecResponse) Set(val *ObjectSpecResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableObjectSpecResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableObjectSpecResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableObjectSpecResponse(val *ObjectSpecResponse) *NullableObjectSpecResponse {
	return &NullableObjectSpecResponse{value: val, isSet: true}
}

func (v NullableObjectSpecResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableObjectSpecResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


