/*
Story Engine API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.12
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package storyteller

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the EntityProvenanceEntryResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EntityProvenanceEntryResponse{}

// EntityProvenanceEntryResponse A single per-session entity provenance row.
type EntityProvenanceEntryResponse struct {
	EntityType string `json:"entity_type"`
	EntityId string `json:"entity_id"`
	IntroducedAtNodeId string `json:"introduced_at_node_id"`
	IntroducedAtChoiceId NullableString `json:"introduced_at_choice_id"`
	LastUpdatedAtNodeId NullableString `json:"last_updated_at_node_id"`
	LastUpdatedAtChoiceId NullableString `json:"last_updated_at_choice_id"`
	IntroducedAt time.Time `json:"introduced_at"`
	LastUpdatedAt NullableTime `json:"last_updated_at"`
}

type _EntityProvenanceEntryResponse EntityProvenanceEntryResponse

// NewEntityProvenanceEntryResponse instantiates a new EntityProvenanceEntryResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEntityProvenanceEntryResponse(entityType string, entityId string, introducedAtNodeId string, introducedAtChoiceId NullableString, lastUpdatedAtNodeId NullableString, lastUpdatedAtChoiceId NullableString, introducedAt time.Time, lastUpdatedAt NullableTime) *EntityProvenanceEntryResponse {
	this := EntityProvenanceEntryResponse{}
	this.EntityType = entityType
	this.EntityId = entityId
	this.IntroducedAtNodeId = introducedAtNodeId
	this.IntroducedAtChoiceId = introducedAtChoiceId
	this.LastUpdatedAtNodeId = lastUpdatedAtNodeId
	this.LastUpdatedAtChoiceId = lastUpdatedAtChoiceId
	this.IntroducedAt = introducedAt
	this.LastUpdatedAt = lastUpdatedAt
	return &this
}

// NewEntityProvenanceEntryResponseWithDefaults instantiates a new EntityProvenanceEntryResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEntityProvenanceEntryResponseWithDefaults() *EntityProvenanceEntryResponse {
	this := EntityProvenanceEntryResponse{}
	return &this
}

// GetEntityType returns the EntityType field value
func (o *EntityProvenanceEntryResponse) GetEntityType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EntityType
}

// GetEntityTypeOk returns a tuple with the EntityType field value
// and a boolean to check if the value has been set.
func (o *EntityProvenanceEntryResponse) GetEntityTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EntityType, true
}

// SetEntityType sets field value
func (o *EntityProvenanceEntryResponse) SetEntityType(v string) {
	o.EntityType = v
}

// GetEntityId returns the EntityId field value
func (o *EntityProvenanceEntryResponse) GetEntityId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EntityId
}

// GetEntityIdOk returns a tuple with the EntityId field value
// and a boolean to check if the value has been set.
func (o *EntityProvenanceEntryResponse) GetEntityIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EntityId, true
}

// SetEntityId sets field value
func (o *EntityProvenanceEntryResponse) SetEntityId(v string) {
	o.EntityId = v
}

// GetIntroducedAtNodeId returns the IntroducedAtNodeId field value
func (o *EntityProvenanceEntryResponse) GetIntroducedAtNodeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IntroducedAtNodeId
}

// GetIntroducedAtNodeIdOk returns a tuple with the IntroducedAtNodeId field value
// and a boolean to check if the value has been set.
func (o *EntityProvenanceEntryResponse) GetIntroducedAtNodeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IntroducedAtNodeId, true
}

// SetIntroducedAtNodeId sets field value
func (o *EntityProvenanceEntryResponse) SetIntroducedAtNodeId(v string) {
	o.IntroducedAtNodeId = v
}

// GetIntroducedAtChoiceId returns the IntroducedAtChoiceId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *EntityProvenanceEntryResponse) GetIntroducedAtChoiceId() string {
	if o == nil || o.IntroducedAtChoiceId.Get() == nil {
		var ret string
		return ret
	}

	return *o.IntroducedAtChoiceId.Get()
}

// GetIntroducedAtChoiceIdOk returns a tuple with the IntroducedAtChoiceId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EntityProvenanceEntryResponse) GetIntroducedAtChoiceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.IntroducedAtChoiceId.Get(), o.IntroducedAtChoiceId.IsSet()
}

// SetIntroducedAtChoiceId sets field value
func (o *EntityProvenanceEntryResponse) SetIntroducedAtChoiceId(v string) {
	o.IntroducedAtChoiceId.Set(&v)
}

// GetLastUpdatedAtNodeId returns the LastUpdatedAtNodeId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *EntityProvenanceEntryResponse) GetLastUpdatedAtNodeId() string {
	if o == nil || o.LastUpdatedAtNodeId.Get() == nil {
		var ret string
		return ret
	}

	return *o.LastUpdatedAtNodeId.Get()
}

// GetLastUpdatedAtNodeIdOk returns a tuple with the LastUpdatedAtNodeId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EntityProvenanceEntryResponse) GetLastUpdatedAtNodeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastUpdatedAtNodeId.Get(), o.LastUpdatedAtNodeId.IsSet()
}

// SetLastUpdatedAtNodeId sets field value
func (o *EntityProvenanceEntryResponse) SetLastUpdatedAtNodeId(v string) {
	o.LastUpdatedAtNodeId.Set(&v)
}

// GetLastUpdatedAtChoiceId returns the LastUpdatedAtChoiceId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *EntityProvenanceEntryResponse) GetLastUpdatedAtChoiceId() string {
	if o == nil || o.LastUpdatedAtChoiceId.Get() == nil {
		var ret string
		return ret
	}

	return *o.LastUpdatedAtChoiceId.Get()
}

// GetLastUpdatedAtChoiceIdOk returns a tuple with the LastUpdatedAtChoiceId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EntityProvenanceEntryResponse) GetLastUpdatedAtChoiceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastUpdatedAtChoiceId.Get(), o.LastUpdatedAtChoiceId.IsSet()
}

// SetLastUpdatedAtChoiceId sets field value
func (o *EntityProvenanceEntryResponse) SetLastUpdatedAtChoiceId(v string) {
	o.LastUpdatedAtChoiceId.Set(&v)
}

// GetIntroducedAt returns the IntroducedAt field value
func (o *EntityProvenanceEntryResponse) GetIntroducedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.IntroducedAt
}

// GetIntroducedAtOk returns a tuple with the IntroducedAt field value
// and a boolean to check if the value has been set.
func (o *EntityProvenanceEntryResponse) GetIntroducedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IntroducedAt, true
}

// SetIntroducedAt sets field value
func (o *EntityProvenanceEntryResponse) SetIntroducedAt(v time.Time) {
	o.IntroducedAt = v
}

// GetLastUpdatedAt returns the LastUpdatedAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *EntityProvenanceEntryResponse) GetLastUpdatedAt() time.Time {
	if o == nil || o.LastUpdatedAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.LastUpdatedAt.Get()
}

// GetLastUpdatedAtOk returns a tuple with the LastUpdatedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EntityProvenanceEntryResponse) GetLastUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastUpdatedAt.Get(), o.LastUpdatedAt.IsSet()
}

// SetLastUpdatedAt sets field value
func (o *EntityProvenanceEntryResponse) SetLastUpdatedAt(v time.Time) {
	o.LastUpdatedAt.Set(&v)
}

func (o EntityProvenanceEntryResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EntityProvenanceEntryResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["entity_type"] = o.EntityType
	toSerialize["entity_id"] = o.EntityId
	toSerialize["introduced_at_node_id"] = o.IntroducedAtNodeId
	toSerialize["introduced_at_choice_id"] = o.IntroducedAtChoiceId.Get()
	toSerialize["last_updated_at_node_id"] = o.LastUpdatedAtNodeId.Get()
	toSerialize["last_updated_at_choice_id"] = o.LastUpdatedAtChoiceId.Get()
	toSerialize["introduced_at"] = o.IntroducedAt
	toSerialize["last_updated_at"] = o.LastUpdatedAt.Get()
	return toSerialize, nil
}

func (o *EntityProvenanceEntryResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"entity_type",
		"entity_id",
		"introduced_at_node_id",
		"introduced_at_choice_id",
		"last_updated_at_node_id",
		"last_updated_at_choice_id",
		"introduced_at",
		"last_updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEntityProvenanceEntryResponse := _EntityProvenanceEntryResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEntityProvenanceEntryResponse)

	if err != nil {
		return err
	}

	*o = EntityProvenanceEntryResponse(varEntityProvenanceEntryResponse)

	return err
}

type NullableEntityProvenanceEntryResponse struct {
	value *EntityProvenanceEntryResponse
	isSet bool
}

func (v NullableEntityProvenanceEntryResponse) Get() *EntityProvenanceEntryResponse {
	return v.value
}

func (v *NullableEntityProvenanceEntryResponse) Set(val *EntityProvenanceEntryResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableEntityProvenanceEntryResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableEntityProvenanceEntryResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEntityProvenanceEntryResponse(val *EntityProvenanceEntryResponse) *NullableEntityProvenanceEntryResponse {
	return &NullableEntityProvenanceEntryResponse{value: val, isSet: true}
}

func (v NullableEntityProvenanceEntryResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEntityProvenanceEntryResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


