/*
Story Engine API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.12
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package storyteller

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LocationSpecResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LocationSpecResponse{}

// LocationSpecResponse Author-defined location with description and spatial connections.
type LocationSpecResponse struct {
	Name string `json:"name"`
	Description string `json:"description"`
	Region *string `json:"region,omitempty"`
	Atmosphere *string `json:"atmosphere,omitempty"`
	ConnectedTo []string `json:"connected_to,omitempty"`
}

type _LocationSpecResponse LocationSpecResponse

// NewLocationSpecResponse instantiates a new LocationSpecResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLocationSpecResponse(name string, description string) *LocationSpecResponse {
	this := LocationSpecResponse{}
	this.Name = name
	this.Description = description
	var region string = ""
	this.Region = &region
	var atmosphere string = ""
	this.Atmosphere = &atmosphere
	return &this
}

// NewLocationSpecResponseWithDefaults instantiates a new LocationSpecResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLocationSpecResponseWithDefaults() *LocationSpecResponse {
	this := LocationSpecResponse{}
	var region string = ""
	this.Region = &region
	var atmosphere string = ""
	this.Atmosphere = &atmosphere
	return &this
}

// GetName returns the Name field value
func (o *LocationSpecResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *LocationSpecResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *LocationSpecResponse) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
func (o *LocationSpecResponse) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *LocationSpecResponse) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *LocationSpecResponse) SetDescription(v string) {
	o.Description = v
}

// GetRegion returns the Region field value if set, zero value otherwise.
func (o *LocationSpecResponse) GetRegion() string {
	if o == nil || IsNil(o.Region) {
		var ret string
		return ret
	}
	return *o.Region
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LocationSpecResponse) GetRegionOk() (*string, bool) {
	if o == nil || IsNil(o.Region) {
		return nil, false
	}
	return o.Region, true
}

// HasRegion returns a boolean if a field has been set.
func (o *LocationSpecResponse) HasRegion() bool {
	if o != nil && !IsNil(o.Region) {
		return true
	}

	return false
}

// SetRegion gets a reference to the given string and assigns it to the Region field.
func (o *LocationSpecResponse) SetRegion(v string) {
	o.Region = &v
}

// GetAtmosphere returns the Atmosphere field value if set, zero value otherwise.
func (o *LocationSpecResponse) GetAtmosphere() string {
	if o == nil || IsNil(o.Atmosphere) {
		var ret string
		return ret
	}
	return *o.Atmosphere
}

// GetAtmosphereOk returns a tuple with the Atmosphere field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LocationSpecResponse) GetAtmosphereOk() (*string, bool) {
	if o == nil || IsNil(o.Atmosphere) {
		return nil, false
	}
	return o.Atmosphere, true
}

// HasAtmosphere returns a boolean if a field has been set.
func (o *LocationSpecResponse) HasAtmosphere() bool {
	if o != nil && !IsNil(o.Atmosphere) {
		return true
	}

	return false
}

// SetAtmosphere gets a reference to the given string and assigns it to the Atmosphere field.
func (o *LocationSpecResponse) SetAtmosphere(v string) {
	o.Atmosphere = &v
}

// GetConnectedTo returns the ConnectedTo field value if set, zero value otherwise.
func (o *LocationSpecResponse) GetConnectedTo() []string {
	if o == nil || IsNil(o.ConnectedTo) {
		var ret []string
		return ret
	}
	return o.ConnectedTo
}

// GetConnectedToOk returns a tuple with the ConnectedTo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LocationSpecResponse) GetConnectedToOk() ([]string, bool) {
	if o == nil || IsNil(o.ConnectedTo) {
		return nil, false
	}
	return o.ConnectedTo, true
}

// HasConnectedTo returns a boolean if a field has been set.
func (o *LocationSpecResponse) HasConnectedTo() bool {
	if o != nil && !IsNil(o.ConnectedTo) {
		return true
	}

	return false
}

// SetConnectedTo gets a reference to the given []string and assigns it to the ConnectedTo field.
func (o *LocationSpecResponse) SetConnectedTo(v []string) {
	o.ConnectedTo = v
}

func (o LocationSpecResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LocationSpecResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["description"] = o.Description
	if !IsNil(o.Region) {
		toSerialize["region"] = o.Region
	}
	if !IsNil(o.Atmosphere) {
		toSerialize["atmosphere"] = o.Atmosphere
	}
	if !IsNil(o.ConnectedTo) {
		toSerialize["connected_to"] = o.ConnectedTo
	}
	return toSerialize, nil
}

func (o *LocationSpecResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"description",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLocationSpecResponse := _LocationSpecResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLocationSpecResponse)

	if err != nil {
		return err
	}

	*o = LocationSpecResponse(varLocationSpecResponse)

	return err
}

type NullableLocationSpecResponse struct {
	value *LocationSpecResponse
	isSet bool
}

func (v NullableLocationSpecResponse) Get() *LocationSpecResponse {
	return v.value
}

func (v *NullableLocationSpecResponse) Set(val *LocationSpecResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableLocationSpecResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableLocationSpecResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLocationSpecResponse(val *LocationSpecResponse) *NullableLocationSpecResponse {
	return &NullableLocationSpecResponse{value: val, isSet: true}
}

func (v NullableLocationSpecResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLocationSpecResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


