/*
Story Engine API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.12
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package storyteller

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ExplorationRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExplorationRequest{}

// ExplorationRequest Request body for POST /story/{story_id}/explore.  Exploration is a non-advancing read-plus-enrichment path. The endpoint still requires an idempotency key because successful answers can persist a player-owned turn, an overlay merge, and cache metadata.  ``node_id`` is expected to be the session's current node. This keeps the route from becoming a general story-inspection API and matches the privacy boundary used by the state read endpoint. ``lock_token`` is accepted only as the existing client/device ownership token; the route still acquires the Redis session-context lock before calling the exploration service.
type ExplorationRequest struct {
	NodeId string `json:"node_id"`
	Question string `json:"question"`
	IdempotencyKey string `json:"idempotency_key"`
	LockToken NullableString `json:"lock_token,omitempty"`
}

type _ExplorationRequest ExplorationRequest

// NewExplorationRequest instantiates a new ExplorationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExplorationRequest(nodeId string, question string, idempotencyKey string) *ExplorationRequest {
	this := ExplorationRequest{}
	this.NodeId = nodeId
	this.Question = question
	this.IdempotencyKey = idempotencyKey
	return &this
}

// NewExplorationRequestWithDefaults instantiates a new ExplorationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExplorationRequestWithDefaults() *ExplorationRequest {
	this := ExplorationRequest{}
	return &this
}

// GetNodeId returns the NodeId field value
func (o *ExplorationRequest) GetNodeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NodeId
}

// GetNodeIdOk returns a tuple with the NodeId field value
// and a boolean to check if the value has been set.
func (o *ExplorationRequest) GetNodeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NodeId, true
}

// SetNodeId sets field value
func (o *ExplorationRequest) SetNodeId(v string) {
	o.NodeId = v
}

// GetQuestion returns the Question field value
func (o *ExplorationRequest) GetQuestion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Question
}

// GetQuestionOk returns a tuple with the Question field value
// and a boolean to check if the value has been set.
func (o *ExplorationRequest) GetQuestionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Question, true
}

// SetQuestion sets field value
func (o *ExplorationRequest) SetQuestion(v string) {
	o.Question = v
}

// GetIdempotencyKey returns the IdempotencyKey field value
func (o *ExplorationRequest) GetIdempotencyKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IdempotencyKey
}

// GetIdempotencyKeyOk returns a tuple with the IdempotencyKey field value
// and a boolean to check if the value has been set.
func (o *ExplorationRequest) GetIdempotencyKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IdempotencyKey, true
}

// SetIdempotencyKey sets field value
func (o *ExplorationRequest) SetIdempotencyKey(v string) {
	o.IdempotencyKey = v
}

// GetLockToken returns the LockToken field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ExplorationRequest) GetLockToken() string {
	if o == nil || IsNil(o.LockToken.Get()) {
		var ret string
		return ret
	}
	return *o.LockToken.Get()
}

// GetLockTokenOk returns a tuple with the LockToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ExplorationRequest) GetLockTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.LockToken.Get(), o.LockToken.IsSet()
}

// HasLockToken returns a boolean if a field has been set.
func (o *ExplorationRequest) HasLockToken() bool {
	if o != nil && o.LockToken.IsSet() {
		return true
	}

	return false
}

// SetLockToken gets a reference to the given NullableString and assigns it to the LockToken field.
func (o *ExplorationRequest) SetLockToken(v string) {
	o.LockToken.Set(&v)
}
// SetLockTokenNil sets the value for LockToken to be an explicit nil
func (o *ExplorationRequest) SetLockTokenNil() {
	o.LockToken.Set(nil)
}

// UnsetLockToken ensures that no value is present for LockToken, not even an explicit nil
func (o *ExplorationRequest) UnsetLockToken() {
	o.LockToken.Unset()
}

func (o ExplorationRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExplorationRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["node_id"] = o.NodeId
	toSerialize["question"] = o.Question
	toSerialize["idempotency_key"] = o.IdempotencyKey
	if o.LockToken.IsSet() {
		toSerialize["lock_token"] = o.LockToken.Get()
	}
	return toSerialize, nil
}

func (o *ExplorationRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"node_id",
		"question",
		"idempotency_key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExplorationRequest := _ExplorationRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varExplorationRequest)

	if err != nil {
		return err
	}

	*o = ExplorationRequest(varExplorationRequest)

	return err
}

type NullableExplorationRequest struct {
	value *ExplorationRequest
	isSet bool
}

func (v NullableExplorationRequest) Get() *ExplorationRequest {
	return v.value
}

func (v *NullableExplorationRequest) Set(val *ExplorationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableExplorationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableExplorationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExplorationRequest(val *ExplorationRequest) *NullableExplorationRequest {
	return &NullableExplorationRequest{value: val, isSet: true}
}

func (v NullableExplorationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExplorationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


