/*
Story Engine API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.12
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package storyteller

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the HealthResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HealthResponse{}

// HealthResponse Response body for GET /health.  ``status`` is the aggregate health: ``\"ok\"`` when all required services are reachable, ``\"degraded\"`` when some optional services are down, ``\"unavailable\"`` when a required service (Postgres or Redis) is unreachable.
type HealthResponse struct {
	Status string `json:"status"`
	Postgres string `json:"postgres"`
	Redis string `json:"redis"`
	Version string `json:"version"`
}

type _HealthResponse HealthResponse

// NewHealthResponse instantiates a new HealthResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHealthResponse(status string, postgres string, redis string, version string) *HealthResponse {
	this := HealthResponse{}
	this.Status = status
	this.Postgres = postgres
	this.Redis = redis
	this.Version = version
	return &this
}

// NewHealthResponseWithDefaults instantiates a new HealthResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHealthResponseWithDefaults() *HealthResponse {
	this := HealthResponse{}
	return &this
}

// GetStatus returns the Status field value
func (o *HealthResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *HealthResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *HealthResponse) SetStatus(v string) {
	o.Status = v
}

// GetPostgres returns the Postgres field value
func (o *HealthResponse) GetPostgres() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Postgres
}

// GetPostgresOk returns a tuple with the Postgres field value
// and a boolean to check if the value has been set.
func (o *HealthResponse) GetPostgresOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Postgres, true
}

// SetPostgres sets field value
func (o *HealthResponse) SetPostgres(v string) {
	o.Postgres = v
}

// GetRedis returns the Redis field value
func (o *HealthResponse) GetRedis() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Redis
}

// GetRedisOk returns a tuple with the Redis field value
// and a boolean to check if the value has been set.
func (o *HealthResponse) GetRedisOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Redis, true
}

// SetRedis sets field value
func (o *HealthResponse) SetRedis(v string) {
	o.Redis = v
}

// GetVersion returns the Version field value
func (o *HealthResponse) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *HealthResponse) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *HealthResponse) SetVersion(v string) {
	o.Version = v
}

func (o HealthResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HealthResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["postgres"] = o.Postgres
	toSerialize["redis"] = o.Redis
	toSerialize["version"] = o.Version
	return toSerialize, nil
}

func (o *HealthResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"postgres",
		"redis",
		"version",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHealthResponse := _HealthResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHealthResponse)

	if err != nil {
		return err
	}

	*o = HealthResponse(varHealthResponse)

	return err
}

type NullableHealthResponse struct {
	value *HealthResponse
	isSet bool
}

func (v NullableHealthResponse) Get() *HealthResponse {
	return v.value
}

func (v *NullableHealthResponse) Set(val *HealthResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableHealthResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableHealthResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHealthResponse(val *HealthResponse) *NullableHealthResponse {
	return &NullableHealthResponse{value: val, isSet: true}
}

func (v NullableHealthResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHealthResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


