/*
Story Engine API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.12
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package storyteller

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AcceptToSRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AcceptToSRequest{}

// AcceptToSRequest Request body for POST /tos/accept (player accepts the current ToS).  ``tos_version_id`` must be the UUID of the ToS version the player is accepting — validated client-side to prevent stale-version acceptance.
type AcceptToSRequest struct {
	TosVersionId string `json:"tos_version_id"`
}

type _AcceptToSRequest AcceptToSRequest

// NewAcceptToSRequest instantiates a new AcceptToSRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAcceptToSRequest(tosVersionId string) *AcceptToSRequest {
	this := AcceptToSRequest{}
	this.TosVersionId = tosVersionId
	return &this
}

// NewAcceptToSRequestWithDefaults instantiates a new AcceptToSRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAcceptToSRequestWithDefaults() *AcceptToSRequest {
	this := AcceptToSRequest{}
	return &this
}

// GetTosVersionId returns the TosVersionId field value
func (o *AcceptToSRequest) GetTosVersionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TosVersionId
}

// GetTosVersionIdOk returns a tuple with the TosVersionId field value
// and a boolean to check if the value has been set.
func (o *AcceptToSRequest) GetTosVersionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TosVersionId, true
}

// SetTosVersionId sets field value
func (o *AcceptToSRequest) SetTosVersionId(v string) {
	o.TosVersionId = v
}

func (o AcceptToSRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AcceptToSRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tos_version_id"] = o.TosVersionId
	return toSerialize, nil
}

func (o *AcceptToSRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tos_version_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAcceptToSRequest := _AcceptToSRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAcceptToSRequest)

	if err != nil {
		return err
	}

	*o = AcceptToSRequest(varAcceptToSRequest)

	return err
}

type NullableAcceptToSRequest struct {
	value *AcceptToSRequest
	isSet bool
}

func (v NullableAcceptToSRequest) Get() *AcceptToSRequest {
	return v.value
}

func (v *NullableAcceptToSRequest) Set(val *AcceptToSRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAcceptToSRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAcceptToSRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAcceptToSRequest(val *AcceptToSRequest) *NullableAcceptToSRequest {
	return &NullableAcceptToSRequest{value: val, isSet: true}
}

func (v NullableAcceptToSRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAcceptToSRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


