/*
Story Engine API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.12
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package storyteller

import (
	"encoding/json"
)

// checks if the PatchExplorationNodeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchExplorationNodeRequest{}

// PatchExplorationNodeRequest Request body for PATCH /exploration-nodes/{node_id}.  Only the ``essential`` flag can be updated via the authoring surface. Setting ``essential=True`` instructs the context builder to always include this node's ``formalized_text`` in the synthesized narrative entry regardless of byte budget.  All other fields are immutable after creation.
type PatchExplorationNodeRequest struct {
	Essential NullableBool `json:"essential,omitempty"`
}

// NewPatchExplorationNodeRequest instantiates a new PatchExplorationNodeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchExplorationNodeRequest() *PatchExplorationNodeRequest {
	this := PatchExplorationNodeRequest{}
	return &this
}

// NewPatchExplorationNodeRequestWithDefaults instantiates a new PatchExplorationNodeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchExplorationNodeRequestWithDefaults() *PatchExplorationNodeRequest {
	this := PatchExplorationNodeRequest{}
	return &this
}

// GetEssential returns the Essential field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchExplorationNodeRequest) GetEssential() bool {
	if o == nil || IsNil(o.Essential.Get()) {
		var ret bool
		return ret
	}
	return *o.Essential.Get()
}

// GetEssentialOk returns a tuple with the Essential field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchExplorationNodeRequest) GetEssentialOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Essential.Get(), o.Essential.IsSet()
}

// HasEssential returns a boolean if a field has been set.
func (o *PatchExplorationNodeRequest) HasEssential() bool {
	if o != nil && o.Essential.IsSet() {
		return true
	}

	return false
}

// SetEssential gets a reference to the given NullableBool and assigns it to the Essential field.
func (o *PatchExplorationNodeRequest) SetEssential(v bool) {
	o.Essential.Set(&v)
}
// SetEssentialNil sets the value for Essential to be an explicit nil
func (o *PatchExplorationNodeRequest) SetEssentialNil() {
	o.Essential.Set(nil)
}

// UnsetEssential ensures that no value is present for Essential, not even an explicit nil
func (o *PatchExplorationNodeRequest) UnsetEssential() {
	o.Essential.Unset()
}

func (o PatchExplorationNodeRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchExplorationNodeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Essential.IsSet() {
		toSerialize["essential"] = o.Essential.Get()
	}
	return toSerialize, nil
}

type NullablePatchExplorationNodeRequest struct {
	value *PatchExplorationNodeRequest
	isSet bool
}

func (v NullablePatchExplorationNodeRequest) Get() *PatchExplorationNodeRequest {
	return v.value
}

func (v *NullablePatchExplorationNodeRequest) Set(val *PatchExplorationNodeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchExplorationNodeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchExplorationNodeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchExplorationNodeRequest(val *PatchExplorationNodeRequest) *NullablePatchExplorationNodeRequest {
	return &NullablePatchExplorationNodeRequest{value: val, isSet: true}
}

func (v NullablePatchExplorationNodeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchExplorationNodeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


