/*
Story Engine API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.12
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package storyteller

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NodeClearEnrichmentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NodeClearEnrichmentRequest{}

// NodeClearEnrichmentRequest Admin request to clear a node's enrichment baseline.  Replacing rollback-to-version: with ExplorationNode the only meaningful reset target is \"no enrichment at all\", so a single clear operation is sufficient. reason and actor_admin_id are mandatory for the audit trail.
type NodeClearEnrichmentRequest struct {
	Reason string `json:"reason"`
	ActorAdminId string `json:"actor_admin_id"`
}

type _NodeClearEnrichmentRequest NodeClearEnrichmentRequest

// NewNodeClearEnrichmentRequest instantiates a new NodeClearEnrichmentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNodeClearEnrichmentRequest(reason string, actorAdminId string) *NodeClearEnrichmentRequest {
	this := NodeClearEnrichmentRequest{}
	this.Reason = reason
	this.ActorAdminId = actorAdminId
	return &this
}

// NewNodeClearEnrichmentRequestWithDefaults instantiates a new NodeClearEnrichmentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNodeClearEnrichmentRequestWithDefaults() *NodeClearEnrichmentRequest {
	this := NodeClearEnrichmentRequest{}
	return &this
}

// GetReason returns the Reason field value
func (o *NodeClearEnrichmentRequest) GetReason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Reason
}

// GetReasonOk returns a tuple with the Reason field value
// and a boolean to check if the value has been set.
func (o *NodeClearEnrichmentRequest) GetReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reason, true
}

// SetReason sets field value
func (o *NodeClearEnrichmentRequest) SetReason(v string) {
	o.Reason = v
}

// GetActorAdminId returns the ActorAdminId field value
func (o *NodeClearEnrichmentRequest) GetActorAdminId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ActorAdminId
}

// GetActorAdminIdOk returns a tuple with the ActorAdminId field value
// and a boolean to check if the value has been set.
func (o *NodeClearEnrichmentRequest) GetActorAdminIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ActorAdminId, true
}

// SetActorAdminId sets field value
func (o *NodeClearEnrichmentRequest) SetActorAdminId(v string) {
	o.ActorAdminId = v
}

func (o NodeClearEnrichmentRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NodeClearEnrichmentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["reason"] = o.Reason
	toSerialize["actor_admin_id"] = o.ActorAdminId
	return toSerialize, nil
}

func (o *NodeClearEnrichmentRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"reason",
		"actor_admin_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNodeClearEnrichmentRequest := _NodeClearEnrichmentRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNodeClearEnrichmentRequest)

	if err != nil {
		return err
	}

	*o = NodeClearEnrichmentRequest(varNodeClearEnrichmentRequest)

	return err
}

type NullableNodeClearEnrichmentRequest struct {
	value *NodeClearEnrichmentRequest
	isSet bool
}

func (v NullableNodeClearEnrichmentRequest) Get() *NodeClearEnrichmentRequest {
	return v.value
}

func (v *NullableNodeClearEnrichmentRequest) Set(val *NodeClearEnrichmentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableNodeClearEnrichmentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableNodeClearEnrichmentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNodeClearEnrichmentRequest(val *NodeClearEnrichmentRequest) *NullableNodeClearEnrichmentRequest {
	return &NullableNodeClearEnrichmentRequest{value: val, isSet: true}
}

func (v NullableNodeClearEnrichmentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNodeClearEnrichmentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


