/*
Story Engine API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.13
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package storyteller

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner{}

// V1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner struct for V1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner
type V1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner struct {
	Answer string `json:"answer"`
	DetailDelta map[string]map[string]interface{} `json:"detail_delta"`
	Essential bool `json:"essential"`
	FormalizedText string `json:"formalized_text"`
	Id string `json:"id"`
	NormalizedQuestion string `json:"normalized_question"`
	ParentNodeId string `json:"parent_node_id"`
	Picked bool `json:"picked"`
	Question string `json:"question"`
}

type _V1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner V1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner

// NewV1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner instantiates a new V1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner(answer string, detailDelta map[string]map[string]interface{}, essential bool, formalizedText string, id string, normalizedQuestion string, parentNodeId string, picked bool, question string) *V1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner {
	this := V1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner{}
	this.Answer = answer
	this.DetailDelta = detailDelta
	this.Essential = essential
	this.FormalizedText = formalizedText
	this.Id = id
	this.NormalizedQuestion = normalizedQuestion
	this.ParentNodeId = parentNodeId
	this.Picked = picked
	this.Question = question
	return &this
}

// NewV1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInnerWithDefaults instantiates a new V1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInnerWithDefaults() *V1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner {
	this := V1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner{}
	return &this
}

// GetAnswer returns the Answer field value
func (o *V1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner) GetAnswer() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Answer
}

// GetAnswerOk returns a tuple with the Answer field value
// and a boolean to check if the value has been set.
func (o *V1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner) GetAnswerOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Answer, true
}

// SetAnswer sets field value
func (o *V1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner) SetAnswer(v string) {
	o.Answer = v
}

// GetDetailDelta returns the DetailDelta field value
func (o *V1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner) GetDetailDelta() map[string]map[string]interface{} {
	if o == nil {
		var ret map[string]map[string]interface{}
		return ret
	}

	return o.DetailDelta
}

// GetDetailDeltaOk returns a tuple with the DetailDelta field value
// and a boolean to check if the value has been set.
func (o *V1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner) GetDetailDeltaOk() (map[string]map[string]interface{}, bool) {
	if o == nil {
		return map[string]map[string]interface{}{}, false
	}
	return o.DetailDelta, true
}

// SetDetailDelta sets field value
func (o *V1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner) SetDetailDelta(v map[string]map[string]interface{}) {
	o.DetailDelta = v
}

// GetEssential returns the Essential field value
func (o *V1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner) GetEssential() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Essential
}

// GetEssentialOk returns a tuple with the Essential field value
// and a boolean to check if the value has been set.
func (o *V1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner) GetEssentialOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Essential, true
}

// SetEssential sets field value
func (o *V1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner) SetEssential(v bool) {
	o.Essential = v
}

// GetFormalizedText returns the FormalizedText field value
func (o *V1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner) GetFormalizedText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FormalizedText
}

// GetFormalizedTextOk returns a tuple with the FormalizedText field value
// and a boolean to check if the value has been set.
func (o *V1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner) GetFormalizedTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FormalizedText, true
}

// SetFormalizedText sets field value
func (o *V1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner) SetFormalizedText(v string) {
	o.FormalizedText = v
}

// GetId returns the Id field value
func (o *V1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *V1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *V1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner) SetId(v string) {
	o.Id = v
}

// GetNormalizedQuestion returns the NormalizedQuestion field value
func (o *V1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner) GetNormalizedQuestion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NormalizedQuestion
}

// GetNormalizedQuestionOk returns a tuple with the NormalizedQuestion field value
// and a boolean to check if the value has been set.
func (o *V1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner) GetNormalizedQuestionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NormalizedQuestion, true
}

// SetNormalizedQuestion sets field value
func (o *V1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner) SetNormalizedQuestion(v string) {
	o.NormalizedQuestion = v
}

// GetParentNodeId returns the ParentNodeId field value
func (o *V1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner) GetParentNodeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ParentNodeId
}

// GetParentNodeIdOk returns a tuple with the ParentNodeId field value
// and a boolean to check if the value has been set.
func (o *V1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner) GetParentNodeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ParentNodeId, true
}

// SetParentNodeId sets field value
func (o *V1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner) SetParentNodeId(v string) {
	o.ParentNodeId = v
}

// GetPicked returns the Picked field value
func (o *V1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner) GetPicked() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Picked
}

// GetPickedOk returns a tuple with the Picked field value
// and a boolean to check if the value has been set.
func (o *V1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner) GetPickedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Picked, true
}

// SetPicked sets field value
func (o *V1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner) SetPicked(v bool) {
	o.Picked = v
}

// GetQuestion returns the Question field value
func (o *V1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner) GetQuestion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Question
}

// GetQuestionOk returns a tuple with the Question field value
// and a boolean to check if the value has been set.
func (o *V1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner) GetQuestionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Question, true
}

// SetQuestion sets field value
func (o *V1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner) SetQuestion(v string) {
	o.Question = v
}

func (o V1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["answer"] = o.Answer
	toSerialize["detail_delta"] = o.DetailDelta
	toSerialize["essential"] = o.Essential
	toSerialize["formalized_text"] = o.FormalizedText
	toSerialize["id"] = o.Id
	toSerialize["normalized_question"] = o.NormalizedQuestion
	toSerialize["parent_node_id"] = o.ParentNodeId
	toSerialize["picked"] = o.Picked
	toSerialize["question"] = o.Question
	return toSerialize, nil
}

func (o *V1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"answer",
		"detail_delta",
		"essential",
		"formalized_text",
		"id",
		"normalized_question",
		"parent_node_id",
		"picked",
		"question",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner := _V1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner)

	if err != nil {
		return err
	}

	*o = V1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner(varV1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner)

	return err
}

type NullableV1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner struct {
	value *V1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner
	isSet bool
}

func (v NullableV1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner) Get() *V1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner {
	return v.value
}

func (v *NullableV1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner) Set(val *V1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableV1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableV1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner(val *V1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner) *NullableV1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner {
	return &NullableV1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner{value: val, isSet: true}
}

func (v NullableV1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1AuthoringStoriesStoryIdExplorationNodesGet200ResponseItemsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


