/*
Story Engine API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.13
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package storyteller

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V1StoryStoryIdChoicePost200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1StoryStoryIdChoicePost200Response{}

// V1StoryStoryIdChoicePost200Response struct for V1StoryStoryIdChoicePost200Response
type V1StoryStoryIdChoicePost200Response struct {
	CharacterDelta []string `json:"character_delta"`
	Choices []V1StoryStoryIdChoicePost200ResponseChoicesInner `json:"choices"`
	EndReason *string `json:"end_reason,omitempty"`
	FlagDelta map[string]map[string]interface{} `json:"flag_delta"`
	FlagSchemaDelta map[string]map[string]interface{} `json:"flag_schema_delta"`
	HistorySummary *string `json:"history_summary,omitempty"`
	LocationDelta map[string]V1AdminStoryStoryIdGet200ResponseLocationsValue `json:"location_delta"`
	Metadata V1StoryStoryIdChoicePost200ResponseMetadata `json:"metadata"`
	NodeId string `json:"node_id"`
	NodeType string `json:"node_type"`
	ObjectDelta map[string]V1AdminStoryStoryIdGet200ResponseObjectsValue `json:"object_delta"`
	ResolvedAnchor *string `json:"resolved_anchor,omitempty"`
	Text string `json:"text"`
}

type _V1StoryStoryIdChoicePost200Response V1StoryStoryIdChoicePost200Response

// NewV1StoryStoryIdChoicePost200Response instantiates a new V1StoryStoryIdChoicePost200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1StoryStoryIdChoicePost200Response(characterDelta []string, choices []V1StoryStoryIdChoicePost200ResponseChoicesInner, flagDelta map[string]map[string]interface{}, flagSchemaDelta map[string]map[string]interface{}, locationDelta map[string]V1AdminStoryStoryIdGet200ResponseLocationsValue, metadata V1StoryStoryIdChoicePost200ResponseMetadata, nodeId string, nodeType string, objectDelta map[string]V1AdminStoryStoryIdGet200ResponseObjectsValue, text string) *V1StoryStoryIdChoicePost200Response {
	this := V1StoryStoryIdChoicePost200Response{}
	this.CharacterDelta = characterDelta
	this.Choices = choices
	this.FlagDelta = flagDelta
	this.FlagSchemaDelta = flagSchemaDelta
	this.LocationDelta = locationDelta
	this.Metadata = metadata
	this.NodeId = nodeId
	this.NodeType = nodeType
	this.ObjectDelta = objectDelta
	this.Text = text
	return &this
}

// NewV1StoryStoryIdChoicePost200ResponseWithDefaults instantiates a new V1StoryStoryIdChoicePost200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1StoryStoryIdChoicePost200ResponseWithDefaults() *V1StoryStoryIdChoicePost200Response {
	this := V1StoryStoryIdChoicePost200Response{}
	return &this
}

// GetCharacterDelta returns the CharacterDelta field value
func (o *V1StoryStoryIdChoicePost200Response) GetCharacterDelta() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.CharacterDelta
}

// GetCharacterDeltaOk returns a tuple with the CharacterDelta field value
// and a boolean to check if the value has been set.
func (o *V1StoryStoryIdChoicePost200Response) GetCharacterDeltaOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CharacterDelta, true
}

// SetCharacterDelta sets field value
func (o *V1StoryStoryIdChoicePost200Response) SetCharacterDelta(v []string) {
	o.CharacterDelta = v
}

// GetChoices returns the Choices field value
func (o *V1StoryStoryIdChoicePost200Response) GetChoices() []V1StoryStoryIdChoicePost200ResponseChoicesInner {
	if o == nil {
		var ret []V1StoryStoryIdChoicePost200ResponseChoicesInner
		return ret
	}

	return o.Choices
}

// GetChoicesOk returns a tuple with the Choices field value
// and a boolean to check if the value has been set.
func (o *V1StoryStoryIdChoicePost200Response) GetChoicesOk() ([]V1StoryStoryIdChoicePost200ResponseChoicesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Choices, true
}

// SetChoices sets field value
func (o *V1StoryStoryIdChoicePost200Response) SetChoices(v []V1StoryStoryIdChoicePost200ResponseChoicesInner) {
	o.Choices = v
}

// GetEndReason returns the EndReason field value if set, zero value otherwise.
func (o *V1StoryStoryIdChoicePost200Response) GetEndReason() string {
	if o == nil || IsNil(o.EndReason) {
		var ret string
		return ret
	}
	return *o.EndReason
}

// GetEndReasonOk returns a tuple with the EndReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1StoryStoryIdChoicePost200Response) GetEndReasonOk() (*string, bool) {
	if o == nil || IsNil(o.EndReason) {
		return nil, false
	}
	return o.EndReason, true
}

// HasEndReason returns a boolean if a field has been set.
func (o *V1StoryStoryIdChoicePost200Response) HasEndReason() bool {
	if o != nil && !IsNil(o.EndReason) {
		return true
	}

	return false
}

// SetEndReason gets a reference to the given string and assigns it to the EndReason field.
func (o *V1StoryStoryIdChoicePost200Response) SetEndReason(v string) {
	o.EndReason = &v
}

// GetFlagDelta returns the FlagDelta field value
func (o *V1StoryStoryIdChoicePost200Response) GetFlagDelta() map[string]map[string]interface{} {
	if o == nil {
		var ret map[string]map[string]interface{}
		return ret
	}

	return o.FlagDelta
}

// GetFlagDeltaOk returns a tuple with the FlagDelta field value
// and a boolean to check if the value has been set.
func (o *V1StoryStoryIdChoicePost200Response) GetFlagDeltaOk() (map[string]map[string]interface{}, bool) {
	if o == nil {
		return map[string]map[string]interface{}{}, false
	}
	return o.FlagDelta, true
}

// SetFlagDelta sets field value
func (o *V1StoryStoryIdChoicePost200Response) SetFlagDelta(v map[string]map[string]interface{}) {
	o.FlagDelta = v
}

// GetFlagSchemaDelta returns the FlagSchemaDelta field value
func (o *V1StoryStoryIdChoicePost200Response) GetFlagSchemaDelta() map[string]map[string]interface{} {
	if o == nil {
		var ret map[string]map[string]interface{}
		return ret
	}

	return o.FlagSchemaDelta
}

// GetFlagSchemaDeltaOk returns a tuple with the FlagSchemaDelta field value
// and a boolean to check if the value has been set.
func (o *V1StoryStoryIdChoicePost200Response) GetFlagSchemaDeltaOk() (map[string]map[string]interface{}, bool) {
	if o == nil {
		return map[string]map[string]interface{}{}, false
	}
	return o.FlagSchemaDelta, true
}

// SetFlagSchemaDelta sets field value
func (o *V1StoryStoryIdChoicePost200Response) SetFlagSchemaDelta(v map[string]map[string]interface{}) {
	o.FlagSchemaDelta = v
}

// GetHistorySummary returns the HistorySummary field value if set, zero value otherwise.
func (o *V1StoryStoryIdChoicePost200Response) GetHistorySummary() string {
	if o == nil || IsNil(o.HistorySummary) {
		var ret string
		return ret
	}
	return *o.HistorySummary
}

// GetHistorySummaryOk returns a tuple with the HistorySummary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1StoryStoryIdChoicePost200Response) GetHistorySummaryOk() (*string, bool) {
	if o == nil || IsNil(o.HistorySummary) {
		return nil, false
	}
	return o.HistorySummary, true
}

// HasHistorySummary returns a boolean if a field has been set.
func (o *V1StoryStoryIdChoicePost200Response) HasHistorySummary() bool {
	if o != nil && !IsNil(o.HistorySummary) {
		return true
	}

	return false
}

// SetHistorySummary gets a reference to the given string and assigns it to the HistorySummary field.
func (o *V1StoryStoryIdChoicePost200Response) SetHistorySummary(v string) {
	o.HistorySummary = &v
}

// GetLocationDelta returns the LocationDelta field value
func (o *V1StoryStoryIdChoicePost200Response) GetLocationDelta() map[string]V1AdminStoryStoryIdGet200ResponseLocationsValue {
	if o == nil {
		var ret map[string]V1AdminStoryStoryIdGet200ResponseLocationsValue
		return ret
	}

	return o.LocationDelta
}

// GetLocationDeltaOk returns a tuple with the LocationDelta field value
// and a boolean to check if the value has been set.
func (o *V1StoryStoryIdChoicePost200Response) GetLocationDeltaOk() (map[string]V1AdminStoryStoryIdGet200ResponseLocationsValue, bool) {
	if o == nil {
		return map[string]V1AdminStoryStoryIdGet200ResponseLocationsValue{}, false
	}
	return o.LocationDelta, true
}

// SetLocationDelta sets field value
func (o *V1StoryStoryIdChoicePost200Response) SetLocationDelta(v map[string]V1AdminStoryStoryIdGet200ResponseLocationsValue) {
	o.LocationDelta = v
}

// GetMetadata returns the Metadata field value
func (o *V1StoryStoryIdChoicePost200Response) GetMetadata() V1StoryStoryIdChoicePost200ResponseMetadata {
	if o == nil {
		var ret V1StoryStoryIdChoicePost200ResponseMetadata
		return ret
	}

	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value
// and a boolean to check if the value has been set.
func (o *V1StoryStoryIdChoicePost200Response) GetMetadataOk() (*V1StoryStoryIdChoicePost200ResponseMetadata, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Metadata, true
}

// SetMetadata sets field value
func (o *V1StoryStoryIdChoicePost200Response) SetMetadata(v V1StoryStoryIdChoicePost200ResponseMetadata) {
	o.Metadata = v
}

// GetNodeId returns the NodeId field value
func (o *V1StoryStoryIdChoicePost200Response) GetNodeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NodeId
}

// GetNodeIdOk returns a tuple with the NodeId field value
// and a boolean to check if the value has been set.
func (o *V1StoryStoryIdChoicePost200Response) GetNodeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NodeId, true
}

// SetNodeId sets field value
func (o *V1StoryStoryIdChoicePost200Response) SetNodeId(v string) {
	o.NodeId = v
}

// GetNodeType returns the NodeType field value
func (o *V1StoryStoryIdChoicePost200Response) GetNodeType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NodeType
}

// GetNodeTypeOk returns a tuple with the NodeType field value
// and a boolean to check if the value has been set.
func (o *V1StoryStoryIdChoicePost200Response) GetNodeTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NodeType, true
}

// SetNodeType sets field value
func (o *V1StoryStoryIdChoicePost200Response) SetNodeType(v string) {
	o.NodeType = v
}

// GetObjectDelta returns the ObjectDelta field value
func (o *V1StoryStoryIdChoicePost200Response) GetObjectDelta() map[string]V1AdminStoryStoryIdGet200ResponseObjectsValue {
	if o == nil {
		var ret map[string]V1AdminStoryStoryIdGet200ResponseObjectsValue
		return ret
	}

	return o.ObjectDelta
}

// GetObjectDeltaOk returns a tuple with the ObjectDelta field value
// and a boolean to check if the value has been set.
func (o *V1StoryStoryIdChoicePost200Response) GetObjectDeltaOk() (map[string]V1AdminStoryStoryIdGet200ResponseObjectsValue, bool) {
	if o == nil {
		return map[string]V1AdminStoryStoryIdGet200ResponseObjectsValue{}, false
	}
	return o.ObjectDelta, true
}

// SetObjectDelta sets field value
func (o *V1StoryStoryIdChoicePost200Response) SetObjectDelta(v map[string]V1AdminStoryStoryIdGet200ResponseObjectsValue) {
	o.ObjectDelta = v
}

// GetResolvedAnchor returns the ResolvedAnchor field value if set, zero value otherwise.
func (o *V1StoryStoryIdChoicePost200Response) GetResolvedAnchor() string {
	if o == nil || IsNil(o.ResolvedAnchor) {
		var ret string
		return ret
	}
	return *o.ResolvedAnchor
}

// GetResolvedAnchorOk returns a tuple with the ResolvedAnchor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1StoryStoryIdChoicePost200Response) GetResolvedAnchorOk() (*string, bool) {
	if o == nil || IsNil(o.ResolvedAnchor) {
		return nil, false
	}
	return o.ResolvedAnchor, true
}

// HasResolvedAnchor returns a boolean if a field has been set.
func (o *V1StoryStoryIdChoicePost200Response) HasResolvedAnchor() bool {
	if o != nil && !IsNil(o.ResolvedAnchor) {
		return true
	}

	return false
}

// SetResolvedAnchor gets a reference to the given string and assigns it to the ResolvedAnchor field.
func (o *V1StoryStoryIdChoicePost200Response) SetResolvedAnchor(v string) {
	o.ResolvedAnchor = &v
}

// GetText returns the Text field value
func (o *V1StoryStoryIdChoicePost200Response) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *V1StoryStoryIdChoicePost200Response) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *V1StoryStoryIdChoicePost200Response) SetText(v string) {
	o.Text = v
}

func (o V1StoryStoryIdChoicePost200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1StoryStoryIdChoicePost200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["character_delta"] = o.CharacterDelta
	toSerialize["choices"] = o.Choices
	if !IsNil(o.EndReason) {
		toSerialize["end_reason"] = o.EndReason
	}
	toSerialize["flag_delta"] = o.FlagDelta
	toSerialize["flag_schema_delta"] = o.FlagSchemaDelta
	if !IsNil(o.HistorySummary) {
		toSerialize["history_summary"] = o.HistorySummary
	}
	toSerialize["location_delta"] = o.LocationDelta
	toSerialize["metadata"] = o.Metadata
	toSerialize["node_id"] = o.NodeId
	toSerialize["node_type"] = o.NodeType
	toSerialize["object_delta"] = o.ObjectDelta
	if !IsNil(o.ResolvedAnchor) {
		toSerialize["resolved_anchor"] = o.ResolvedAnchor
	}
	toSerialize["text"] = o.Text
	return toSerialize, nil
}

func (o *V1StoryStoryIdChoicePost200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"character_delta",
		"choices",
		"flag_delta",
		"flag_schema_delta",
		"location_delta",
		"metadata",
		"node_id",
		"node_type",
		"object_delta",
		"text",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1StoryStoryIdChoicePost200Response := _V1StoryStoryIdChoicePost200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV1StoryStoryIdChoicePost200Response)

	if err != nil {
		return err
	}

	*o = V1StoryStoryIdChoicePost200Response(varV1StoryStoryIdChoicePost200Response)

	return err
}

type NullableV1StoryStoryIdChoicePost200Response struct {
	value *V1StoryStoryIdChoicePost200Response
	isSet bool
}

func (v NullableV1StoryStoryIdChoicePost200Response) Get() *V1StoryStoryIdChoicePost200Response {
	return v.value
}

func (v *NullableV1StoryStoryIdChoicePost200Response) Set(val *V1StoryStoryIdChoicePost200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableV1StoryStoryIdChoicePost200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableV1StoryStoryIdChoicePost200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1StoryStoryIdChoicePost200Response(val *V1StoryStoryIdChoicePost200Response) *NullableV1StoryStoryIdChoicePost200Response {
	return &NullableV1StoryStoryIdChoicePost200Response{value: val, isSet: true}
}

func (v NullableV1StoryStoryIdChoicePost200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1StoryStoryIdChoicePost200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


